<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Adds one Lesson per Unit of the NCTB "English For Today for Classes XI-XII"
     * textbook (the current HSC English First Paper book) under the existing
     * "Hsc english first paper words meaning" chapter (id=3). Each lesson's title
     * matches the book's own unit title so students recognize it directly.
     * Words are deduplicated globally across units (a word already used in an
     * earlier unit is not repeated in a later one) — sourced from the book's own
     * lesson vocabulary boxes where available, otherwise curated from the actual
     * reading passages of that unit.
     */
    public function up(): void
    {
        $chapterId = 3; // "Hsc english first paper words meaning"

        $units = [
            'People or Institutions Making History' => [
                ['Shackle', 'শিকল; বাধা'],
                ['Apartheid', 'বর্ণবৈষম্য নীতি'],
                ['Decade', 'দশক'],
                ['Revered', 'শ্রদ্ধেয়; পূজনীয়'],
                ['Prominent', 'বিশিষ্ট; প্রখ্যাত'],
                ['Testimony', 'সাক্ষ্য; জবানবন্দি'],
                ['Domination', 'আধিপত্য; কর্তৃত্ব'],
                ['Laud', 'প্রশংসা করা'],
                ['Prestige', 'মর্যাদা; সুনাম'],
                ['Resolve', 'দৃঢ় সংকল্প'],
                ['Rein', 'লাগাম; নিয়ন্ত্রণ ক্ষমতা'],
                ['Restore', 'পুনরুদ্ধার করা; ফিরিয়ে আনা'],
                ['Carry out', 'সম্পাদন করা; কার্যকর করা'],
                ['Capacity', 'পদমর্যাদা; সামর্থ্য'],
                ['Majority', 'সংখ্যাগরিষ্ঠতা'],
                ['Martial law', 'সামরিক আইন'],
                ['Hardship', 'দুর্ভোগ; কষ্ট'],
                ['Convert', 'রূপান্তরিত করা'],
                ['Textile', 'বস্ত্র বা বয়ন সংক্রান্ত'],
                ['Undergo', 'সহ্য করা; অভিজ্ঞতা লাভ করা'],
                ['Vessel', 'জাহাজ; বড় নৌযান'],
                ['Log', 'নথিভুক্ত করা'],
                ['Deploy', 'মোতায়েন করা; কার্যকরভাবে ব্যবহার করা'],
                ['Retrieve', 'পুনরুদ্ধার করা; ফিরিয়ে আনা'],
            ],
            'Greatest Scientific Achievements' => [
                ['Extraordinary', 'অসাধারণ'],
                ['Incredible', 'অবিশ্বাস্য'],
                ['Pique', 'আগ্রহ জাগানো'],
                ['Alter', 'পরিবর্তন করা'],
                ['Commence', 'শুরু করা'],
                ['Broadcast', 'সম্প্রচার'],
                ['Orbit', 'কক্ষপথ'],
                ['Dish', 'বাটি আকৃতির অ্যান্টেনা (স্যাটেলাইট ডিশ)'],
                ['Leprosy', 'কুষ্ঠরোগ'],
                ['Eliminate', 'নির্মূল করা'],
                ['Undetected', 'অশনাক্ত; ধরা পড়েনি এমন'],
                ['Biblical', 'বাইবেল সম্পর্কিত'],
                ['Symptom', 'লক্ষণ'],
                ['Bolster', 'শক্তিশালী করা; সমর্থন জোগানো'],
                ['Prevalent', 'ব্যাপক; প্রচলিত'],
                ['Genetic', 'বংশগত; জিনগত'],
                ['Compute', 'গণনা করা'],
                ['Infancy', 'প্রাথমিক পর্যায়; শৈশব অবস্থা'],
                ['Substance', 'পদার্থ; মূল বিষয়'],
                ['Solar', 'সৌর'],
                ['Launch', 'উৎক্ষেপণ করা'],
                ['Manned', 'মানুষ দ্বারা চালিত'],
                ['Milestone', 'মাইলফলক; উল্লেখযোগ্য ঘটনা'],
                ['Enormous', 'প্রকাণ্ড; বিশাল'],
                ['Delicate', 'সূক্ষ্ম; ভঙ্গুর'],
                ['Interior', 'অভ্যন্তরভাগ'],
                ['Tap', 'কাজে লাগানো; ব্যবহার করা'],
            ],
            'Dreams' => [
                ['Disturbing', 'উদ্বেগজনক; অস্বস্তিকর'],
                ['Recurring', 'পুনরাবৃত্ত; বারবার ঘটে এমন'],
                ['Underlying', 'অন্তর্নিহিত'],
                ['Conduit', 'মাধ্যম; নালা'],
                ['Trauma', 'মানসিক আঘাত'],
                ['Suppressed', 'দমিত; অবদমিত'],
                ['Unconscious', 'অচেতন'],
                ['Lucid', 'স্পষ্ট চেতনাসম্পন্ন'],
                ['Vanity', 'অসারতা; বৃথা অহংকার'],
                ['Recesses', 'অন্তরাল; গোপন কোণ'],
                ['Barren', 'অনুর্বর; বন্ধ্যা'],
                ['Essayist', 'প্রবন্ধকার'],
                ['Manacles', 'শিকল; হাতকড়া'],
                ['Languishing', 'ক্লিষ্ট হয়ে থাকা; ধুঁকতে থাকা'],
                ['Exile', 'নির্বাসন; নির্বাসিত ব্যক্তি'],
                ['Dramatize', 'নাটকীয়ভাবে তুলে ধরা'],
                ['Creed', 'ধর্মবিশ্বাস; মতবাদ'],
                ['Oppression', 'নিপীড়ন'],
                ['Sweltering', 'প্রচণ্ড গরম'],
                ['Oasis', 'মরূদ্যান'],
                ['Vicious', 'নিষ্ঠুর; হিংস্র'],
                ['Exalted', 'আনন্দে উদ্বেলিত; উচ্চীকৃত'],
                ['Crooked', 'বাঁকা; কুটিল'],
                ['Jangling', 'ঝনঝন শব্দযুক্ত; বিসদৃশ'],
                ['Symphony', 'সুরেলা মিলন; সিম্ফনি'],
                ['Hamlet', 'ছোট গ্রাম'],
                ['Prodigious', 'বিশাল; অসাধারণ'],
                ['Interposition', 'মধ্যস্থতা; হস্তক্ষেপ'],
                ['Nullification', 'বাতিলকরণ'],
                ['Discord', 'বিরোধ; অনৈক্য'],
            ],
            'Human Relationships' => [
                ['Etiquette', 'শিষ্টাচার; সামাজিক রীতিনীতি'],
                ['Arrogant', 'অহংকারী'],
                ['Considerate', 'বিবেচক; অন্যের প্রতি যত্নশীল'],
                ['Embarrass', 'বিব্রত করা'],
                ['Hospitable', 'আতিথেয়তাপরায়ণ'],
                ['Courtesies', 'সৌজন্যতা; ভদ্রতা'],
                ['Embellishes', 'সৌন্দর্য বৃদ্ধি করে; অলংকৃত করে'],
                ['Inculcating', 'মনে গেঁথে দেওয়া; অভ্যাসে পরিণত করা'],
                ['Submissive', 'বশ্যতাপূর্ণ; নমনীয়'],
                ['Abruptly', 'হঠাৎ; আকস্মিকভাবে'],
                ['Composed', 'স্থিরচিত্ত; শান্ত'],
                ['Ingratitude', 'অকৃতজ্ঞতা'],
                ['Feigning', 'ভান করা; কৃত্রিমভাবে দেখানো'],
                ['Folly', 'মূর্খতা'],
                ['Nigh', 'কাছাকাছি; নিকটে'],
                ['Warp', 'বাঁকা করা; বিকৃত করা'],
                ['Heirloom', 'বংশপরম্পরাগত স্মারক সম্পত্তি'],
                ['Rummaging', 'হাতড়ানো; খোঁজাখুঁজি করা'],
                ['Attic', 'চিলেকোঠা'],
                ['Creeper', 'লতা'],
                ['Walloped', 'সজোরে আঘাত করল'],
                ['Drapery', 'কাপড়ের ভাঁজ ও বিন্যাস'],
                ['Squinted', 'চোখ কুঁচকে তাকাল'],
                ['Bougainvillea', 'বোগেনভিলিয়া (এক প্রকার লতাজাতীয় ফুলগাছ)'],
                ['Marigolds', 'গাঁদা ফুল'],
            ],
            'Art and Music' => [
                ['Beholder', 'দর্শক; যে দেখে'],
                ['Repulsed', 'বিতৃষ্ণ হওয়া; ঘৃণা বোধ করা'],
                ['Enduring', 'স্থায়ী; দীর্ঘস্থায়ী'],
                ['Gaudy', 'জমকালো; কর্কশ রঙিন'],
                ['Impaired', 'ক্ষতিগ্রস্ত; দুর্বল'],
                ['Serenely', 'প্রশান্তভাবে'],
                ['Eloquent', 'বাগ্মিতাপূর্ণ; সুভাষী'],
                ['Scarce', 'দুষ্প্রাপ্য; বিরল'],
                ['Adjoining', 'সংলগ্ন; পাশাপাশি'],
                ['Brethren', 'ভ্রাতৃবৃন্দ'],
                ['Moss', 'শ্যাওলা'],
                ['Heritage', 'ঐতিহ্য'],
                ['Secular', 'ধর্মনিরপেক্ষ'],
                ['Spontaneous', 'স্বতঃস্ফূর্ত'],
                ['Dialect', 'আঞ্চলিক ভাষা; উপভাষা'],
                ['Riverine', 'নদীবিধৌত; নদীকেন্দ্রিক'],
                ['Mystical', 'রহস্যময়; আধ্যাত্মিক'],
                ['Motifs', 'নকশার মূল ভাব; মোটিফ'],
                ['Ingenuity', 'উদ্ভাবনী দক্ষতা; কুশলতা'],
                ['Tactile', 'স্পর্শযোগ্য'],
                ['Exquisite', 'অতি সুন্দর; নিখুঁত সূক্ষ্ম'],
                ['Terracotta', 'পোড়ামাটি'],
                ['Patron', 'পৃষ্ঠপোষক'],
                ['Authenticity', 'প্রকৃততা; খাঁটিত্ব'],
            ],
            'Adolescence' => [
                ['Adolescence', 'কৈশোর'],
                ['Puberty', 'বয়ঃসন্ধিকাল'],
                ['Onset', 'সূত্রপাত, শুরু'],
                ['Maturation', 'পরিপক্বতা লাভ'],
                ['Acquisition', 'অর্জন'],
                ['Vulnerable', 'ঝুঁকিপূর্ণ, অরক্ষিত'],
                ['Intervene', 'হস্তক্ষেপ করা'],
                ['Urbanization', 'নগরায়ণ'],
                ['Exploitation', 'শোষণ'],
                ['Subordination', 'অধীনতা, নিম্নমর্যাদা'],
                ['Marginalization', 'প্রান্তিকীকরণ, একঘরে করা'],
                ['Affluent', 'ধনবান, সচ্ছল'],
                ['Dowry', 'যৌতুক'],
                ['Mortality', 'মৃত্যুহার'],
                ['Undernourished', 'অপুষ্ট'],
                ['Fertility', 'উর্বরতা, প্রজননক্ষমতা'],
                ['Drudgery', 'একঘেয়ে কঠোর পরিশ্রম'],
                ['Empowerment', 'ক্ষমতায়ন'],
                ['Hemorrhage', 'রক্তক্ষরণ'],
                ['Morbidity', 'রোগাক্রান্ততা'],
                ['Mobilize', 'সংঘবদ্ধ করা, একত্রিত করা'],
                ['Holocaust', 'ব্যাপক গণহত্যা'],
                ['Sanitation', 'স্বাস্থ্যবিধান, পয়ঃনিষ্কাশন ব্যবস্থা'],
                ['Chronicle', 'কালানুক্রমিক বিবরণ লেখা'],
            ],
            'Traffic Education' => [
                ['Sophisticated', 'জটিল ও উন্নত প্রযুক্তির'],
                ['Invariably', 'সবসময়ই, ব্যতিক্রমহীনভাবে'],
                ['Restrain', 'সংযত রাখা'],
                ['Conscience', 'বিবেক'],
                ['Stuttering', 'থেমে থেমে চলা, তোতলানো'],
                ['Wrenching', 'সজোরে মোচড় দেওয়া'],
                ['Wriggling', 'কিলবিল করে এগোনো'],
                ['Wedge', 'কীলক, সরু ফাঁক'],
                ['Alleviate', 'লাঘব করা, কমানো'],
                ['Congestion', 'যানজট, ভিড়'],
                ['Paradoxically', 'স্ববিরোধীভাবে'],
                ['Whisk', 'দ্রুত নিয়ে যাওয়া'],
                ['Designate', 'নির্দিষ্ট করা, চিহ্নিত করা'],
                ['Incentive', 'প্রণোদনা'],
                ['Exhaust', 'যানবাহনের ধোঁয়া, নিষ্কাশন'],
                ['Erratic', 'অনিয়মিত, খামখেয়ালি'],
                ['Plight', 'দুর্দশা'],
                ['Vigil', 'সজাগ প্রহরা'],
                ['Agile', 'ক্ষিপ্র, চটপটে'],
                ['Swerve', 'হঠাৎ দিক পরিবর্তন করা'],
                ['Persona', 'ব্যক্তিসত্তা, চরিত্র'],
                ['Manic', 'অতি উত্তেজিত, উন্মত্তপ্রায়'],
                ['Unyielding', 'অনমনীয়, নাছোড়বান্দা'],
            ],
            'Human Rights' => [
                ['Endowed', 'গুণসম্পন্ন করা, অধিকারী করা'],
                ['Arbitrary', 'খামখেয়ালিমূলক, অযৌক্তিক'],
                ['Asylum', 'রাজনৈতিক আশ্রয়'],
                ['Persecution', 'নিপীড়ন, নির্যাতন'],
                ['Invoked', 'প্রয়োগ করা, উদ্ধৃত করা'],
                ['Prosecution', 'অভিযোগ, মামলা পরিচালনা'],
                ['Dissolution', 'বিলুপ্তি, বিচ্ছেদ'],
                ['Manifest', 'প্রকাশ করা'],
                ['Observance', 'রীতি পালন'],
                ['Impart', 'জানানো, প্রদান করা'],
                ['Suffrage', 'ভোটাধিকার'],
                ['Widowhood', 'বৈধব্য'],
                ['Wedlock', 'বিবাহবন্ধন'],
            ],
            'Diaspora' => [
                ['Diaspora', 'স্বদেশত্যাগী জনগোষ্ঠীর বিচ্ছুরণ, প্রবাসী জনগোষ্ঠী'],
                ['Ancestral', 'পূর্বপুরুষসংক্রান্ত'],
                ['Ravages', 'ধ্বংসাত্মক প্রভাব'],
                ['Borough', 'পৌর এলাকা'],
                ['Notoriety', 'কুখ্যাতি'],
                ['Tunic', 'লম্বা আলখাল্লা জাতীয় পোশাক'],
                ['Hard-won', 'কষ্টার্জিত'],
                ['Frugally', 'মিতব্যয়ীভাবে'],
                ['Protestation', 'আপত্তি, প্রতিবাদ'],
                ['Haggling', 'দরকষাকষি'],
                ['Expatriate', 'প্রবাসী'],
                ['Predominantly', 'প্রধানত'],
                ['Peasantry', 'কৃষক সম্প্রদায়'],
                ['Forge', 'গড়ে তোলা, সৃষ্টি করা'],
                ['Census', 'আদমশুমারি'],
            ],
            'Peace and Conflict' => [
                ['Antagonism', 'বিরোধিতা, শত্রুতা'],
                ['Transpire', 'ঘটা'],
                ['Dismayed', 'হতাশ, বিমর্ষ'],
                ['Blundered', 'মারাত্মক ভুল করা'],
                ['Volleyed', 'একযোগে গোলাবর্ষণ করা'],
                ['Reeled', 'টলে পড়া'],
                ['Thundered', 'বজ্রের মতো গর্জন করা'],
                ['Sabre', 'তরবারি'],
                ['Pontoon', 'অস্থায়ী ভাসমান সেতু'],
                ['Plodded', 'ভারী পায়ে ধীরে ধীরে হাঁটা'],
                ['Bridgehead', 'সেতুমাথা ঘাঁটি'],
                ['Artillery', 'কামান বাহিনী, ভারী গোলাবারুদ'],
                ['Unquiet', 'অস্থির, অশান্ত'],
                ['Pacifism', 'শান্তিবাদ'],
                ['Advocacy', 'সমর্থন, পক্ষসমর্থন'],
                ['Proliferation', 'বিস্তার, ব্যাপক প্রসার'],
                ['Philanthropist', 'জনহিতৈষী ব্যক্তি'],
                ['Arbitration', 'সালিশি, মধ্যস্থতা'],
            ],
            'Tours and Travels' => [
                ['Onslaught', 'প্রবল আক্রমণ'],
                ['Moonlit', 'চন্দ্রালোকিত, জ্যোৎস্নাময়'],
                ['Remonstrate', 'প্রতিবাদ করা'],
                ['Thatched', 'খড়ের ছাউনিযুক্ত'],
                ['Phosphorescent', 'স্বতঃপ্রভ, জ্বলজ্বলে (আলোকিত)'],
                ['Porpoise', 'শুশুক (সামুদ্রিক প্রাণী)'],
                ['Besought', 'মিনতি করেছিল (beseech-এর অতীত রূপ)'],
                ['Spittle', 'থুতু'],
                ['Parched', 'রৌদ্রদগ্ধ, শুষ্ক'],
                ['Gleamed', 'ঝিকমিক করেছিল'],
                ['Supine', 'চিত হয়ে শায়িত'],
                ['Saurian', 'সরীসৃপসদৃশ'],
                ['Disquiet', 'উদ্বেগ, অস্থিরতা'],
                ['Conjecture', 'অনুমান'],
                ['Foment', 'উসকে দেওয়া, উত্তেজিত করা'],
                ['Quell', 'দমন করা'],
                ['Animosity', 'শত্রুতা, বিদ্বেষ'],
                ['Obstinate', 'একগুঁয়ে, জেদি'],
                ['Lissome', 'ছিপছিপে ও নমনীয়'],
                ['Blandishment', 'তোষামোদ, মিষ্টি কথায় ভোলানো'],
            ],
            'Environment and Nature' => [
                ['Chronic', 'দীর্ঘস্থায়ী'],
                ['Discharge', 'নির্গত করা, ছেড়ে দেওয়া'],
                ['Stench', 'দুর্গন্ধ'],
                ['Bounty', 'পুরস্কার, দান'],
                ['Perpetual', 'চিরস্থায়ী, নিরবচ্ছিন্ন'],
                ['Flash flood', 'আকস্মিক বন্যা'],
                ['Rain forest', 'বৃষ্টি অরণ্য'],
                ['Picturesque', 'চিত্রানুগ, নয়নাভিরাম'],
                ['Expanse', 'বিস্তৃত এলাকা'],
                ['Expel', 'বহিষ্কার করা'],
                ['Homestead', 'বসতবাড়ি ও তৎসংলগ্ন জমি'],
                ['Sanctuary', 'অভয়ারণ্য, নিরাপদ আশ্রয়'],
                ['Ply', 'নিয়মিত চলাচল করা'],
                ['Encompass', 'পরিবেষ্টন করা, ঘিরে রাখা'],
                ['Brunt', 'প্রধান আঘাত'],
                ['Coastline', 'উপকূলরেখা'],
                ['Emission', 'নির্গমন (গ্যাস, তাপ ইত্যাদির)'],
                ['Degrade', 'অবনতি ঘটানো, নষ্ট করা'],
                ['Reed', 'নলখাগড়া'],
                ['Rear', 'পালন করা (পশুপাখি)'],
                ['Fry', 'পোনা মাছ'],
                ['Inland', 'দেশের অভ্যন্তরভাগ'],
            ],
            'Food Adulteration' => [
                ['Adulteration', 'ভেজাল মেশানো'],
                ['Pesticide', 'কীটনাশক'],
                ['Contaminated', 'দূষিত'],
                ['Formaldehyde', 'ফরমালডিহাইড (সংরক্ষক রাসায়নিক)'],
                ['Arsenic', 'আর্সেনিক (বিষাক্ত ধাতব মৌল)'],
                ['Chromium', 'ক্রোমিয়াম (ধাতব মৌল)'],
                ['Microbial', 'জীবাণুঘটিত'],
                ['Antibiotic', 'অ্যান্টিবায়োটিক, জীবাণুনাশক ওষুধ'],
                ['Pasteurised', 'পাস্তুরিত (জীবাণুমুক্তকৃত দুধ)'],
                ['Enacted', '(আইন) প্রণয়ন করা হয়েছিল'],
                ['Tainted', 'কলুষিত, দূষিত'],
                ['Formalin', 'ফরমালিন (সংরক্ষক রাসায়নিক)'],
                ['Coriander', 'ধনেপাতা'],
                ['Lead chromate', 'লেড ক্রোমেট (বিষাক্ত রাসায়নিক যৌগ)'],
                ['Luncheon', 'আনুষ্ঠানিক দুপুরের ভোজ'],
                ['Imposing', 'জাঁকজমকপূর্ণ, প্রভাবশালী চেহারার'],
                ['Bill of fare', 'খাদ্যতালিকা, মেনু'],
                ['Caviare', 'ক্যাভিয়ার (মাছের ডিমের বিশেষ খাবার)'],
                ['Effusive', 'অতিরিক্ত আবেগপূর্ণ (প্রশংসায়)'],
                ['Amicable', 'বন্ধুত্বপূর্ণ'],
                ['Airy', 'উদাসীন ভঙ্গিতে, হালকাভাবে'],
                ['Ingratiating', 'মন জয়ের চেষ্টাযুক্ত, তোষামোদপূর্ণ'],
                ['Humorist', 'হাস্যরসিক লেখক'],
                ['Vindictive', 'প্রতিহিংসাপরায়ণ'],
                ['Complacency', 'আত্মপ্রসাদ, নিজের প্রতি অতি সন্তুষ্টি'],
            ],
            'Myths and Literature' => [
                ['Roosting', 'বাসা বেঁধে বিশ্রাম নেওয়া (পাখির)'],
                ['Honeycombed', 'মৌচাকের মতো (ছিদ্রযুক্ত)'],
                ['Waning', 'ক্ষয়িষ্ণু (চাঁদের ক্ষয়)'],
                ['Desolate', 'নির্জন, বিরান'],
                ['Wagtail', 'খঞ্জনা পাখি (ল্যাজঝোলা পাখি)'],
                ['Thrush', 'দোয়েল জাতীয় গায়ক পাখি'],
                ['Lyre', 'বীণাজাতীয় প্রাচীন বাদ্যযন্ত্র'],
                ['Mortals', 'মরণশীল মানুষ'],
                ['Docile', 'বশংবদ, শান্তশিষ্ট'],
                ['Predatory', 'শিকারী প্রকৃতির'],
                ['Indigenous', 'স্থানীয়, দেশজ'],
                ['Slay', 'হত্যা করা (বিশেষত রাক্ষস বা দানব)'],
                ['Ravaging', 'ধ্বংসকারী, তছনছকারী'],
            ],
            'Path to Higher Education' => [
                ['Humiliation', 'অপমান'],
                ['Trampled', 'পদদলিত'],
                ['Recoup', 'ক্ষতিপূরণ করা, পুনরুদ্ধার করা'],
                ['Disseminate', 'প্রচার করা, ছড়িয়ে দেওয়া'],
                ['Aristocracy', 'আভিজাত্য, অভিজাততন্ত্র'],
                ['Perversity', 'একগুঁয়েমি, বিকৃতমনস্কতা'],
                ['Acquaintance', 'পরিচিত ব্যক্তি, পরিচিতি'],
                ['Tertiary', 'তৃতীয় স্তরের (শিক্ষা)'],
                ['Affiliated', 'অধিভুক্ত'],
                ['Symposium', 'আলোচনাসভা'],
                ['Subsidized', 'ভর্তুকিপ্রাপ্ত'],
                ['Indispensable', 'অপরিহার্য'],
                ['Barrage', 'অবিরাম বর্ষণ (তথ্যের প্রাচুর্য)'],
            ],
        ];

        $now = now();
        $unitNumber = 1;
        foreach ($units as $unitTitle => $words) {
            $lessonId = DB::table('lessons')->insertGetId([
                'title'      => 'Unit ' . $unitNumber . ': ' . $unitTitle,
                'type'       => 'vocabulary',
                'chapter_id' => $chapterId,
                'status'     => true,
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            $rows = array_map(function ($w) use ($lessonId, $now) {
                return [
                    'word'       => $w[0],
                    'meaning'    => $w[1],
                    'lesson_id'  => $lessonId,
                    'status'     => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }, $words);

            foreach (array_chunk($rows, 50) as $chunk) {
                DB::table('words')->insert($chunk);
            }

            $unitNumber++;
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $unitTitles = [
            'People or Institutions Making History',
            'Greatest Scientific Achievements',
            'Dreams',
            'Human Relationships',
            'Art and Music',
            'Adolescence',
            'Traffic Education',
            'Human Rights',
            'Diaspora',
            'Peace and Conflict',
            'Tours and Travels',
            'Environment and Nature',
            'Food Adulteration',
            'Myths and Literature',
            'Path to Higher Education',
        ];

        $unitNumber = 1;
        foreach ($unitTitles as $unitTitle) {
            $title = 'Unit ' . $unitNumber . ': ' . $unitTitle;
            $lesson = DB::table('lessons')->where('chapter_id', 3)->where('title', $title)->first();
            if ($lesson) {
                DB::table('words')->where('lesson_id', $lesson->id)->delete();
                DB::table('lessons')->where('id', $lesson->id)->delete();
            }
            $unitNumber++;
        }
    }
};
