<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Batch 1 of IELTS vocabulary words for lesson_id=4
     * ("IELTS পরীক্ষার জন্য প্রয়োজনীয় ভোকাবুলারি"). Adds 150 new words;
     * lesson had 13 before this, more batches will follow toward 500.
     */
    public function up(): void
    {
        $words = [
            ['Abundant', 'প্রচুর, প্রাচুর্যপূর্ণ', 'plentiful, ample', 'scarce, insufficient'],
            ['Advocate', 'সমর্থন করা, প্রবক্তা', 'support, champion', 'oppose, discourage'],
            ['Aesthetic', 'নান্দনিক, সৌন্দর্যবোধক', 'artistic, tasteful', 'unaesthetic, ugly'],
            ['Ambiguous', 'দ্ব্যর্থবোধক, অস্পষ্ট', 'unclear, vague', 'clear, definite'],
            ['Ambitious', 'উচ্চাকাঙ্ক্ষী', 'aspiring, driven', 'unambitious, content'],
            ['Analogous', 'সাদৃশ্যপূর্ণ', 'similar, comparable', 'different, dissimilar'],
            ['Arbitrary', 'ইচ্ছাধীন, স্বেচ্ছাচারী', 'random, capricious', 'reasoned, deliberate'],
            ['Articulate', 'সুস্পষ্টভাবে বলা', 'eloquent, fluent', 'inarticulate, incoherent'],
            ['Assert', 'দৃঢ়ভাবে বলা, দাবি করা', 'declare, affirm', 'deny, retract'],
            ['Attain', 'অর্জন করা', 'achieve, accomplish', 'fail, lose'],
            ['Authentic', 'প্রকৃত, আসল', 'genuine, real', 'fake, counterfeit'],
            ['Autonomous', 'স্বায়ত্তশাসিত', 'independent, self-governing', 'dependent, controlled'],
            ['Beneficial', 'উপকারী', 'helpful, advantageous', 'harmful, detrimental'],
            ['Bias', 'পক্ষপাত', 'prejudice, partiality', 'fairness, impartiality'],
            ['Bureaucracy', 'আমলাতন্ত্র', 'administration, officialdom', 'informality'],
            ['Coherent', 'সুসংগত', 'logical, consistent', 'incoherent, confusing'],
            ['Collaborate', 'সহযোগিতা করা', 'cooperate, team up', 'compete, oppose'],
            ['Commence', 'শুরু করা', 'begin, initiate', 'end, conclude'],
            ['Compatible', 'সামঞ্জস্যপূর্ণ', 'consistent, suitable', 'incompatible, conflicting'],
            ['Compensate', 'ক্ষতিপূরণ দেওয়া', 'reimburse, offset', 'deprive, penalize'],
            ['Comprehensive', 'ব্যাপক, পূর্ণাঙ্গ', 'thorough, extensive', 'partial, limited'],
            ['Conceive', 'কল্পনা করা, ধারণা করা', 'imagine, envisage', 'disregard, ignore'],
            ['Concise', 'সংক্ষিপ্ত', 'brief, succinct', 'lengthy, verbose'],
            ['Conducive', 'সহায়ক, অনুকূল', 'favorable, helpful', 'unfavorable, hindering'],
            ['Consensus', 'ঐকমত্য', 'agreement, accord', 'disagreement, discord'],
            ['Considerable', 'যথেষ্ট, বিবেচ্য', 'substantial, significant', 'insignificant, negligible'],
            ['Consolidate', 'সুসংহত করা', 'strengthen, unify', 'weaken, divide'],
            ['Constrain', 'সীমাবদ্ধ করা', 'restrict, limit', 'free, liberate'],
            ['Contemporary', 'সমসাময়িক', 'modern, current', 'ancient, outdated'],
            ['Contradict', 'বিরোধিতা করা', 'oppose, refute', 'confirm, support'],
            ['Controversial', 'বিতর্কিত', 'disputed, debatable', 'undisputed, agreed'],
            ['Convention', 'প্রথা, সম্মেলন', 'custom, tradition', 'innovation, novelty'],
            ['Correlate', 'সম্পর্কযুক্ত করা', 'connect, associate', 'separate, disconnect'],
            ['Credible', 'বিশ্বাসযোগ্য', 'believable, plausible', 'incredible, unbelievable'],
            ['Crucial', 'অত্যন্ত গুরুত্বপূর্ণ', 'vital, critical', 'unimportant, trivial'],
            ['Cumulative', 'ক্রমবর্ধমান, পুঞ্জীভূত', 'increasing, accumulated', 'decreasing, diminishing'],
            ['Deficient', 'অপর্যাপ্ত, ঘাটতিপূর্ণ', 'inadequate, lacking', 'sufficient, adequate'],
            ['Deliberate', 'ইচ্ছাকৃত', 'intentional, calculated', 'accidental, unintentional'],
            ['Demonstrate', 'প্রদর্শন করা', 'show, illustrate', 'conceal, hide'],
            ['Depict', 'চিত্রিত করা', 'portray, represent', 'distort, misrepresent'],
            ['Derive', 'উদ্ভূত হওয়া', 'originate, stem', 'create anew'],
            ['Deteriorate', 'অবনতি হওয়া', 'worsen, decline', 'improve, recover'],
            ['Devise', 'উদ্ভাবন করা', 'create, formulate', 'destroy, abandon'],
            ['Diminish', 'হ্রাস পাওয়া', 'decrease, reduce', 'increase, grow'],
            ['Discrepancy', 'অসঙ্গতি', 'inconsistency, difference', 'agreement, consistency'],
            ['Distinct', 'স্বতন্ত্র, স্পষ্ট', 'separate, clear', 'identical, unclear'],
            ['Diverse', 'বৈচিত্র্যময়', 'varied, assorted', 'uniform, similar'],
            ['Domestic', 'গার্হস্থ্য, অভ্যন্তরীণ', 'household, internal', 'foreign, international'],
            ['Dominant', 'প্রভাবশালী', 'prevailing, leading', 'subordinate, weak'],
            ['Drastic', 'কঠোর, আমূল', 'severe, extreme', 'mild, moderate'],
            ['Elaborate', 'বিস্তারিত বর্ণনা করা', 'detail, expand', 'simplify, abbreviate'],
            ['Eliminate', 'দূর করা', 'remove, eradicate', 'retain, include'],
            ['Eminent', 'বিশিষ্ট, প্রখ্যাত', 'distinguished, renowned', 'unknown, obscure'],
            ['Empirical', 'পরীক্ষামূলক, অভিজ্ঞতাভিত্তিক', 'experiential, observed', 'theoretical, speculative'],
            ['Enhance', 'উন্নত করা', 'improve, boost', 'worsen, reduce'],
            ['Enormous', 'বিশাল', 'huge, immense', 'tiny, minuscule'],
            ['Ensure', 'নিশ্চিত করা', 'guarantee, secure', 'risk, jeopardize'],
            ['Erode', 'ক্ষয় হওয়া', 'wear away, diminish', 'build up, strengthen'],
            ['Essential', 'অপরিহার্য', 'vital, necessary', 'unnecessary, optional'],
            ['Evaluate', 'মূল্যায়ন করা', 'assess, appraise', 'ignore, disregard'],
            ['Eventually', 'অবশেষে', 'finally, ultimately', 'initially'],
            ['Evident', 'স্পষ্ট, প্রতীয়মান', 'obvious, clear', 'unclear, hidden'],
            ['Exceed', 'অতিক্রম করা', 'surpass, outdo', 'fall short of'],
            ['Exclude', 'বাদ দেওয়া', 'omit, leave out', 'include, incorporate'],
            ['Exert', 'প্রয়োগ করা', 'apply, wield', 'withhold, restrain'],
            ['Exhaustive', 'পূর্ণাঙ্গ, নিঃশেষিত', 'comprehensive, thorough', 'incomplete, partial'],
            ['Explicit', 'সুস্পষ্ট', 'clear, direct', 'implicit, vague'],
            ['Exploit', 'কাজে লাগানো, শোষণ করা', 'utilize, take advantage', 'neglect, waste'],
            ['Facilitate', 'সহজতর করা', 'ease, assist', 'hinder, obstruct'],
            ['Feasible', 'সম্ভাব্য, করা সম্ভব', 'viable, practicable', 'infeasible, impossible'],
            ['Formulate', 'প্রণয়ন করা', 'devise, develop', 'abandon, scrap'],
            ['Fundamental', 'মৌলিক', 'basic, essential', 'secondary, minor'],
            ['Generate', 'উৎপন্ন করা', 'produce, create', 'destroy, eliminate'],
            ['Genuine', 'প্রকৃত, আন্তরিক', 'authentic, sincere', 'fake, insincere'],
            ['Gradual', 'ধীরে ধীরে', 'steady, incremental', 'sudden, abrupt'],
            ['Hamper', 'বাধা দেওয়া', 'hinder, impede', 'help, facilitate'],
            ['Hence', 'অতএব', 'therefore, thus', 'however'],
            ['Hierarchy', 'পদক্রম, স্তরবিন্যাস', 'ranking, order', 'equality'],
            ['Hypothesis', 'অনুমান, প্রকল্প', 'theory, assumption', 'fact, certainty'],
            ['Identical', 'অভিন্ন', 'same, matching', 'different, distinct'],
            ['Illustrate', 'উদাহরণসহ ব্যাখ্যা করা', 'exemplify, depict', 'obscure, confuse'],
            ['Immense', 'বিশাল', 'vast, huge', 'tiny, small'],
            ['Impact', 'প্রভাব', 'effect, influence', 'irrelevance'],
            ['Implement', 'কার্যকর করা', 'execute, carry out', 'neglect, abandon'],
            ['Implication', 'ইঙ্গিত, তাৎপর্য', 'suggestion, consequence', 'irrelevance'],
            ['Imply', 'ইঙ্গিত করা', 'suggest, indicate', 'state directly'],
            ['Inadequate', 'অপর্যাপ্ত', 'insufficient, deficient', 'adequate, sufficient'],
            ['Incentive', 'প্রণোদনা', 'motivation, inducement', 'deterrent, disincentive'],
            ['Incidence', 'ঘটনার হার', 'occurrence, frequency', 'absence'],
            ['Inconsistent', 'অসামঞ্জস্যপূর্ণ', 'contradictory, erratic', 'consistent, stable'],
            ['Incorporate', 'অন্তর্ভুক্ত করা', 'include, integrate', 'exclude, omit'],
            ['Indicate', 'নির্দেশ করা', 'show, signify', 'conceal, hide'],
            ['Inevitable', 'অনিবার্য', 'unavoidable, certain', 'avoidable, uncertain'],
            ['Infer', 'অনুমান করা', 'deduce, conclude', 'state explicitly'],
            ['Inhibit', 'বাধা দেওয়া, দমন করা', 'restrain, hinder', 'encourage, promote'],
            ['Initiate', 'শুরু করা', 'begin, launch', 'end, terminate'],
            ['Innate', 'সহজাত', 'inborn, natural', 'acquired, learned'],
            ['Innovate', 'উদ্ভাবন করা', 'invent, pioneer', 'imitate, copy'],
            ['Insight', 'অন্তর্দৃষ্টি', 'understanding, perception', 'ignorance'],
            ['Integral', 'অবিচ্ছেদ্য, অপরিহার্য', 'essential, fundamental', 'peripheral, optional'],
            ['Integrate', 'সংযুক্ত করা, একীভূত করা', 'combine, unify', 'separate, segregate'],
            ['Intense', 'প্রবল, তীব্র', 'severe, extreme', 'mild, moderate'],
            ['Interact', 'পারস্পরিক ক্রিয়া করা', 'communicate, engage', 'ignore, disregard'],
            ['Intervene', 'হস্তক্ষেপ করা', 'interfere, mediate', 'ignore, avoid'],
            ['Intrinsic', 'সহজাত, অন্তর্নিহিত', 'inherent, innate', 'extrinsic, external'],
            ['Invoke', 'আহ্বান করা, উল্লেখ করা', 'cite, summon', 'dismiss, disregard'],
            ['Isolate', 'বিচ্ছিন্ন করা', 'separate, segregate', 'combine, integrate'],
            ['Justify', 'সঙ্গত প্রমাণ করা', 'validate, defend', 'condemn, refute'],
            ['Lack', 'অভাব', 'shortage, deficiency', 'abundance, surplus'],
            ['Legislation', 'আইন প্রণয়ন', 'law, statute', 'repeal'],
            ['Legitimate', 'বৈধ', 'lawful, valid', 'illegitimate, unlawful'],
            ['Likewise', 'একইভাবে', 'similarly, also', 'differently'],
            ['Manipulate', 'কারসাজি করা', 'control, influence', 'leave alone'],
            ['Marginal', 'প্রান্তিক, সামান্য', 'minor, slight', 'significant, major'],
            ['Mechanism', 'কৌশল, ব্যবস্থা', 'system, process', 'chaos, disorder'],
            ['Mere', 'নিছক', 'simple, plain', 'significant, considerable'],
            ['Minimal', 'ন্যূনতম', 'negligible, slight', 'maximal, substantial'],
            ['Mitigate', 'প্রশমিত করা', 'alleviate, reduce', 'aggravate, worsen'],
            ['Modify', 'পরিবর্তন করা', 'alter, adjust', 'preserve, maintain'],
            ['Momentum', 'গতিবেগ, ভরবেগ', 'impetus, drive', 'inertia'],
            ['Mutual', 'পারস্পরিক', 'reciprocal, shared', 'one-sided'],
            ['Negate', 'অস্বীকার করা, বাতিল করা', 'nullify, invalidate', 'affirm, confirm'],
            ['Negligible', 'নগণ্য', 'insignificant, trivial', 'significant, considerable'],
            ['Norm', 'রীতি, মান', 'standard, convention', 'exception, anomaly'],
            ['Notion', 'ধারণা', 'idea, concept', 'fact'],
            ['Notwithstanding', 'সত্ত্বেও', 'despite, although', 'because of'],
            ['Nuance', 'সূক্ষ্ম পার্থক্য', 'subtlety, shade', 'obviousness'],
            ['Nurture', 'লালনপালন করা', 'nourish, foster', 'neglect, abandon'],
            ['Objective', 'উদ্দেশ্য, নিরপেক্ষ', 'goal, unbiased', 'subjective, biased'],
            ['Obscure', 'অস্পষ্ট', 'unclear, vague', 'clear, obvious'],
            ['Obsolete', 'অপ্রচলিত', 'outdated, defunct', 'modern, current'],
            ['Obstacle', 'বাধা', 'hindrance, barrier', 'advantage, aid'],
            ['Obtain', 'প্রাপ্ত হওয়া', 'acquire, gain', 'lose, forfeit'],
            ['Occupy', 'দখল করা', 'inhabit, hold', 'vacate, abandon'],
            ['Ongoing', 'চলমান', 'continuing, current', 'finished, completed'],
            ['Optimal', 'সর্বোত্তম', 'best, ideal', 'worst, suboptimal'],
            ['Outcome', 'ফলাফল', 'result, consequence', 'cause'],
            ['Overall', 'সামগ্রিকভাবে', 'generally, altogether', 'partially'],
            ['Overwhelm', 'অভিভূত করা', 'overpower, engulf', 'underwhelm'],
            ['Paradox', 'বিরোধাভাস', 'contradiction, anomaly', 'consistency'],
            ['Parallel', 'সমান্তরাল', 'analogous, similar', 'divergent, different'],
            ['Peer', 'সমবয়সী, সমকক্ষ', 'equal, colleague', 'superior'],
            ['Perceive', 'উপলব্ধি করা', 'sense, discern', 'overlook, miss'],
            ['Persistent', 'অবিচল, অবিরাম', 'persevering, continuous', 'fleeting, sporadic'],
            ['Perspective', 'দৃষ্টিভঙ্গি', 'viewpoint, outlook', 'facts'],
            ['Phenomenon', 'ঘটনা, বিষয়', 'occurrence, event', 'triviality'],
            ['Plausible', 'বিশ্বাসযোগ্য', 'credible, reasonable', 'implausible, unlikely'],
            ['Portray', 'চিত্রিত করা', 'depict, represent', 'distort, misrepresent'],
            ['Potential', 'সম্ভাব্য, সম্ভাবনা', 'possible, capability', 'actual, impossibility'],
            ['Precede', 'পূর্বে ঘটা', 'come before, lead', 'follow, succeed'],
        ];

        $now = now();
        $rows = array_map(function ($w) use ($now) {
            return [
                'word' => $w[0],
                'meaning' => $w[1],
                'synonyms' => $w[2],
                'antonyms' => $w[3],
                'lesson_id' => 4,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $words);

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('words')->insert($chunk);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $words = [
            'Abundant','Advocate','Aesthetic','Ambiguous','Ambitious','Analogous','Arbitrary','Articulate','Assert','Attain',
            'Authentic','Autonomous','Beneficial','Bias','Bureaucracy','Coherent','Collaborate','Commence','Compatible','Compensate',
            'Comprehensive','Conceive','Concise','Conducive','Consensus','Considerable','Consolidate','Constrain','Contemporary','Contradict',
            'Controversial','Convention','Correlate','Credible','Crucial','Cumulative','Deficient','Deliberate','Demonstrate','Depict',
            'Derive','Deteriorate','Devise','Diminish','Discrepancy','Distinct','Diverse','Domestic','Dominant','Drastic',
            'Elaborate','Eliminate','Eminent','Empirical','Enhance','Enormous','Ensure','Erode','Essential','Evaluate',
            'Eventually','Evident','Exceed','Exclude','Exert','Exhaustive','Explicit','Exploit','Facilitate','Feasible',
            'Formulate','Fundamental','Generate','Genuine','Gradual','Hamper','Hence','Hierarchy','Hypothesis','Identical',
            'Illustrate','Immense','Impact','Implement','Implication','Imply','Inadequate','Incentive','Incidence','Inconsistent',
            'Incorporate','Indicate','Inevitable','Infer','Inhibit','Initiate','Innate','Innovate','Insight','Integral',
            'Integrate','Intense','Interact','Intervene','Intrinsic','Invoke','Isolate','Justify','Lack','Legislation',
            'Legitimate','Likewise','Manipulate','Marginal','Mechanism','Mere','Minimal','Mitigate','Modify','Momentum',
            'Mutual','Negate','Negligible','Norm','Notion','Notwithstanding','Nuance','Nurture','Objective','Obscure',
            'Obsolete','Obstacle','Obtain','Occupy','Ongoing','Optimal','Outcome','Overall','Overwhelm','Paradox',
            'Parallel','Peer','Perceive','Persistent','Perspective','Phenomenon','Plausible','Portray','Potential','Precede',
        ];
        DB::table('words')->where('lesson_id', 4)->whereIn('word', $words)->delete();
    }
};
