<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Batch 2 of IELTS vocabulary for lesson_id=4. Adds 150 more words
     * (163 total so far + 150 = 313), continuing toward 500.
     */
    public function up(): void
    {
        $words = [
            ['Precise', 'নির্ভুল, সুনির্দিষ্ট', 'exact, accurate', 'imprecise, vague'],
            ['Predominant', 'প্রধান, প্রভাবশালী', 'main, principal', 'minor, secondary'],
            ['Preliminary', 'প্রাথমিক', 'initial, introductory', 'final, concluding'],
            ['Presumably', 'অনুমান করা যায়', 'probably, likely', 'certainly not'],
            ['Prevail', 'প্রাধান্য পাওয়া', 'dominate, triumph', 'lose, fail'],
            ['Prevalent', 'ব্যাপক, প্রচলিত', 'widespread, common', 'rare, uncommon'],
            ['Primarily', 'প্রধানত', 'mainly, chiefly', 'secondarily'],
            ['Prior', 'পূর্ববর্তী', 'previous, earlier', 'subsequent, later'],
            ['Proceed', 'অগ্রসর হওয়া', 'continue, advance', 'stop, halt'],
            ['Profound', 'গভীর', 'deep, intense', 'superficial, shallow'],
            ['Prohibit', 'নিষেধ করা', 'ban, forbid', 'permit, allow'],
            ['Proliferate', 'দ্রুত বৃদ্ধি পাওয়া', 'multiply, increase', 'decline, diminish'],
            ['Prominent', 'বিশিষ্ট, সুস্পষ্ট', 'notable, distinguished', 'obscure, minor'],
            ['Prompt', 'তাৎক্ষণিক, উদ্বুদ্ধ করা', 'quick, instant', 'delayed, slow'],
            ['Proportion', 'অনুপাত', 'ratio, percentage', 'disproportion'],
            ['Provoke', 'উস্কানি দেওয়া', 'incite, trigger', 'calm, soothe'],
            ['Radical', 'আমূল, মৌলবাদী', 'extreme, fundamental', 'moderate, conventional'],
            ['Random', 'এলোমেলো', 'arbitrary, haphazard', 'systematic, planned'],
            ['Rational', 'যুক্তিসঙ্গত', 'logical, sensible', 'irrational, illogical'],
            ['Reinforce', 'শক্তিশালী করা', 'strengthen, support', 'weaken, undermine'],
            ['Reject', 'প্রত্যাখ্যান করা', 'refuse, decline', 'accept, approve'],
            ['Reluctant', 'অনিচ্ছুক', 'unwilling, hesitant', 'willing, eager'],
            ['Remarkable', 'উল্লেখযোগ্য', 'notable, extraordinary', 'ordinary, unremarkable'],
            ['Rely', 'নির্ভর করা', 'depend, trust', 'distrust, doubt'],
            ['Reside', 'বসবাস করা', 'live, dwell', 'move away'],
            ['Resolve', 'সমাধান করা', 'settle, determine', 'worsen, complicate'],
            ['Restrain', 'সংযত রাখা', 'control, curb', 'release, unleash'],
            ['Restrict', 'সীমাবদ্ধ করা', 'limit, confine', 'expand, free'],
            ['Reveal', 'প্রকাশ করা', 'disclose, expose', 'conceal, hide'],
            ['Rigid', 'কঠোর, অনমনীয়', 'strict, inflexible', 'flexible, adaptable'],
            ['Robust', 'দৃঢ়, মজবুত', 'strong, sturdy', 'weak, fragile'],
            ['Scarce', 'দুষ্প্রাপ্য', 'rare, limited', 'abundant, plentiful'],
            ['Scope', 'পরিধি', 'range, extent', 'limitation'],
            ['Scrutinize', 'খুঁটিয়ে দেখা', 'examine, inspect', 'overlook, ignore'],
            ['Sequence', 'ক্রম', 'order, series', 'randomness'],
            ['Sole', 'একমাত্র', 'only, single', 'multiple, several'],
            ['Solely', 'কেবলমাত্র', 'only, exclusively', 'partly'],
            ['Sophisticated', 'পরিশীলিত, জটিল', 'advanced, refined', 'simple, unrefined'],
            ['Spontaneous', 'স্বতঃস্ফূর্ত', 'impulsive, natural', 'planned, deliberate'],
            ['Statistic', 'পরিসংখ্যান', 'figure, data', 'estimate'],
            ['Straightforward', 'সহজবোধ্য', 'simple, clear', 'complicated, confusing'],
            ['Stringent', 'কঠোর', 'strict, rigorous', 'lenient, lax'],
            ['Subsequent', 'পরবর্তী', 'following, later', 'previous, earlier'],
            ['Substantial', 'যথেষ্ট, উল্লেখযোগ্য', 'considerable, significant', 'insignificant, negligible'],
            ['Substitute', 'বিকল্প', 'replacement, alternative', 'original'],
            ['Subtle', 'সূক্ষ্ম', 'delicate, understated', 'obvious, blatant'],
            ['Sufficient', 'পর্যাপ্ত', 'adequate, enough', 'insufficient, inadequate'],
            ['Superficial', 'উপরিভাগের', 'shallow, cursory', 'profound, thorough'],
            ['Supplement', 'সম্পূরক', 'addition, extra', 'reduction'],
            ['Sustain', 'টিকিয়ে রাখা', 'maintain, support', 'abandon, discontinue'],
            ['Sustainable', 'টেকসই', 'viable, renewable', 'unsustainable'],
            ['Tackle', 'মোকাবিলা করা', 'address, confront', 'avoid, evade'],
            ['Tangible', 'স্পর্শযোগ্য, বাস্তব', 'concrete, real', 'intangible, abstract'],
            ['Tedious', 'ক্লান্তিকর', 'boring, monotonous', 'interesting, exciting'],
            ['Temporary', 'সাময়িক', 'transient, short-lived', 'permanent, lasting'],
            ['Tendency', 'প্রবণতা', 'inclination, propensity', 'aversion'],
            ['Terminate', 'সমাপ্ত করা', 'end, conclude', 'begin, start'],
            ['Thorough', 'পুঙ্খানুপুঙ্খ', 'comprehensive, meticulous', 'careless, superficial'],
            ['Trait', 'বৈশিষ্ট্য', 'characteristic, feature', 'none'],
            ['Transform', 'রূপান্তরিত করা', 'change, convert', 'preserve, maintain'],
            ['Transition', 'রূপান্তর', 'change, shift', 'stability, continuity'],
            ['Trigger', 'উদ্দীপিত করা', 'cause, prompt', 'prevent, stop'],
            ['Ultimate', 'চূড়ান্ত', 'final, eventual', 'initial, first'],
            ['Undergo', 'অতিক্রম করা', 'experience, endure', 'avoid, escape'],
            ['Underlying', 'অন্তর্নিহিত', 'fundamental, basic', 'superficial, apparent'],
            ['Undermine', 'দুর্বল করা', 'weaken, sabotage', 'strengthen, support'],
            ['Undertake', 'গ্রহণ করা', 'engage in, embark on', 'abandon, avoid'],
            ['Uniform', 'অভিন্ন, সমরূপ', 'consistent, identical', 'diverse, varied'],
            ['Unprecedented', 'নজিরবিহীন', 'unparalleled, novel', 'common, usual'],
            ['Utilize', 'ব্যবহার করা', 'use, employ', 'waste, neglect'],
            ['Valid', 'বৈধ, যুক্তিসঙ্গত', 'legitimate, sound', 'invalid, unfounded'],
            ['Vary', 'পরিবর্তিত হওয়া', 'differ, fluctuate', 'remain same'],
            ['Verify', 'যাচাই করা', 'confirm, validate', 'disprove, refute'],
            ['Versatile', 'বহুমুখী', 'adaptable, flexible', 'limited, inflexible'],
            ['Viable', 'কার্যকর, সম্ভাব্য', 'feasible, workable', 'unviable, impossible'],
            ['Vigorous', 'প্রাণবন্ত, জোরালো', 'energetic, robust', 'weak, lethargic'],
            ['Virtually', 'কার্যত', 'almost, nearly', 'exactly'],
            ['Vital', 'অত্যাবশ্যক', 'essential, crucial', 'unimportant, trivial'],
            ['Vulnerable', 'দুর্বল, ঝুঁকিপূর্ণ', 'exposed, susceptible', 'protected, secure'],
            ['Widespread', 'ব্যাপক', 'extensive, prevalent', 'limited, rare'],
            ['Withstand', 'সহ্য করা', 'endure, resist', 'succumb, yield'],
            ['Yield', 'ফলন, মেনে নেওয়া', 'produce, submit', 'resist, withhold'],
            ['Accelerate', 'ত্বরান্বিত করা', 'speed up, hasten', 'slow down, decelerate'],
            ['Accumulate', 'সঞ্চিত করা', 'gather, amass', 'disperse, squander'],
            ['Accurate', 'সঠিক', 'precise, exact', 'inaccurate, wrong'],
            ['Acknowledge', 'স্বীকার করা', 'admit, recognize', 'deny, ignore'],
            ['Acquire', 'অর্জন করা', 'obtain, gain', 'lose, forfeit'],
            ['Adapt', 'খাপ খাওয়ানো', 'adjust, modify', 'resist change'],
            ['Adequate', 'পর্যাপ্ত', 'sufficient, satisfactory', 'inadequate, insufficient'],
            ['Adhere', 'আঁকড়ে থাকা, মেনে চলা', 'stick to, comply', 'deviate, abandon'],
            ['Adjacent', 'সন্নিহিত', 'neighboring, adjoining', 'distant, remote'],
            ['Adverse', 'প্রতিকূল', 'unfavorable, harmful', 'favorable, beneficial'],
            ['Affiliate', 'সংযুক্ত করা', 'associate, ally', 'separate, disconnect'],
            ['Aggregate', 'সমষ্টি', 'total, sum', 'individual part'],
            ['Allocate', 'বরাদ্দ করা', 'assign, distribute', 'withhold'],
            ['Alter', 'পরিবর্তন করা', 'change, modify', 'preserve, retain'],
            ['Ample', 'পর্যাপ্ত, যথেষ্ট', 'abundant, plentiful', 'insufficient, scarce'],
            ['Anticipate', 'পূর্বানুমান করা', 'expect, foresee', 'be surprised'],
            ['Apparent', 'স্পষ্ট, আপাত', 'obvious, evident', 'hidden, unclear'],
            ['Appreciable', 'লক্ষণীয়', 'noticeable, considerable', 'negligible, imperceptible'],
            ['Approximate', 'আনুমানিক', 'estimated, rough', 'exact, precise'],
            ['Aspire', 'আকাঙ্ক্ষা করা', 'aim, strive', 'give up'],
            ['Assess', 'মূল্যায়ন করা', 'evaluate, appraise', 'ignore, disregard'],
            ['Assume', 'অনুমান করা', 'presume, suppose', 'know for certain'],
            ['Assure', 'আশ্বস্ত করা', 'guarantee, reassure', 'worry, alarm'],
            ['Attribute', 'আরোপ করা, গুণ', 'ascribe, quality', 'unrelated feature'],
            ['Boost', 'বৃদ্ধি করা', 'increase, enhance', 'decrease, reduce'],
            ['Capacity', 'ক্ষমতা', 'ability, capability', 'incapacity'],
            ['Circumstance', 'পরিস্থিতি', 'situation, condition', 'irrelevance'],
            ['Comprise', 'গঠিত হওয়া', 'consist of, include', 'exclude'],
            ['Concurrent', 'একযোগে ঘটমান', 'simultaneous, parallel', 'sequential'],
            ['Confine', 'সীমাবদ্ধ রাখা', 'restrict, limit', 'free, release'],
            ['Conform', 'মানিয়ে চলা', 'comply, adapt', 'rebel, deviate'],
            ['Constant', 'স্থির, অবিরাম', 'continuous, unchanging', 'variable, fluctuating'],
            ['Contribute', 'অবদান রাখা', 'donate, add', 'withhold, detract'],
            ['Convey', 'প্রকাশ করা, বহন করা', 'communicate, express', 'conceal'],
            ['Cope', 'মোকাবিলা করা', 'manage, handle', 'fail, give up'],
            ['Counteract', 'প্রতিরোধ করা', 'neutralize, offset', 'reinforce'],
            ['Criteria', 'মানদণ্ড', 'standards, benchmarks', 'none'],
            ['Curb', 'দমন করা', 'restrain, control', 'encourage, unleash'],
            ['Decline', 'হ্রাস পাওয়া, প্রত্যাখ্যান করা', 'decrease, refuse', 'increase, accept'],
            ['Defer', 'স্থগিত রাখা', 'postpone, delay', 'proceed, advance'],
            ['Deploy', 'মোতায়েন করা', 'position, station', 'withdraw'],
            ['Detect', 'সনাক্ত করা', 'identify, discover', 'overlook, miss'],
            ['Deviate', 'বিচ্যুত হওয়া', 'diverge, stray', 'conform, adhere'],
            ['Diligent', 'অধ্যবসায়ী', 'hardworking, industrious', 'lazy, idle'],
            ['Discern', 'বিচক্ষণতার সাথে বোঝা', 'perceive, distinguish', 'overlook, confuse'],
            ['Disperse', 'ছড়িয়ে পড়া', 'scatter, spread', 'gather, congregate'],
            ['Displace', 'স্থানচ্যুত করা', 'replace, dislodge', 'keep in place'],
            ['Disrupt', 'বিঘ্নিত করা', 'disturb, interrupt', 'maintain, sustain'],
            ['Distort', 'বিকৃত করা', 'twist, misrepresent', 'clarify, represent accurately'],
            ['Diversify', 'বৈচিত্র্য আনা', 'vary, expand', 'standardize'],
            ['Durable', 'টেকসই', 'long-lasting, sturdy', 'fragile, flimsy'],
            ['Elicit', 'বের করে আনা', 'draw out, evoke', 'suppress'],
            ['Embark', 'শুরু করা, আরোহণ করা', 'begin, undertake', 'finish, disembark'],
            ['Emerge', 'উদ্ভূত হওয়া', 'appear, arise', 'disappear, vanish'],
            ['Emphasize', 'গুরুত্ব দেওয়া', 'stress, highlight', 'downplay, ignore'],
            ['Enable', 'সক্ষম করা', 'allow, permit', 'prevent, hinder'],
            ['Encompass', 'অন্তর্ভুক্ত করা', 'include, cover', 'exclude'],
            ['Endeavor', 'প্রচেষ্টা করা', 'attempt, strive', 'give up, abandon'],
            ['Endure', 'সহ্য করা', 'withstand, tolerate', 'succumb, surrender'],
            ['Enforce', 'প্রয়োগ করা', 'implement, impose', 'neglect, ignore'],
            ['Engage', 'নিযুক্ত করা', 'involve, participate', 'disengage, withdraw'],
            ['Enrich', 'সমৃদ্ধ করা', 'enhance, improve', 'impoverish, deplete'],
            ['Entail', 'জড়িত থাকা', 'involve, require', 'exclude'],
            ['Envisage', 'কল্পনা করা', 'imagine, foresee', 'disregard'],
            ['Equivalent', 'সমতুল্য', 'equal, comparable', 'different, unequal'],
            ['Erratic', 'অনিয়মিত', 'inconsistent, unpredictable', 'consistent, stable'],
            ['Escalate', 'বৃদ্ধি পাওয়া', 'intensify, increase', 'de-escalate, diminish'],
            ['Establish', 'প্রতিষ্ঠা করা', 'found, set up', 'dissolve, abolish'],
        ];

        $now = now();
        $rows = array_map(function ($w) use ($now) {
            return [
                'word' => $w[0],
                'meaning' => $w[1],
                'synonyms' => $w[2],
                'antonyms' => $w[3],
                'lesson_id' => 4,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $words);

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('words')->insert($chunk);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $words = [
            'Precise','Predominant','Preliminary','Presumably','Prevail','Prevalent','Primarily','Prior','Proceed','Profound',
            'Prohibit','Proliferate','Prominent','Prompt','Proportion','Provoke','Radical','Random','Rational','Reinforce',
            'Reject','Reluctant','Remarkable','Rely','Reside','Resolve','Restrain','Restrict','Reveal','Rigid',
            'Robust','Scarce','Scope','Scrutinize','Sequence','Sole','Solely','Sophisticated','Spontaneous','Statistic',
            'Straightforward','Stringent','Subsequent','Substantial','Substitute','Subtle','Sufficient','Superficial','Supplement','Sustain',
            'Sustainable','Tackle','Tangible','Tedious','Temporary','Tendency','Terminate','Thorough','Trait','Transform',
            'Transition','Trigger','Ultimate','Undergo','Underlying','Undermine','Undertake','Uniform','Unprecedented','Utilize',
            'Valid','Vary','Verify','Versatile','Viable','Vigorous','Virtually','Vital','Vulnerable','Widespread',
            'Withstand','Yield','Accelerate','Accumulate','Accurate','Acknowledge','Acquire','Adapt','Adequate','Adhere',
            'Adjacent','Adverse','Affiliate','Aggregate','Allocate','Alter','Ample','Anticipate','Apparent','Appreciable',
            'Approximate','Aspire','Assess','Assume','Assure','Attribute','Boost','Capacity','Circumstance','Comprise',
            'Concurrent','Confine','Conform','Constant','Contribute','Convey','Cope','Counteract','Criteria','Curb',
            'Decline','Defer','Deploy','Detect','Deviate','Diligent','Discern','Disperse','Displace','Disrupt',
            'Distort','Diversify','Durable','Elicit','Embark','Emerge','Emphasize','Enable','Encompass','Endeavor',
            'Endure','Enforce','Engage','Enrich','Entail','Envisage','Equivalent','Erratic','Escalate','Establish',
        ];
        DB::table('words')->where('lesson_id', 4)->whereIn('word', $words)->delete();
    }
};
