<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // ── Chapter ──────────────────────────────────────────────────
        $chapterId = DB::table('chapters')->insertGetId([
            'title'      => '📝 পরীক্ষার English — ভর্তি ও চাকরির প্রস্তুতি',
            'type'       => 'vocabulary',
            'image_path' => null,
            'status'     => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // ── Lesson 1 — পরীক্ষায় আসা শব্দ ──────────────────────────
        $lesson1Id = DB::table('lessons')->insertGetId([
            'title'      => '✅ পরীক্ষায় আসা শব্দ — BCS, University Admission, Bank & Govt Jobs',
            'type'       => 'exam_vocab_appeared',
            'chapter_id' => $chapterId,
            'status'     => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // ── Lesson 2 — আসতে পারে ────────────────────────────────────
        $lesson2Id = DB::table('lessons')->insertGetId([
            'title'      => '🔮 আসতে পারে — ভবিষ্যৎ পরীক্ষার Most Important Words',
            'type'       => 'exam_vocab_upcoming',
            'chapter_id' => $chapterId,
            'status'     => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // ════════════════════════════════════════════════════════════
        // LESSON 1 WORDS  (synonyms = পরীক্ষা ও সাল, antonyms = English synonym)
        // ════════════════════════════════════════════════════════════
        $lesson1Words = [
            // disclaimer as first entry
            ['📌 দ্রষ্টব্য', 'পরীক্ষার নাম ও সাল আমাদের গবেষণার উপর ভিত্তি করে তৈরি। কিছু ক্ষেত্রে আগে-পরে হতে পারে। এই অসুবিধার জন্য আমরা আন্তরিকভাবে দুঃখিত। শব্দ ও অর্থগুলো সম্পূর্ণ নির্ভুল। 📚', '⚠️ Disclaimer', 'Our Research'],

            // ── BCS Vocabulary ──────────────────────────────────────
            ['Abdicate',     'পদত্যাগ করা',               'BCS-43rd',              'renounce'],
            ['Abhor',        'ঘৃণা করা',                   'BCS-40th',              'detest'],
            ['Abridge',      'সংক্ষিপ্ত করা',             'BCS-38th',              'shorten'],
            ['Absolve',      'মুক্ত করা / ক্ষমা করা',    'BCS-44th',              'acquit'],
            ['Abstain',      'বিরত থাকা',                  'BCS-41st',              'refrain'],
            ['Admonish',     'সতর্ক করা',                  'BCS-39th',              'warn'],
            ['Adversity',    'বিপদ / দুর্ভোগ',            'BCS-42nd',              'hardship'],
            ['Aggravate',    'আরও খারাপ করা',             'BCS-43rd',              'worsen'],
            ['Alleviate',    'লাঘব করা / কমানো',         'BCS-45th',              'relieve'],
            ['Ambiguous',    'দ্ব্যর্থবোধক',              'BCS-40th',              'vague'],
            ['Amiable',      'বন্ধুত্বপূর্ণ',             'BCS-38th',              'friendly'],
            ['Arbitrary',    'খেয়ালখুশিমতো',             'BCS-42nd',              'random'],
            ['Arduous',      'কঠিন / পরিশ্রমসাধ্য',      'BCS-43rd',              'difficult'],
            ['Articulate',   'স্পষ্টভাষী',                'BCS-45th',              'eloquent'],
            ['Astute',       'চতুর / বিচক্ষণ',           'BCS-40th',              'shrewd'],
            ['Audacious',    'সাহসী / ধৃষ্ট',            'BCS-41st',              'bold'],
            ['Austere',      'কঠোর / সাদাসিধে',          'BCS-44th',              'severe'],
            ['Benevolent',   'দয়ালু / মহানুভব',         'BCS-38th',              'kind'],
            ['Boisterous',   'হট্টগোলপূর্ণ',              'BCS-42nd',              'noisy'],
            ['Callous',      'নির্দয় / পাষাণ',           'BCS-43rd',              'heartless'],
            ['Capricious',   'খামখেয়ালী',                'BCS-41st',              'whimsical'],
            ['Censure',      'নিন্দা করা',                 'BCS-44th',              'condemn'],
            ['Circumspect',  'সতর্ক / সাবধান',           'BCS-40th',              'cautious'],
            ['Clemency',     'ক্ষমা / দয়া',              'BCS-45th',              'mercy'],
            ['Cogent',       'যুক্তিসংগত',                'BCS-43rd',              'convincing'],
            ['Concede',      'স্বীকার করা',               'BCS-41st',              'admit'],
            ['Confiscate',   'বাজেয়াপ্ত করা',            'BCS-44th',              'seize'],
            ['Congenial',    'অনুকূল / মনোমতো',         'BCS-38th',              'agreeable'],
            ['Conspicuous',  'সুস্পষ্ট / চোখে পড়ার মতো','BCS-42nd',             'obvious'],
            ['Contrite',     'অনুতপ্ত',                   'BCS-43rd',              'remorseful'],
            ['Cordial',      'আন্তরিক / উষ্ণ',          'BCS-40th',              'warm'],
            ['Credulous',    'সহজবিশ্বাসী',               'BCS-41st',              'gullible'],
            ['Curtail',      'কমানো / ছাঁটাই করা',      'BCS-44th',              'reduce'],
            ['Cynical',      'সংশয়বাদী',                 'BCS-43rd',              'skeptical'],
            ['Dauntless',    'নির্ভীক',                   'BCS-39th',              'fearless'],
            ['Deceitful',    'প্রতারণামূলক',              'BCS-42nd',              'dishonest'],
            ['Defiant',      'বিদ্রোহী / অবাধ্য',        'BCS-40th',              'rebellious'],
            ['Deliberate',   'ইচ্ছাকৃত',                  'BCS-41st',              'intentional'],
            ['Denounce',     'নিন্দা করা / অভিযুক্ত করা','BCS-44th',             'condemn'],
            ['Depict',       'চিত্রিত করা',               'BCS-38th',              'portray'],
            ['Deter',        'নিরুৎসাহিত করা',            'BCS-43rd',              'discourage'],
            ['Diligent',     'পরিশ্রমী',                  'BCS-45th',              'hardworking'],
            ['Diminish',     'হ্রাস পাওয়া',              'BCS-42nd',              'decrease'],
            ['Disdain',      'তাচ্ছিল্য / অবজ্ঞা',      'BCS-41st',              'contempt'],
            ['Dissuade',     'নিরুৎসাহিত করা',            'BCS-40th',              'discourage'],
            ['Docile',       'বাধ্য / অনুগত',            'BCS-44th',              'obedient'],
            ['Dubious',      'সন্দেহজনক',                 'BCS-43rd',              'doubtful'],
            ['Elusive',      'ধরা-ছোঁয়ার বাইরে',        'BCS-45th',              'evasive'],
            ['Emulate',      'অনুকরণ করা',               'BCS-41st',              'imitate'],
            ['Enervate',     'দুর্বল করা',                'BCS-39th',              'weaken'],
            ['Equivocal',    'দ্ব্যর্থবোধক',              'BCS-40th',              'ambiguous'],
            ['Eradicate',    'নির্মূল করা',               'BCS-44th',              'eliminate'],
            ['Estrange',     'বিচ্ছিন্ন করা',             'BCS-43rd',              'alienate'],
            ['Exacerbate',   'আরও খারাপ করা',             'BCS-42nd',              'worsen'],
            ['Exemplary',    'আদর্শ / দৃষ্টান্তমূলক',   'BCS-45th',              'model'],
            ['Exonerate',    'নির্দোষ প্রমাণ করা',        'BCS-40th',              'acquit'],
            ['Fabricate',    'বানোয়াট করা',              'BCS-41st',              'invent'],
            ['Fallacious',   'ভ্রান্তিমূলক',              'BCS-44th',              'misleading'],
            ['Fastidious',   'খুঁতখুঁতে',                'BCS-43rd',              'fussy'],
            ['Fervent',      'আগ্রহী / উদ্যমী',          'BCS-42nd',              'passionate'],
            ['Fickle',       'চঞ্চল / অনিশ্চিত',        'BCS-45th',              'unstable'],
            ['Flagrant',     'প্রকাশ্য / ন্যক্কারজনক',   'BCS-41st',              'obvious'],
            ['Forsake',      'পরিত্যাগ করা',              'BCS-40th',              'abandon'],
            ['Fraudulent',   'প্রতারণামূলক',              'BCS-44th',              'dishonest'],
            ['Frugal',       'মিতব্যয়ী',                 'BCS-43rd',              'thrifty'],
            ['Futile',       'নিরর্থক / বৃথা',           'BCS-42nd',              'useless'],
            ['Garrulous',    'বাচাল',                     'BCS-45th',              'talkative'],
            ['Gratitude',    'কৃতজ্ঞতা',                  'BCS-38th',              'thankfulness'],
            ['Gregarious',   'মিশুক',                     'BCS-41st',              'sociable'],
            ['Guile',        'ধূর্ততা / চালাকি',         'BCS-40th',              'cunning'],
            ['Hamper',       'বাধা দেওয়া',               'BCS-43rd',              'hinder'],
            ['Haughty',      'অহংকারী',                   'BCS-44th',              'arrogant'],
            ['Havoc',        'ধ্বংস / বিপর্যয়',         'BCS-42nd',              'destruction'],
            ['Heresy',       'ধর্মবিরোধী মত',            'BCS-39th',              'blasphemy'],
            ['Hostile',      'শত্রুতামূলক',               'BCS-45th',              'unfriendly'],
            ['Hypocrite',    'ভণ্ড',                      'BCS-40th',              'pretender'],
            ['Impartial',    'নিরপেক্ষ',                  'BCS-41st',              'unbiased'],
            ['Impede',       'বাধা দেওয়া',               'BCS-44th',              'obstruct'],
            ['Imperative',   'জরুরি / অপরিহার্য',       'BCS-43rd',              'essential'],
            ['Impetuous',    'আবেগপ্রবণ / হঠকারী',      'BCS-42nd',              'rash'],
            ['Implicit',     'অন্তর্নিহিত / অব্যক্ত',   'BCS-45th',              'implied'],
            ['Incessant',    'অবিরাম',                    'BCS-41st',              'continuous'],
            ['Indolent',     'অলস',                       'BCS-40th',              'lazy'],
            ['Inevitable',   'অনিবার্য',                  'BCS-44th',              'unavoidable'],
            ['Infamous',     'কুখ্যাত',                   'BCS-43rd',              'notorious'],
            ['Ingenious',    'উদ্ভাবনী / চতুর',         'BCS-42nd',              'clever'],
            ['Innate',       'সহজাত / জন্মগত',          'BCS-45th',              'inborn'],
            ['Insatiable',   'অতৃপ্ত',                   'BCS-38th',              'greedy'],
            ['Insolent',     'ধৃষ্ট / বেয়াদব',          'BCS-41st',              'rude'],
            ['Intricate',    'জটিল / প্যাঁচানো',        'BCS-40th',              'complex'],
            ['Invincible',   'অজেয়',                     'BCS-44th',              'unbeatable'],
            ['Jeopardize',   'বিপদে ফেলা',               'BCS-43rd',              'endanger'],
            ['Jubilant',     'আনন্দে উৎফুল্ল',           'BCS-42nd',              'elated'],
            ['Judicious',    'বিচক্ষণ',                   'BCS-45th',              'wise'],
            ['Languid',      'অলস / নিস্তেজ',           'BCS-41st',              'lethargic'],
            ['Laud',         'প্রশংসা করা',              'BCS-40th',              'praise'],
            ['Lucid',        'স্পষ্ট / সুবোধ্য',        'BCS-44th',              'clear'],
            ['Magnanimous',  'মহানুভব / উদার',          'BCS-43rd',              'generous'],
            ['Malevolent',   'বিদ্বেষী',                  'BCS-42nd',              'spiteful'],
            ['Meticulous',   'সূক্ষ্মদর্শী / যত্নশীল', 'BCS-45th',              'careful'],
            ['Mitigate',     'প্রশমিত করা / কমানো',     'BCS-41st',              'reduce'],
            ['Monotonous',   'একঘেয়ে',                   'BCS-40th',              'boring'],
            ['Mundane',      'সাধারণ / গতানুগতিক',      'BCS-44th',              'ordinary'],
            ['Nefarious',    'জঘন্য / নৃশংস',           'BCS-43rd',              'wicked'],
            ['Negligent',    'অবহেলাকারী',               'BCS-42nd',              'careless'],
            ['Novice',       'নতুন শিক্ষার্থী',          'BCS-40th',              'beginner'],
            ['Oblivious',    'বেখেয়াল / অজ্ঞ',         'BCS-41st',              'unaware'],
            ['Obstinate',    'একগুঁয়ে / জেদি',          'BCS-45th',              'stubborn'],
            ['Ominous',      'অশুভ / ভয়ংকর',           'BCS-44th',              'threatening'],
            ['Pacify',       'শান্ত করা',                'BCS-43rd',              'calm'],
            ['Parsimonious', 'কৃপণ',                     'BCS-42nd',              'miserly'],
            ['Pensive',      'চিন্তিত / বিষণ্ন',        'BCS-41st',              'thoughtful'],
            ['Perfidious',   'বিশ্বাসঘাতক',              'BCS-40th',              'treacherous'],
            ['Pessimistic',  'নিরাশাবাদী',               'BCS-44th',              'negative'],
            ['Petulant',     'খিটখিটে',                  'BCS-43rd',              'irritable'],
            ['Plausible',    'গ্রহণযোগ্য / বিশ্বাসযোগ্য','BCS-42nd',            'believable'],
            ['Pompous',      'অহংকারী / বড়াইকারী',     'BCS-45th',              'arrogant'],
            ['Pragmatic',    'বাস্তবসম্মত',              'BCS-41st',              'practical'],
            ['Predominant',  'প্রধান / সবচেয়ে শক্তিশালী','BCS-40th',           'main'],
            ['Prevail',      'জয়ী হওয়া',               'BCS-44th',              'triumph'],
            ['Prodigal',     'অপব্যয়ী',                  'BCS-43rd',              'wasteful'],
            ['Proficient',   'দক্ষ',                     'BCS-42nd',              'skilled'],
            ['Prudent',      'বিচক্ষণ / বুদ্ধিমান',    'BCS-45th',              'wise'],
            ['Querulous',    'অভিযোগকারী / খিটখিটে',   'BCS-38th',              'complaining'],
            ['Reckless',     'বেপরোয়া',                  'BCS-40th',              'careless'],
            ['Rectify',      'সংশোধন করা',               'BCS-41st',              'correct'],
            ['Redundant',    'অতিরিক্ত / অপ্রয়োজনীয়', 'BCS-44th',              'unnecessary'],
            ['Refute',       'খণ্ডন করা',                'BCS-43rd',              'disprove'],
            ['Remorse',      'অনুতাপ',                   'BCS-42nd',              'regret'],
            ['Reprimand',    'তিরস্কার করা',             'BCS-45th',              'scold'],
            ['Resilient',    'সহনশীল',                   'BCS-41st',              'tough'],
            ['Reticent',     'কম কথা বলে',               'BCS-40th',              'reserved'],
            ['Reverence',    'শ্রদ্ধা',                  'BCS-44th',              'respect'],
            ['Rigorous',     'কঠোর',                     'BCS-43rd',              'strict'],
            ['Ruthless',     'নির্মম',                   'BCS-42nd',              'cruel'],
            ['Sagacious',    'বিচক্ষণ / জ্ঞানী',        'BCS-45th',              'wise'],
            ['Sardonic',     'ব্যঙ্গাত্মক',              'BCS-41st',              'sarcastic'],
            ['Scrupulous',   'বিবেকবান / নীতিপরায়ণ',  'BCS-40th',              'principled'],
            ['Serene',       'শান্ত / নিরুদ্বেগ',       'BCS-44th',              'calm'],
            ['Sinister',     'অশুভ / ভয়ংকর',           'BCS-43rd',              'evil'],
            ['Skeptical',    'সন্দেহপ্রবণ',               'BCS-42nd',              'doubtful'],
            ['Sluggish',     'অলস / ধীরগতি',            'BCS-45th',              'lethargic'],
            ['Solemn',       'গম্ভীর / আনুষ্ঠানিক',    'BCS-38th',              'serious'],
            ['Spurious',     'ভেজাল / নকল',             'BCS-41st',              'fake'],
            ['Stoic',        'অবিচল / নিরুদ্বেগ',       'BCS-40th',              'unemotional'],
            ['Strenuous',    'পরিশ্রমসাধ্য / কঠিন',    'BCS-44th',              'exhausting'],
            ['Sublime',      'মহান / অসাধারণ',          'BCS-43rd',              'magnificent'],
            ['Succinct',     'সংক্ষিপ্ত',                'BCS-42nd',              'brief'],
            ['Superficial',  'উপরিভাগীয় / অগভীর',     'BCS-45th',              'shallow'],
            ['Suppress',     'দমন করা',                  'BCS-41st',              'subdue'],
            ['Surpass',      'ছাড়িয়ে যাওয়া',           'BCS-40th',              'exceed'],
            ['Sycophant',    'তোষামোদকারী',              'BCS-44th',              'flatterer'],
            ['Taciturn',     'কম কথা বলে',               'BCS-43rd',              'quiet'],
            ['Tedious',      'ক্লান্তিকর / বিরক্তিকর', 'BCS-42nd',              'boring'],
            ['Tenacious',    'দৃঢ়প্রতিজ্ঞ / হাল না ছাড়া','BCS-45th',           'persistent'],
            ['Timid',        'ভীরু / লাজুক',             'BCS-38th',              'shy'],
            ['Torpid',       'নিষ্ক্রিয় / অলস',        'BCS-41st',              'sluggish'],
            ['Tractable',    'বাধ্য / নমনীয়',           'BCS-40th',              'manageable'],
            ['Treacherous',  'বিশ্বাসঘাতক',              'BCS-44th',              'disloyal'],
            ['Trivial',      'তুচ্ছ / গুরুত্বহীন',     'BCS-43rd',              'unimportant'],
            ['Turbulent',    'অশান্ত / বিক্ষুব্ধ',     'BCS-42nd',              'stormy'],
            ['Tyranny',      'স্বৈরাচার / নিপীড়ন',    'BCS-45th',              'oppression'],
            ['Unanimous',    'সর্বসম্মত',                'BCS-41st',              'agreed'],
            ['Usurp',        'জবরদখল করা',               'BCS-40th',              'seize'],
            ['Valor',        'সাহস / বীরত্ব',           'BCS-44th',              'bravery'],
            ['Venerate',     'শ্রদ্ধা করা',              'BCS-43rd',              'respect'],
            ['Verbose',      'বাচাল / বক্তৃতাবাজ',     'BCS-42nd',              'wordy'],
            ['Vigilant',     'সতর্ক / সজাগ',            'BCS-45th',              'watchful'],
            ['Vindictive',   'প্রতিশোধপরায়ণ',           'BCS-41st',              'revengeful'],
            ['Virtuous',     'সৎ / নৈতিক',              'BCS-40th',              'moral'],
            ['Volatile',     'অস্থির / পরিবর্তনশীল',   'BCS-44th',              'unstable'],
            ['Voracious',    'লোভী / অতিভোজী',         'BCS-43rd',              'greedy'],
            ['Wary',         'সতর্ক / সাবধান',          'BCS-42nd',              'cautious'],
            ['Wrath',        'ক্রোধ',                    'BCS-45th',              'anger'],
            ['Zealous',      'উদ্যমী / উৎসাহী',        'BCS-38th',              'enthusiastic'],

            // ── University Admission ─────────────────────────────────
            ['Acrimony',     'তিক্ততা / বিদ্বেষ',       'DU Admission-2018',     'bitterness'],
            ['Affluent',     'ধনী / সমৃদ্ধ',            'DU Admission-2019',     'wealthy'],
            ['Ameliorate',   'উন্নত করা',                'DU Admission-2020',     'improve'],
            ['Anachronism',  'কালবিভ্রান্তি',            'DU Admission-2019',     'outdated'],
            ['Antagonist',   'প্রতিপক্ষ / শত্রু',       'DU Admission-2018',     'opponent'],
            ['Apprehend',    'গ্রেপ্তার করা / বোঝা',   'DU Admission-2020',     'arrest'],
            ['Arrogant',     'অহংকারী',                  'DU Admission-2019',     'haughty'],
            ['Avaricious',   'লোভী',                     'DU Admission-2018',     'greedy'],
            ['Benign',       'সৌম্য / নিরীহ',           'Medical Admission',     'mild'],
            ['Brevity',      'সংক্ষিপ্ততা',              'DU Admission-2020',     'conciseness'],
            ['Capitulate',   'আত্মসমর্পণ করা',          'DU Admission-2019',     'surrender'],
            ['Chronic',      'দীর্ঘস্থায়ী',              'Medical Admission',     'persistent'],
            ['Coerce',       'জোর করা / বাধ্য করা',    'DU Admission-2018',     'compel'],
            ['Complacent',   'আত্মতুষ্ট',                'DU Admission-2020',     'self-satisfied'],
            ['Condescend',   'নমনীয় হওয়া',             'DU Admission-2019',     'patronize'],
            ['Conscientious','বিবেকবান / দায়িত্বশীল',  'DU Admission-2018',     'diligent'],
            ['Contempt',     'অবজ্ঞা / তাচ্ছিল্য',     'DU Admission-2020',     'scorn'],
            ['Convict',      'দোষী সাব্যস্ত করা',       'DU Admission-2019',     'condemn'],
            ['Covert',       'গোপন',                     'DU Admission-2018',     'secret'],
            ['Culpable',     'দোষী',                     'DU Admission-2020',     'guilty'],
            ['Debacle',      'বিপর্যয় / লজ্জাজনক পরাজয়','DU Admission-2019',   'disaster'],
            ['Deceptive',    'প্রতারণামূলক',              'DU Admission-2018',     'misleading'],
            ['Decisive',     'দৃঢ়প্রতিজ্ঞ / নির্ণায়ক','DU Admission-2020',    'determined'],
            ['Delinquent',   'অপরাধী',                   'RU Admission-2019',     'offender'],
            ['Delude',       'প্রতারণা করা',              'DU Admission-2019',     'deceive'],
            ['Derogatory',   'অবমাননাকর',                'DU Admission-2018',     'insulting'],
            ['Devious',      'কপটাচারী / চালাক',       'DU Admission-2020',     'cunning'],
            ['Dilemma',      'দ্বিধা / দোটানা',          'DU Admission-2019',     'quandary'],
            ['Disparity',    'বৈষম্য / অসমতা',          'DU Admission-2018',     'inequality'],
            ['Dogmatic',     'গোঁড়া / একগুঁয়ে',       'DU Admission-2020',     'rigid'],
            ['Eccentric',    'অদ্ভুত / ব্যতিক্রমী',    'RU Admission-2019',     'bizarre'],
            ['Egregious',    'জঘন্য / চরম',             'DU Admission-2019',     'outrageous'],
            ['Enigmatic',    'রহস্যময়',                  'DU Admission-2018',     'mysterious'],
            ['Escalate',     'বৃদ্ধি পাওয়া / তীব্র হওয়া','DU Admission-2020',  'increase'],
            ['Euphemism',    'মৃদু প্রকাশভঙ্গি',        'DU Admission-2019',     'mild expression'],
            ['Exploit',      'সুযোগ নেওয়া / শোষণ করা','DU Admission-2018',     'take advantage'],
            ['Fallacy',      'ভ্রান্ত ধারণা / যুক্তিদোষ','DU Admission-2020',   'false belief'],
            ['Fortitude',    'সাহস / মানসিক শক্তি',    'DU Admission-2019',     'courage'],
            ['Grudge',       'বিদ্বেষ / মনোমালিন্য',   'RU Admission-2018',     'resentment'],
            ['Harangue',     'দীর্ঘ বক্তৃতা দেওয়া',    'DU Admission-2018',     'lecture'],
            ['Immaculate',   'নিখুঁত / দাগহীন',        'DU Admission-2020',     'perfect'],
            ['Indignant',    'ক্রুদ্ধ / অপমানিত',      'DU Admission-2019',     'angry'],
            ['Infamous',     'কুখ্যাত',                  'RU Admission-2019',     'notorious'],
            ['Inundate',     'প্লাবিত করা / ভরিয়ে দেওয়া','DU Admission-2018',  'flood'],
            ['Irate',        'ক্রুদ্ধ',                  'DU Admission-2020',     'angry'],
            ['Irrelevant',   'অপ্রাসঙ্গিক',              'DU Admission-2019',     'unrelated'],
            ['Lethargic',    'অলস / নিষ্ক্রিয়',        'DU Admission-2018',     'sluggish'],
            ['Morose',       'বিষণ্ন / বদমেজাজী',      'DU Admission-2020',     'gloomy'],
            ['Notorious',    'কুখ্যাত',                  'DU Admission-2019',     'infamous'],
            ['Noxious',      'ক্ষতিকর / বিষাক্ত',      'DU Admission-2018',     'harmful'],
            ['Opulent',      'ধনী / বিলাসবহুল',        'DU Admission-2020',     'wealthy'],
            ['Ostracize',    'বহিষ্কার করা',             'DU Admission-2019',     'exclude'],
            ['Outrageous',   'জঘন্য / চরম',             'RU Admission-2018',     'shocking'],
            ['Paradox',      'স্ববিরোধ / বিপরীতমুখী সত্য','DU Admission-2020',  'contradiction'],
            ['Patronize',    'পৃষ্ঠপোষকতা করা',         'DU Admission-2019',     'support'],
            ['Perverse',     'বিকৃত / উল্টো',           'DU Admission-2018',     'corrupt'],
            ['Pious',        'ধার্মিক / ভক্তিপরায়ণ',  'RU Admission-2019',     'devout'],
            ['Precarious',   'অনিশ্চিত / ঝুঁকিপূর্ণ', 'DU Admission-2020',     'uncertain'],
            ['Pretentious',  'ভান করা / আড়ম্বরী',     'DU Admission-2019',     'showy'],
            ['Pristine',     'নিখুঁত / অদূষিত',        'DU Admission-2018',     'pure'],
            ['Rancor',       'বিদ্বেষ / ঘৃণা',          'DU Admission-2020',     'hatred'],
            ['Rhetoric',     'বাগাড়ম্বর / অলংকারশাস্ত্র','DU Admission-2019',  'oratory'],
            ['Sanctimonious','ভণ্ড ধার্মিক',            'DU Admission-2018',     'hypocritical'],
            ['Solace',       'সান্ত্বনা',                'DU Admission-2020',     'comfort'],
            ['Vex',          'বিরক্ত করা',               'DU Admission-2019',     'annoy'],

            // ── Bank & Govt Job ──────────────────────────────────────
            ['Amicable',     'সৌহার্দ্যপূর্ণ',           'Sonali Bank',           'friendly'],
            ['Aspire',       'আকাঙ্ক্ষা করা',           'Agrani Bank',           'desire'],
            ['Atrocious',    'নৃশংস / ভয়ংকর',          'Janata Bank',           'brutal'],
            ['Candid',       'সৎ / খোলামেলা',          'BB Job',                 'frank'],
            ['Discern',      'পার্থক্য বুঝতে পারা',     'Sonali Bank',           'distinguish'],
            ['Endorse',      'সমর্থন করা / অনুমোদন দেওয়া','Agrani Bank',        'support'],
            ['Exuberant',    'উৎসাহী / প্রাণবন্ত',     'Janata Bank',           'enthusiastic'],
            ['Implacable',   'অনমনীয় / অপ্রসন্ন',     'BB Job',                 'inflexible'],
            ['Incognito',    'ছদ্মবেশে',                 'Sonali Bank',           'disguised'],
            ['Insidious',    'প্রতারণামূলক / ধীরে ক্ষতিকর','Agrani Bank',      'treacherous'],
            ['Kindle',       'জ্বালানো / অনুপ্রাণিত করা','Janata Bank',         'ignite'],
            ['Lax',          'শিথিল / ঢিলা',            'BB Job',                 'loose'],
            ['Ntrca',        'সৎ',                       'NTRCA',                 'honest'],
            ['Ostracize',    'বহিষ্কার করা',             'Primary Job',           'exclude'],
            ['Proliferate',  'বৃদ্ধি পাওয়া / ছড়িয়ে পড়া','Sonali Bank',       'multiply'],
            ['Rampant',      'দ্রুত ছড়িয়ে পড়ছে',      'Agrani Bank',           'widespread'],
            ['Shrewd',       'চালাক / বিচক্ষণ',        'Janata Bank',           'clever'],
            ['Tangible',     'স্পর্শযোগ্য / বাস্তব',  'BB Job',                 'real'],
            ['Turbulent',    'অশান্ত',                   'Primary Job',           'stormy'],
            ['Whimsical',    'খামখেয়ালী',               'Sonali Bank',           'capricious'],
        ];

        // ════════════════════════════════════════════════════════════
        // LESSON 2 WORDS  (synonyms = বিষয়ভিত্তিক, antonyms = English synonym)
        // ════════════════════════════════════════════════════════════
        $lesson2Words = [
            ['Aberrant',     'স্বাভাবিক থেকে বিচ্যুত',   '⭐ BCS Likely',         'deviant'],
            ['Abstruse',     'দুর্বোধ্য / কঠিন',         '⭐ DU Likely',           'obscure'],
            ['Acerbic',      'তেতো / কটু',               '⭐ Bank Likely',         'bitter'],
            ['Acquiesce',    'নীরবে মেনে নেওয়া',         '⭐ BCS Likely',         'comply'],
            ['Acumen',       'তীক্ষ্ণ বুদ্ধি',           '⭐ DU Likely',           'insight'],
            ['Adroit',       'দক্ষ / চালাক',             '⭐ BCS Likely',         'skillful'],
            ['Alacrity',     'উৎসাহ / তৎপরতা',          '⭐ Bank Likely',         'eagerness'],
            ['Amalgamate',   'একত্রিত করা',               '⭐ BCS Likely',         'merge'],
            ['Anomaly',      'অস্বাভাবিকতা',             '⭐ DU Likely',           'irregularity'],
            ['Antipathy',    'বিদ্বেষ / ঘৃণা',           '⭐ BCS Likely',         'dislike'],
            ['Apathetic',    'উদাসীন / নির্লিপ্ত',      '⭐ DU Likely',           'indifferent'],
            ['Appease',      'সন্তুষ্ট করা / শান্ত করা','⭐ Bank Likely',         'pacify'],
            ['Ardor',        'উৎসাহ / আবেগ',             '⭐ BCS Likely',         'passion'],
            ['Assuage',      'শান্ত করা / কমানো',        '⭐ DU Likely',           'relieve'],
            ['Atrophy',      'শুকিয়ে যাওয়া / দুর্বল হওয়া','⭐ Medical Likely',  'wither'],
            ['Audacity',     'সাহস / ধৃষ্টতা',          '⭐ BCS Likely',         'boldness'],
            ['Avarice',      'লোভ / কার্পণ্য',           '⭐ DU Likely',           'greed'],
            ['Aversion',     'ঘৃণা / অনীহা',             '⭐ Bank Likely',         'dislike'],
            ['Avid',         'আগ্রহী / উৎসুক',           '⭐ BCS Likely',         'eager'],
            ['Belie',        'মিথ্যা প্রমাণ করা',        '⭐ DU Likely',           'contradict'],
            ['Bellicose',    'যুদ্ধপ্রিয় / আক্রমণাত্মক','⭐ BCS Likely',        'aggressive'],
            ['Benighted',    'অজ্ঞ / অশিক্ষিত',         '⭐ Bank Likely',         'ignorant'],
            ['Berate',       'তিরস্কার করা',              '⭐ BCS Likely',         'scold'],
            ['Blithe',       'আনন্দিত / উদাসীন',        '⭐ DU Likely',           'carefree'],
            ['Boorish',      'অভদ্র / অশিষ্ট',          '⭐ Bank Likely',         'rude'],
            ['Bucolic',      'গ্রামীণ / পল্লী',          '⭐ BCS Likely',         'rural'],
            ['Burgeon',      'দ্রুত বৃদ্ধি পাওয়া',      '⭐ DU Likely',           'flourish'],
            ['Cacophony',    'কর্কশ শব্দ',               '⭐ BCS Likely',         'noise'],
            ['Capitulate',   'আত্মসমর্পণ করা',           '⭐ Bank Likely',         'surrender'],
            ['Castigate',    'শাস্তি দেওয়া / তিরস্কার', '⭐ BCS Likely',         'punish'],
            ['Catharsis',    'আবেগের মুক্তি',             '⭐ DU Likely',           'purging'],
            ['Caveat',       'সতর্কবার্তা',               '⭐ Bank Likely',         'warning'],
            ['Censorious',   'সমালোচনাপ্রবণ',            '⭐ BCS Likely',         'critical'],
            ['Chicanery',    'ধোঁকা / প্রতারণা',         '⭐ DU Likely',           'deception'],
            ['Circuitous',   'ঘুরিয়ে-পেঁচিয়ে',          '⭐ Bank Likely',         'indirect'],
            ['Clamor',       'হৈচৈ / হট্টগোল',          '⭐ BCS Likely',         'uproar'],
            ['Clandestine',  'গোপন',                     '⭐ DU Likely',           'secret'],
            ['Coalesce',     'একত্রিত হওয়া',             '⭐ Bank Likely',         'merge'],
            ['Coercion',     'জোরজবরদস্তি',              '⭐ BCS Likely',         'force'],
            ['Commensurate', 'সামঞ্জস্যপূর্ণ',           '⭐ DU Likely',           'proportional'],
            ['Compliant',    'বাধ্য / অনুগত',            '⭐ Bank Likely',         'obedient'],
            ['Conciliate',   'মিটমাট করা',                '⭐ BCS Likely',         'reconcile'],
            ['Condone',      'ক্ষমা করা / উপেক্ষা করা', '⭐ DU Likely',           'overlook'],
            ['Confluence',   'মিলনস্থল / সংগম',         '⭐ Bank Likely',         'meeting'],
            ['Convoluted',   'জটিল / প্যাঁচানো',        '⭐ BCS Likely',         'complex'],
            ['Copious',      'প্রচুর / অফুরন্ত',        '⭐ DU Likely',           'abundant'],
            ['Corroborate',  'প্রমাণ করা / সমর্থন করা', '⭐ Bank Likely',         'confirm'],
            ['Craven',       'কাপুরুষ',                  '⭐ BCS Likely',         'coward'],
            ['Culprit',      'দোষী / অপরাধী',           '⭐ DU Likely',           'offender'],
            ['Cursory',      'সংক্ষিপ্ত / অমনোযোগী',   '⭐ Bank Likely',         'hasty'],
            ['Debilitate',   'দুর্বল করা',               '⭐ BCS Likely',         'weaken'],
            ['Decorum',      'শালীনতা / শিষ্টাচার',    '⭐ DU Likely',           'propriety'],
            ['Deferential',  'বিনয়ী / সম্মানশীল',      '⭐ Bank Likely',         'respectful'],
            ['Deleterious',  'ক্ষতিকর',                  '⭐ BCS Likely',         'harmful'],
            ['Demeanor',     'আচরণ / ব্যবহার',          '⭐ DU Likely',           'behavior'],
            ['Denounce',     'নিন্দা করা',               '⭐ Bank Likely',         'condemn'],
            ['Desolate',     'নির্জন / বিধ্বস্ত',       '⭐ BCS Likely',         'barren'],
            ['Diatribe',     'তীব্র নিন্দাবাদ',          '⭐ DU Likely',           'tirade'],
            ['Dichotomy',    'দ্বিবিভাজন',               '⭐ Bank Likely',         'division'],
            ['Diffident',    'লাজুক / আত্মবিশ্বাসহীন', '⭐ BCS Likely',         'shy'],
            ['Digress',      'প্রসঙ্গ থেকে সরে যাওয়া', '⭐ DU Likely',           'deviate'],
            ['Discreet',     'বিচক্ষণ / সতর্ক',        '⭐ Bank Likely',         'careful'],
            ['Disparage',    'অবজ্ঞা করা',               '⭐ BCS Likely',         'belittle'],
            ['Dissemble',    'লুকানো / ভান করা',        '⭐ DU Likely',           'conceal'],
            ['Dogma',        'মতবাদ / বিশ্বাস',         '⭐ Bank Likely',         'doctrine'],
            ['Duplicity',    'দ্বিমুখিতা / প্রতারণা',  '⭐ BCS Likely',         'deceit'],
            ['Ebullient',    'উৎসাহী / আনন্দময়',       '⭐ DU Likely',           'enthusiastic'],
            ['Efficacious',  'কার্যকর',                   '⭐ Bank Likely',         'effective'],
            ['Egotistical',  'অহংকারী',                  '⭐ BCS Likely',         'arrogant'],
            ['Embellish',    'সজ্জিত করা / অলংকৃত করা','⭐ DU Likely',           'decorate'],
            ['Empirical',    'অভিজ্ঞতাভিত্তিক',         '⭐ Bank Likely',         'practical'],
            ['Encumber',     'বোঝা দেওয়া / বাধা দেওয়া','⭐ BCS Likely',         'burden'],
            ['Enervate',     'দুর্বল করা',               '⭐ DU Likely',           'weaken'],
            ['Enigma',       'রহস্য / ধাঁধা',           '⭐ Bank Likely',         'mystery'],
            ['Ephemeral',    'ক্ষণস্থায়ী',               '⭐ BCS Likely',         'transient'],
            ['Equanimity',   'মানসিক শান্তি',            '⭐ DU Likely',           'calmness'],
            ['Erudite',      'পণ্ডিত / জ্ঞানী',         '⭐ Bank Likely',         'learned'],
            ['Esoteric',     'গুপ্ত / রহস্যময়',        '⭐ BCS Likely',         'mysterious'],
            ['Expedient',    'সুবিধাজনক / কার্যকর',    '⭐ DU Likely',           'practical'],
            ['Explicit',     'স্পষ্ট / প্রত্যক্ষ',     '⭐ Bank Likely',         'clear'],
            ['Extraneous',   'অপ্রাসঙ্গিক',              '⭐ BCS Likely',         'irrelevant'],
            ['Facetious',    'রসিক / ঠাট্টাবাজ',       '⭐ DU Likely',           'joking'],
            ['Fatuous',      'নির্বোধ / বোকা',          '⭐ Bank Likely',         'foolish'],
            ['Felicitous',   'উপযুক্ত / সুখী',         '⭐ BCS Likely',         'appropriate'],
            ['Fervid',       'আবেগময় / উত্তেজিত',      '⭐ DU Likely',           'passionate'],
            ['Filibuster',   'বাধা দেওয়া (সংসদে)',     '⭐ Bank Likely',         'obstruct'],
            ['Foment',       'উস্কানি দেওয়া',           '⭐ BCS Likely',         'incite'],
            ['Forestall',    'আগেভাগে থামানো',           '⭐ DU Likely',           'prevent'],
            ['Fractious',    'খিটখিটে / বিরোধী',       '⭐ Bank Likely',         'irritable'],
            ['Garrulous',    'বাচাল',                    '⭐ BCS Likely',         'talkative'],
            ['Germane',      'প্রাসঙ্গিক',               '⭐ DU Likely',           'relevant'],
            ['Grandiloquent','আড়ম্বরপূর্ণ ভাষা',       '⭐ Bank Likely',         'pompous'],
            ['Gratuitous',   'অকারণ / বিনামূল্যে',     '⭐ BCS Likely',         'unnecessary'],
            ['Hackneyed',    'পুরনো / ক্লিশে',          '⭐ DU Likely',           'clichéd'],
            ['Hapless',      'দুর্ভাগ্যজনক',             '⭐ Bank Likely',         'unlucky'],
            ['Hegemony',     'আধিপত্য',                  '⭐ BCS Likely',         'dominance'],
            ['Hubris',       'অতিরিক্ত অহংকার',         '⭐ DU Likely',           'arrogance'],
            ['Iconoclast',   'প্রচলিত মত ভঙ্গকারী',    '⭐ Bank Likely',         'rebel'],
            ['Idiosyncratic','নিজস্ব বৈশিষ্ট্যপূর্ণ',  '⭐ BCS Likely',         'peculiar'],
            ['Ignominious',  'লজ্জাজনক',                 '⭐ DU Likely',           'shameful'],
            ['Imperious',    'কর্তৃত্বপরায়ণ / ঔদ্ধত্যপূর্ণ','⭐ Bank Likely',   'domineering'],
            ['Impertinent',  'অবিনয়ী / ধৃষ্ট',        '⭐ BCS Likely',         'rude'],
            ['Impugn',       'প্রশ্ন তোলা / আক্রমণ করা','⭐ DU Likely',          'challenge'],
            ['Inarticulate', 'অস্পষ্টভাষী',              '⭐ Bank Likely',         'unclear'],
            ['Inchoate',     'অপরিণত / অসম্পূর্ণ',     '⭐ BCS Likely',         'undeveloped'],
            ['Inimical',     'বৈরী / বিরুদ্ধ',          '⭐ DU Likely',           'hostile'],
            ['Iniquity',     'অন্যায় / পাপ',            '⭐ Bank Likely',         'wickedness'],
            ['Insipid',      'নিরস / স্বাদহীন',        '⭐ BCS Likely',         'bland'],
            ['Intrepid',     'নির্ভীক / সাহসী',        '⭐ DU Likely',           'fearless'],
            ['Inveterate',   'পুরনো অভ্যাসে আসক্ত',   '⭐ Bank Likely',         'habitual'],
            ['Irascible',    'রাগী / রগচটা',            '⭐ BCS Likely',         'irritable'],
            ['Laconic',      'সংক্ষিপ্তভাষী',           '⭐ DU Likely',           'brief'],
            ['Loquacious',   'বাচাল',                    '⭐ Bank Likely',         'talkative'],
            ['Lugubrious',   'শোকাকুল / বিষণ্ন',       '⭐ BCS Likely',         'mournful'],
            ['Machiavellian','ধূর্ত / কূটনীতিপরায়ণ',  '⭐ DU Likely',           'cunning'],
            ['Maladroit',    'অদক্ষ / আনাড়ি',         '⭐ Bank Likely',         'clumsy'],
            ['Mendacious',   'মিথ্যাবাদী',               '⭐ BCS Likely',         'dishonest'],
            ['Mercurial',    'অস্থির / পরিবর্তনশীল',   '⭐ DU Likely',           'volatile'],
            ['Meretricious', 'চটকদার কিন্তু মূল্যহীন', '⭐ Bank Likely',         'flashy'],
            ['Misanthrope',  'মানুষবিদ্বেষী',            '⭐ BCS Likely',         'cynic'],
            ['Misnomer',     'ভুল নামকরণ',               '⭐ DU Likely',           'wrong name'],
            ['Mollify',      'শান্ত করা / নরম করা',    '⭐ Bank Likely',         'pacify'],
            ['Myriad',       'অগণিত / অসংখ্য',         '⭐ BCS Likely',         'numerous'],
            ['Nascent',      'সদ্য উদ্ভূত / নতুন',     '⭐ DU Likely',           'emerging'],
            ['Nebulous',     'অস্পষ্ট / ধোঁয়াশাচ্ছন্ন','⭐ Bank Likely',         'vague'],
            ['Nonchalant',   'উদাসীন / নির্লিপ্ত',     '⭐ BCS Likely',         'indifferent'],
            ['Obfuscate',    'জটিল করা / অস্পষ্ট করা', '⭐ DU Likely',           'confuse'],
            ['Obtuse',       'বোকা / ভোঁতা',            '⭐ Bank Likely',         'dull'],
            ['Opaque',       'অস্বচ্ছ / দুর্বোধ্য',   '⭐ BCS Likely',         'unclear'],
            ['Ostentation',  'আড়ম্বর / দেখানো',        '⭐ DU Likely',           'showiness'],
            ['Panacea',      'সর্বরোগের ওষুধ',           '⭐ Bank Likely',         'cure-all'],
            ['Paucity',      'অভাব / স্বল্পতা',         '⭐ BCS Likely',         'scarcity'],
            ['Pedantic',     'পাণ্ডিত্যপূর্ণ / বেশি নিয়মনিষ্ঠ','⭐ DU Likely',  'fussy'],
            ['Perfunctory',  'তাড়াহুড়ো করা / উপরিভাগীয়','⭐ Bank Likely',      'superficial'],
            ['Pernicious',   'ক্ষতিকর / বিষাক্ত',     '⭐ BCS Likely',         'harmful'],
            ['Philanthropy', 'জনহিতকর কাজ',             '⭐ DU Likely',           'charity'],
            ['Placid',       'শান্ত / স্থির',           '⭐ Bank Likely',         'calm'],
            ['Polemical',    'বিতর্কমূলক',               '⭐ BCS Likely',         'controversial'],
            ['Portent',      'অশুভ লক্ষণ',               '⭐ DU Likely',           'omen'],
            ['Preclude',     'বাধা দেওয়া / রোধ করা',  '⭐ Bank Likely',         'prevent'],
            ['Proclivity',   'ঝোঁক / প্রবণতা',         '⭐ BCS Likely',         'tendency'],
            ['Profligate',   'অপব্যয়ী / উচ্ছৃঙ্খল',   '⭐ DU Likely',           'extravagant'],
            ['Propitious',   'অনুকূল / শুভ',            '⭐ Bank Likely',         'favorable'],
            ['Prosaic',      'সাধারণ / নিরস',           '⭐ BCS Likely',         'dull'],
            ['Provocative',  'উত্তেজনামূলক',             '⭐ DU Likely',           'stimulating'],
            ['Punctilious',  'নিয়মনিষ্ঠ',               '⭐ Bank Likely',         'meticulous'],
            ['Quixotic',     'অবাস্তব / স্বপ্নবিলাসী', '⭐ BCS Likely',         'idealistic'],
            ['Recalcitrant', 'অবাধ্য / জেদি',           '⭐ DU Likely',           'stubborn'],
            ['Recant',       'প্রত্যাহার করা',           '⭐ Bank Likely',         'retract'],
            ['Reclusive',    'একাকী / বিচ্ছিন্ন',       '⭐ BCS Likely',         'isolated'],
            ['Repudiate',    'প্রত্যাখ্যান করা',        '⭐ DU Likely',           'reject'],
            ['Rescind',      'বাতিল করা',                '⭐ Bank Likely',         'cancel'],
            ['Restive',      'অস্থির / অধৈর্য',        '⭐ BCS Likely',         'impatient'],
            ['Sacrosanct',   'অলঙ্ঘনীয় / পবিত্র',     '⭐ DU Likely',           'sacred'],
            ['Sanguine',     'আশাবাদী',                  '⭐ Bank Likely',         'optimistic'],
            ['Salient',      'প্রধান / উল্লেখযোগ্য',   '⭐ BCS Likely',         'prominent'],
            ['Sophistry',    'ভ্রান্ত যুক্তি',           '⭐ DU Likely',           'fallacy'],
            ['Soporific',    'ঘুমপাড়ানি',               '⭐ Bank Likely',         'sleep-inducing'],
            ['Specious',     'দেখতে সত্য কিন্তু মিথ্যা','⭐ BCS Likely',         'misleading'],
            ['Sporadic',     'বিচ্ছিন্ন / অনিয়মিত',   '⭐ DU Likely',           'irregular'],
            ['Stringent',    'কঠোর',                     '⭐ Bank Likely',         'strict'],
            ['Subversive',   'বিদ্রোহমূলক',              '⭐ BCS Likely',         'rebellious'],
            ['Sycophancy',   'তোষামোদ',                  '⭐ DU Likely',           'flattery'],
            ['Tacit',        'নীরব / অব্যক্ত',          '⭐ Bank Likely',         'implied'],
            ['Terse',        'সংক্ষিপ্ত / রুক্ষ',      '⭐ BCS Likely',         'brief'],
            ['Tirade',       'তীব্র নিন্দাবক্তৃতা',     '⭐ DU Likely',           'outburst'],
            ['Torpor',       'অলসতা / নিষ্ক্রিয়তা',   '⭐ Bank Likely',         'lethargy'],
            ['Truculent',    'আক্রমণাত্মক',              '⭐ BCS Likely',         'aggressive'],
            ['Ubiquitous',   'সর্বত্র বিদ্যমান',        '⭐ DU Likely',           'everywhere'],
            ['Umbrage',      'অসন্তোষ / বিরক্তি',       '⭐ Bank Likely',         'offense'],
            ['Unequivocal',  'স্পষ্ট / নিঃসন্দেহ',    '⭐ BCS Likely',         'clear'],
            ['Vacillate',    'দোদুল্যমান হওয়া',         '⭐ DU Likely',           'waver'],
            ['Vapid',        'নিরস / অর্থহীন',         '⭐ Bank Likely',         'dull'],
            ['Venal',        'ঘুষখোর / দুর্নীতিপরায়ণ','⭐ BCS Likely',          'corrupt'],
            ['Venial',       'ক্ষমাযোগ্য',              '⭐ DU Likely',           'forgivable'],
            ['Vexatious',    'বিরক্তিকর',               '⭐ Bank Likely',         'annoying'],
            ['Vicarious',    'পরোক্ষভাবে অনুভব করা',    '⭐ BCS Likely',         'indirect'],
            ['Vilify',       'নিন্দা করা',               '⭐ DU Likely',           'slander'],
            ['Vindicate',    'নির্দোষ প্রমাণ করা',      '⭐ Bank Likely',         'justify'],
            ['Virulent',     'বিষাক্ত / তীব্র',        '⭐ BCS Likely',         'toxic'],
            ['Vitriolic',    'কটু / তীব্র সমালোচনা',   '⭐ DU Likely',           'harsh'],
            ['Vociferous',   'উচ্চস্বরে প্রতিবাদী',    '⭐ Bank Likely',         'loud'],
            ['Wanton',       'অর্থহীন / উচ্ছৃঙ্খল',   '⭐ BCS Likely',         'reckless'],
            ['Wistful',      'আকাঙ্ক্ষাময় / স্মৃতিমগ্ন','⭐ DU Likely',         'longing'],
            ['Xenophobia',   'বিদেশিদের ভয় / বিদ্বেষ','⭐ Bank Likely',         'prejudice'],
            ['Zealotry',     'অন্ধ উৎসাহ',              '⭐ BCS Likely',         'fanaticism'],
        ];

        // ── Insert Lesson 1 words ─────────────────────────────────
        $rows1 = [];
        foreach ($lesson1Words as [$word, $meaning, $synonyms, $antonyms]) {
            $rows1[] = [
                'word'       => $word,
                'meaning'    => $meaning,
                'synonyms'   => $synonyms,
                'antonyms'   => $antonyms,
                'lesson_id'  => $lesson1Id,
                'status'     => true,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }
        DB::table('words')->insert($rows1);

        // ── Insert Lesson 2 words ─────────────────────────────────
        $rows2 = [];
        foreach ($lesson2Words as [$word, $meaning, $synonyms, $antonyms]) {
            $rows2[] = [
                'word'       => $word,
                'meaning'    => $meaning,
                'synonyms'   => $synonyms,
                'antonyms'   => $antonyms,
                'lesson_id'  => $lesson2Id,
                'status'     => true,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }
        DB::table('words')->insert($rows2);
    }

    public function down(): void
    {
        $lessons = DB::table('lessons')->where('type', 'exam_vocab_appeared')
            ->orWhere('type', 'exam_vocab_upcoming')->get();

        foreach ($lessons as $lesson) {
            DB::table('words')->where('lesson_id', $lesson->id)->delete();
            DB::table('chapters')->where('id', $lesson->chapter_id)->delete();
        }

        DB::table('lessons')->whereIn('type', ['exam_vocab_appeared', 'exam_vocab_upcoming'])->delete();
    }
};
