<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Batch 2 of Medical vocabulary for lesson_id=6. Adds 150 more
     * words on top of the 89 original + 149 from batch 1.
     */
    public function up(): void
    {
        $words = [
            ['Abscess', 'ফোড়া', 'boil, swelling', 'none'],
            ['Acne', 'ব্রণ', 'pimples', 'clear skin'],
            ['Adrenaline', 'অ্যাড্রেনালিন', 'epinephrine', 'none'],
            ['Airborne', 'বায়ুবাহিত', 'aerial, wind-carried', 'waterborne'],
            ['Ambulatory', 'চলাফেরায় সক্ষম', 'mobile, walking', 'bedridden'],
            ['Amnesia', 'স্মৃতিভ্রংশ', 'memory loss', 'recall'],
            ['Analgesic', 'ব্যথানাশক', 'painkiller', 'none'],
            ['Angina', 'বুকে ব্যথা', 'chest pain', 'none'],
            ['Antidote', 'প্রতিষেধক', 'antitoxin, remedy', 'poison'],
            ['Antigen', 'অ্যান্টিজেন', 'foreign substance', 'antibody'],
            ['Aorta', 'মহাধমনী', 'main artery', 'none'],
            ['Apnea', 'শ্বাসরোধ', 'breathing pause', 'none'],
            ['Appendix', 'অ্যাপেন্ডিক্স', 'vestigial organ', 'none'],
            ['Arrhythmia', 'অনিয়মিত হৃদস্পন্দন', 'irregular heartbeat', 'normal rhythm'],
            ['Aspirate', 'টেনে নেওয়া, উচ্ছ্বসিত করা', 'suction, inhale', 'none'],
            ['Asymptomatic', 'লক্ষণহীন', 'symptomless', 'symptomatic'],
            ['Ataxia', 'সমন্বয়হীনতা', 'lack of coordination', 'coordination'],
            ['Atrophy', 'ক্ষয়', 'wasting, shrinkage', 'growth'],
            ['Auscultation', 'স্টেথোস্কোপ দ্বারা পরীক্ষা', 'listening exam', 'none'],
            ['Bacterial', 'ব্যাকটেরিয়াজনিত', 'microbial', 'viral'],
            ['Bile', 'পিত্ত', 'digestive fluid', 'none'],
            ['Biohazard', 'জৈব বিপদ', 'biological hazard', 'safe material'],
            ['Blood pressure', 'রক্তচাপ', 'BP', 'none'],
            ['Bowel', 'অন্ত্র', 'intestine', 'none'],
            ['Brain-dead', 'মস্তিষ্ক-মৃত', 'cerebral death', 'alive'],
            ['Bronchitis', 'ব্রঙ্কাইটিস', 'airway inflammation', 'none'],
            ['Burn', 'পোড়া', 'scald', 'heal'],
            ['Capillary', 'কৈশিক নালী', 'tiny blood vessel', 'none'],
            ['Carcinogen', 'ক্যান্সার সৃষ্টিকারী পদার্থ', 'cancer-causing agent', 'none'],
            ['Cataract', 'ছানি', 'eye clouding', 'none'],
            ['Catheter', 'ক্যাথেটার', 'tube, drain', 'none'],
            ['Cerebrum', 'মস্তিষ্কের প্রধান অংশ', 'forebrain', 'none'],
            ['Chemotherapy', 'কেমোথেরাপি', 'cancer treatment', 'none'],
            ['Chickenpox', 'জলবসন্ত', 'varicella', 'none'],
            ['Cholesterol', 'কোলেস্টেরল', 'blood fat', 'none'],
            ['Cirrhosis', 'সিরোসিস (যকৃতের রোগ)', 'liver scarring', 'none'],
            ['Cleft', 'ফাটল', 'split, gap', 'none'],
            ['Clinical', 'ক্লিনিক্যাল', 'medical, diagnostic', 'none'],
            ['Coagulation', 'রক্ত জমাট বাঁধা প্রক্রিয়া', 'clotting', 'none'],
            ['Colic', 'উদরশূল', 'abdominal pain', 'none'],
            ['Colon', 'কোলন, বৃহদন্ত্র', 'large intestine', 'none'],
            ['Coma', 'কোমা', 'unconsciousness', 'consciousness'],
            ['Compress', 'সেঁক', 'pad, dressing', 'none'],
            ['Compulsive', 'বাধ্যতামূলক আচরণজনিত', 'obsessive', 'none'],
            ['Concussion', 'মস্তিষ্কে আঘাত', 'brain injury', 'none'],
            ['Congestion', 'সংকুলান, বন্ধভাব', 'blockage, clogging', 'clearance'],
            ['Conjunctivitis', 'চোখ ওঠা', 'pink eye', 'none'],
            ['Constipation', 'কোষ্ঠকাঠিন্য', 'irregular bowel', 'diarrhea'],
            ['Consultation', 'পরামর্শ', 'appointment, checkup', 'none'],
            ['Contaminate', 'দূষিত করা', 'pollute, infect', 'purify'],
            ['Contract', 'সংক্রমিত হওয়া', 'catch, acquire', 'recover'],
            ['Convulsion', 'খিঁচুনি', 'fit, spasm', 'none'],
            ['Cough', 'কাশি', 'hack', 'none'],
            ['Cramp', 'পেশির খিঁচুনি', 'spasm', 'relaxation'],
            ['Cyst', 'সিস্ট', 'sac, growth', 'none'],
            ['Debilitate', 'দুর্বল করা', 'weaken, incapacitate', 'strengthen'],
            ['Decongestant', 'কনজেশন দূরকারী ঔষধ', 'nasal reliever', 'none'],
            ['Defibrillator', 'ডিফাইব্রিলেটর', 'heart shock device', 'none'],
            ['Degenerate', 'অবক্ষয় হওয়া', 'deteriorate, decline', 'improve'],
            ['Dehydration', 'পানিশূন্যতা', 'fluid loss', 'hydration'],
            ['Delirium', 'প্রলাপ', 'confusion, disorientation', 'clarity'],
            ['Dermatitis', 'ত্বকের প্রদাহ', 'skin inflammation', 'none'],
            ['Dermatology', 'চর্মরোগবিদ্যা', 'skin medicine', 'none'],
            ['Detox', 'বিষমুক্তকরণ', 'detoxification', 'none'],
            ['Dialysis', 'ডায়ালাইসিস', 'kidney filtration', 'none'],
            ['Dilate', 'প্রসারিত করা', 'widen, expand', 'constrict'],
            ['Discomfort', 'অস্বস্তি', 'unease, pain', 'comfort'],
            ['Dislocate', 'স্থানচ্যুত করা', 'displace', 'relocate'],
            ['Dose', 'মাত্রা', 'quantity, amount', 'none'],
            ['Drainage', 'নিষ্কাশন', 'draining', 'none'],
            ['Droplet', 'ফোঁটা', 'drop', 'none'],
            ['Duct', 'নালী', 'channel, tube', 'none'],
            ['Duodenum', 'ডিওডেনাম', 'first part of intestine', 'none'],
            ['Eczema', 'একজিমা', 'skin rash condition', 'none'],
            ['Edema', 'শোথ', 'swelling, fluid retention', 'none'],
            ['Elevate', 'উঁচু করা', 'raise, lift', 'lower'],
            ['Embolism', 'এমবোলিজম', 'blood vessel blockage', 'none'],
            ['Endoscope', 'এন্ডোস্কোপ', 'internal viewing tool', 'none'],
            ['Epidermis', 'বহিস্ত্বক', 'outer skin layer', 'dermis'],
            ['Erosion', 'ক্ষয়', 'wearing away', 'buildup'],
            ['Excrete', 'রেচন করা', 'expel, eliminate', 'absorb'],
            ['Exhaustion', 'সম্পূর্ণ ক্লান্তি', 'extreme fatigue', 'energy'],
            ['External', 'বাহ্যিক', 'outer, outward', 'internal'],
            ['Extremity', 'অঙ্গপ্রত্যঙ্গ', 'limb', 'none'],
            ['Fainting', 'অজ্ঞান হওয়া', 'syncope, blackout', 'consciousness'],
            ['Fertility', 'উর্বরতা', 'reproductive capacity', 'infertility'],
            ['Fetal', 'ভ্রূণসংক্রান্ত', 'relating to fetus', 'none'],
            ['Fistula', 'ফিস্টুলা', 'abnormal passage', 'none'],
            ['Flatulence', 'পেট ফাঁপা', 'gas, bloating', 'none'],
            ['Follicle', 'ফলিকল', 'small sac (hair or egg)', 'none'],
            ['Forceps', 'সাঁড়াশি', 'surgical tongs', 'none'],
            ['Fungal', 'ছত্রাকজনিত', 'fungus-related', 'none'],
            ['Gallbladder', 'পিত্তথলি', 'bile sac', 'none'],
            ['Gastroenterology', 'পরিপাকতন্ত্র বিদ্যা', 'digestive medicine', 'none'],
            ['Gauze', 'গজ কাপড়', 'dressing material', 'none'],
            ['Genitals', 'যৌনাঙ্গ', 'reproductive organs', 'none'],
            ['Geriatric', 'বার্ধক্যজনিত', 'elderly-related', 'pediatric'],
            ['Gestation', 'গর্ভাবস্থা', 'pregnancy period', 'none'],
            ['Graft', 'প্রতিস্থাপিত টিস্যু', 'transplant tissue', 'none'],
            ['Groin', 'কুঁচকি', 'inguinal area', 'none'],
            ['Gynecology', 'স্ত্রীরোগবিদ্যা', "women's medicine", 'none'],
            ['Hematology', 'রক্তরোগবিদ্যা', 'blood study', 'none'],
            ['Hemoglobin', 'হিমোগ্লোবিন', 'oxygen-carrying protein', 'none'],
            ['Hepatic', 'যকৃৎ সংক্রান্ত', 'liver-related', 'none'],
            ['Hepatitis', 'হেপাটাইটিস', 'liver inflammation', 'none'],
            ['Hernia', 'হার্নিয়া', 'organ protrusion', 'none'],
            ['Histology', 'কলাবিদ্যা', 'tissue study', 'none'],
            ['Hormonal', 'হরমোনজনিত', 'endocrine-related', 'none'],
            ['Hospice', 'উপশমকারী সেবাকেন্দ্র', 'palliative care center', 'none'],
            ['Hypertension', 'উচ্চ রক্তচাপ', 'high blood pressure', 'hypotension'],
            ['Hypotension', 'নিম্ন রক্তচাপ', 'low blood pressure', 'hypertension'],
            ['Hypothermia', 'অতিরিক্ত শীতলতা', 'low body temperature', 'hyperthermia'],
            ['Hypoxia', 'অক্সিজেন স্বল্পতা', 'oxygen deficiency', 'none'],
            ['Immobilize', 'স্থির করা', 'fix, restrain', 'mobilize'],
            ['Incubation', 'ইনকিউবেশন', 'development period', 'none'],
            ['Infertility', 'বন্ধ্যাত্ব', 'inability to conceive', 'fertility'],
            ['Inhale', 'শ্বাস নেওয়া', 'breathe in', 'exhale'],
            ['Inpatient', 'ভর্তি রোগী', 'admitted patient', 'outpatient'],
            ['Insulin', 'ইনসুলিন', 'blood sugar hormone', 'none'],
            ['Intern', 'ইন্টার্ন', 'trainee doctor', 'none'],
            ['Intestinal', 'অন্ত্রসংক্রান্ত', 'bowel-related', 'none'],
            ['Intramuscular', 'পেশির ভেতরে', 'within muscle', 'none'],
            ['Involuntary', 'অনিচ্ছাকৃত', 'reflexive, automatic', 'voluntary'],
            ['Irritable', 'খিটখিটে, উত্তেজিত', 'sensitive, easily annoyed', 'calm'],
            ['Lactation', 'স্তন্যদান', 'breastfeeding', 'none'],
            ['Laparoscopy', 'ল্যাপারোস্কোপি', 'keyhole surgery', 'none'],
            ['Larynx', 'স্বরযন্ত্র', 'voice box', 'none'],
            ['Lateral', 'পার্শ্বীয়', 'sideways', 'central'],
            ['Lethargy', 'অলসতা', 'sluggishness, tiredness', 'energy'],
            ['Leukemia', 'লিউকেমিয়া', 'blood cancer', 'none'],
            ['Lifespan', 'আয়ুষ্কাল', 'life expectancy', 'none'],
            ['Ligature', 'বাঁধন', 'tie, binding', 'none'],
            ['Lobe', 'খণ্ড, লোব', 'section of organ', 'none'],
            ['Lumbar', 'কটিদেশীয়', 'lower back related', 'none'],
            ['Lymph', 'লসিকা', 'lymphatic fluid', 'none'],
            ['Malaria', 'ম্যালেরিয়া', 'mosquito-borne fever', 'none'],
            ['Malnutrition', 'অপুষ্টি', 'undernourishment', 'nourishment'],
            ['Mammogram', 'ম্যামোগ্রাম', 'breast X-ray', 'none'],
            ['Mandible', 'নিচের চোয়াল', 'lower jaw', 'maxilla'],
            ['Marrow', 'অস্থিমজ্জা', 'bone marrow', 'none'],
            ['Maternal', 'মাতৃসংক্রান্ত', 'motherly', 'paternal'],
            ['Maxilla', 'উপরের চোয়াল', 'upper jaw', 'mandible'],
            ['Menstruation', 'ঋতুস্রাব', 'period, menses', 'none'],
            ['Metastasis', 'ক্যান্সার ছড়িয়ে পড়া', 'cancer spread', 'none'],
            ['Microbe', 'জীবাণু', 'microorganism', 'none'],
            ['Midwife', 'ধাত্রী', 'birth attendant', 'none'],
            ['Miscarriage', 'গর্ভপাত', 'pregnancy loss', 'delivery'],
            ['Mucus', 'শ্লেষ্মা', 'phlegm', 'none'],
            ['Mute', 'বাকশক্তিহীন', 'speechless, silent', 'vocal'],
            ['Nasal', 'নাসিকাসংক্রান্ত', 'nose-related', 'none'],
        ];

        $now = now();
        $rows = array_map(function ($w) use ($now) {
            return [
                'word' => $w[0],
                'meaning' => $w[1],
                'synonyms' => $w[2],
                'antonyms' => $w[3],
                'lesson_id' => 6,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $words);

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('words')->insert($chunk);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $words = [
            'Abscess','Acne','Adrenaline','Airborne','Ambulatory','Amnesia','Analgesic','Angina','Antidote','Antigen',
            'Aorta','Apnea','Appendix','Arrhythmia','Aspirate','Asymptomatic','Ataxia','Atrophy','Auscultation','Bacterial',
            'Bile','Biohazard','Blood pressure','Bowel','Brain-dead','Bronchitis','Burn','Capillary','Carcinogen','Cataract',
            'Catheter','Cerebrum','Chemotherapy','Chickenpox','Cholesterol','Cirrhosis','Cleft','Clinical','Coagulation','Colic',
            'Colon','Coma','Compress','Compulsive','Concussion','Congestion','Conjunctivitis','Constipation','Consultation','Contaminate',
            'Contract','Convulsion','Cough','Cramp','Cyst','Debilitate','Decongestant','Defibrillator','Degenerate','Dehydration',
            'Delirium','Dermatitis','Dermatology','Detox','Dialysis','Dilate','Discomfort','Dislocate','Dose','Drainage',
            'Droplet','Duct','Duodenum','Eczema','Edema','Elevate','Embolism','Endoscope','Epidermis','Erosion',
            'Excrete','Exhaustion','External','Extremity','Fainting','Fertility','Fetal','Fistula','Flatulence','Follicle',
            'Forceps','Fungal','Gallbladder','Gastroenterology','Gauze','Genitals','Geriatric','Gestation','Graft','Groin',
            'Gynecology','Hematology','Hemoglobin','Hepatic','Hepatitis','Hernia','Histology','Hormonal','Hospice','Hypertension',
            'Hypotension','Hypothermia','Hypoxia','Immobilize','Incubation','Infertility','Inhale','Inpatient','Insulin','Intern',
            'Intestinal','Intramuscular','Involuntary','Irritable','Lactation','Laparoscopy','Larynx','Lateral','Lethargy','Leukemia',
            'Lifespan','Ligature','Lobe','Lumbar','Lymph','Malaria','Malnutrition','Mammogram','Mandible','Marrow',
            'Maternal','Maxilla','Menstruation','Metastasis','Microbe','Midwife','Miscarriage','Mucus','Mute','Nasal',
        ];
        DB::table('words')->where('lesson_id', 6)->whereIn('word', $words)->delete();
    }
};
