<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Batch 3 of IELTS vocabulary for lesson_id=4. Adds ~185 more words
     * (313 so far + this batch), pushing close to the 500 target.
     */
    public function up(): void
    {
        $words = [
            ['Abandon', 'পরিত্যাগ করা', 'give up, desert', 'retain, keep'],
            ['Abolish', 'বিলুপ্ত করা', 'eliminate, eradicate', 'establish, institute'],
            ['Absorb', 'শোষণ করা', 'soak up, assimilate', 'emit, release'],
            ['Abstract', 'বিমূর্ত', 'theoretical, conceptual', 'concrete, tangible'],
            ['Accessible', 'সহজলভ্য', 'available, reachable', 'inaccessible, unreachable'],
            ['Accommodate', 'স্থান সংকুলান করা', 'house, adapt', 'exclude, reject'],
            ['Accompany', 'সঙ্গী হওয়া', 'escort, join', 'abandon, leave'],
            ['Accomplish', 'সম্পন্ন করা', 'achieve, complete', 'fail, abandon'],
            ['Accordingly', 'তদনুসারে', 'consequently, thus', 'regardless'],
            ['Account', 'হিসাব, বর্ণনা', 'explanation, record', 'silence'],
            ['Accustomed', 'অভ্যস্ত', 'used to, familiar', 'unaccustomed, unfamiliar'],
            ['Achieve', 'অর্জন করা', 'accomplish, attain', 'fail, lose'],
            ['Acute', 'তীব্র', 'severe, sharp', 'mild, chronic'],
            ['Adjust', 'সামঞ্জস্য করা', 'adapt, modify', 'disrupt, unsettle'],
            ['Advent', 'আগমন', 'arrival, emergence', 'departure'],
            ['Adversity', 'প্রতিকূলতা', 'hardship, misfortune', 'prosperity, fortune'],
            ['Affect', 'প্রভাবিত করা', 'influence, impact', 'ignore'],
            ['Affluent', 'সম্পদশালী', 'wealthy, prosperous', 'poor, impoverished'],
            ['Aggravate', 'আরও খারাপ করা', 'worsen, intensify', 'alleviate, improve'],
            ['Agenda', 'কার্যসূচি', 'schedule, plan', 'none'],
            ['Aggression', 'আক্রমণাত্মকতা', 'hostility, attack', 'peace, passivity'],
            ['Aid', 'সাহায্য', 'assistance, support', 'hindrance'],
            ['Alarming', 'উদ্বেগজনক', 'worrying, disturbing', 'reassuring, comforting'],
            ['Alienate', 'বিচ্ছিন্ন করা', 'estrange, isolate', 'unite, befriend'],
            ['Align', 'সারিবদ্ধ করা', 'line up, coordinate', 'misalign'],
            ['Allege', 'অভিযোগ করা', 'claim, assert', 'deny, refute'],
            ['Alleviate', 'প্রশমিত করা', 'ease, relieve', 'aggravate, worsen'],
            ['Alliance', 'মৈত্রী', 'partnership, coalition', 'rivalry, conflict'],
            ['Altruistic', 'পরার্থপর', 'selfless, generous', 'selfish, egotistic'],
            ['Amend', 'সংশোধন করা', 'revise, modify', 'worsen'],
            ['Amenity', 'সুযোগসুবিধা', 'facility, comfort', 'inconvenience'],
            ['Analyze', 'বিশ্লেষণ করা', 'examine, evaluate', 'ignore, overlook'],
            ['Ancestor', 'পূর্বপুরুষ', 'forebear, predecessor', 'descendant'],
            ['Annual', 'বার্ষিক', 'yearly', 'none'],
            ['Anonymous', 'বেনামী', 'unnamed, unidentified', 'identified, named'],
            ['Antagonize', 'শত্রুতা সৃষ্টি করা', 'provoke, alienate', 'appease, conciliate'],
            ['Apparatus', 'যন্ত্রপাতি', 'equipment, device', 'none'],
            ['Appealing', 'আকর্ষণীয়', 'attractive, inviting', 'unappealing, repulsive'],
            ['Applicable', 'প্রযোজ্য', 'relevant, suitable', 'inapplicable, irrelevant'],
            ['Appoint', 'নিয়োগ করা', 'assign, designate', 'dismiss, remove'],
            ['Appraisal', 'মূল্যায়ন', 'assessment, evaluation', 'neglect'],
            ['Appropriate', 'উপযুক্ত', 'suitable, fitting', 'inappropriate, unsuitable'],
            ['Approve', 'অনুমোদন করা', 'endorse, sanction', 'reject, disapprove'],
            ['Aptitude', 'সহজাত দক্ষতা', 'talent, capability', 'inability'],
            ['Arise', 'উদ্ভূত হওয়া', 'emerge, occur', 'disappear, vanish'],
            ['Array', 'সমাবেশ, বিন্যাস', 'collection, arrangement', 'disorder'],
            ['Ascertain', 'নিশ্চিত হওয়া', 'determine, verify', 'guess'],
            ['Aspect', 'দিক', 'facet, feature', 'whole'],
            ['Assemble', 'সমবেত করা', 'gather, compile', 'disperse, scatter'],
            ['Assessment', 'মূল্যায়ন', 'evaluation, appraisal', 'neglect'],
            ['Asset', 'সম্পদ', 'resource, possession', 'liability'],
            ['Assign', 'নিয়োগ দেওয়া', 'allocate, designate', 'withdraw'],
            ['Assimilate', 'আত্মীকরণ করা', 'absorb, integrate', 'exclude, segregate'],
            ['Assortment', 'সংগ্রহ', 'variety, mixture', 'uniformity'],
            ['Astonish', 'বিস্মিত করা', 'amaze, surprise', 'bore'],
            ['Attentive', 'মনোযোগী', 'alert, observant', 'inattentive, distracted'],
            ['Augment', 'বৃদ্ধি করা', 'increase, enhance', 'reduce, diminish'],
            ['Authority', 'কর্তৃত্ব', 'power, control', 'subordination'],
            ['Automate', 'স্বয়ংক্রিয় করা', 'mechanize, computerize', 'manualize'],
            ['Avert', 'প্রতিরোধ করা', 'prevent, avoid', 'cause, invite'],
            ['Awareness', 'সচেতনতা', 'consciousness, knowledge', 'ignorance'],
            ['Awesome', 'বিস্ময়কর', 'amazing, impressive', 'unimpressive'],
            ['Backdrop', 'পটভূমি', 'background, setting', 'foreground'],
            ['Backfire', 'উল্টো ফল দেওয়া', 'rebound, boomerang', 'succeed'],
            ['Barrier', 'বাধা', 'obstacle, obstruction', 'gateway, opening'],
            ['Basis', 'ভিত্তি', 'foundation, base', 'none'],
            ['Behalf', 'পক্ষ', 'interest, benefit', 'none'],
            ['Benchmark', 'মানদণ্ড', 'standard, criterion', 'none'],
            ['Bestow', 'প্রদান করা', 'grant, confer', 'withhold, deny'],
            ['Bilateral', 'দ্বিপাক্ষিক', 'two-sided, mutual', 'unilateral'],
            ['Bind', 'আবদ্ধ করা', 'tie, connect', 'release, free'],
            ['Blatant', 'সুস্পষ্ট, প্রকট', 'obvious, flagrant', 'subtle, hidden'],
            ['Bleak', 'বিষণ্ণ, অন্ধকারময়', 'gloomy, grim', 'bright, hopeful'],
            ['Blend', 'মিশ্রিত করা', 'mix, combine', 'separate'],
            ['Blur', 'অস্পষ্ট করা', 'obscure, smudge', 'clarify, sharpen'],
            ['Boast', 'গর্ব করা', 'brag, flaunt', 'humble, understate'],
            ['Bolster', 'শক্তিশালী করা', 'reinforce, support', 'weaken, undermine'],
            ['Bond', 'বন্ধন', 'link, tie', 'separation'],
            ['Boundary', 'সীমানা', 'border, limit', 'center'],
            ['Breach', 'লঙ্ঘন', 'violation, infringement', 'compliance'],
            ['Breakthrough', 'যুগান্তকারী অগ্রগতি', 'advance, discovery', 'setback'],
            ['Breed', 'প্রজনন করা, জাত', 'reproduce, generate', 'eliminate'],
            ['Brief', 'সংক্ষিপ্ত', 'short, concise', 'lengthy, extended'],
            ['Broaden', 'প্রসারিত করা', 'widen, expand', 'narrow, restrict'],
            ['Budget', 'বাজেট', 'allocation, plan', 'none'],
            ['Burden', 'বোঝা', 'load, weight', 'relief'],
            ['Bypass', 'এড়িয়ে যাওয়া', 'avoid, circumvent', 'confront'],
            ['Campaign', 'প্রচারণা', 'crusade, drive', 'none'],
            ['Candid', 'অকপট', 'honest, frank', 'dishonest, evasive'],
            ['Capable', 'সক্ষম', 'competent, able', 'incapable, unable'],
            ['Capitalize', 'সুযোগ নেওয়া', 'exploit, utilize', 'waste, ignore'],
            ['Captivate', 'মুগ্ধ করা', 'fascinate, enchant', 'bore, repel'],
            ['Cater', 'পরিবেশন করা, সরবরাহ করা', 'provide, serve', 'deprive'],
            ['Ceaseless', 'অবিরাম', 'constant, endless', 'intermittent, temporary'],
            ['Certainty', 'নিশ্চয়তা', 'assurance, confidence', 'doubt, uncertainty'],
            ['Chronic', 'দীর্ঘস্থায়ী', 'persistent, long-lasting', 'acute, temporary'],
            ['Circulate', 'প্রচার করা', 'spread, distribute', 'withhold, contain'],
            ['Clarify', 'স্পষ্ট করা', 'explain, elucidate', 'confuse, obscure'],
            ['Clash', 'সংঘর্ষ', 'conflict, collision', 'harmony, agreement'],
            ['Classify', 'শ্রেণীবদ্ধ করা', 'categorize, sort', 'mix, jumble'],
            ['Clientele', 'গ্রাহকবৃন্দ', 'customers, patrons', 'none'],
            ['Clinical', 'চিকিৎসাগত, নির্মোহ', 'medical, detached', 'emotional'],
            ['Clutter', 'বিশৃঙ্খলা', 'mess, disorder', 'order, tidiness'],
            ['Coincide', 'একই সাথে ঘটা', 'correspond, align', 'differ, diverge'],
            ['Collapse', 'ভেঙে পড়া', 'fall apart, crumble', 'stand, endure'],
            ['Collide', 'সংঘর্ষ হওয়া', 'crash, clash', 'avoid'],
            ['Colossal', 'প্রকান্ড', 'huge, gigantic', 'tiny, minuscule'],
            ['Combat', 'মোকাবিলা করা', 'fight, battle', 'surrender, yield'],
            ['Commodity', 'পণ্য', 'product, goods', 'none'],
            ['Commonplace', 'সাধারণ', 'ordinary, usual', 'rare, unusual'],
            ['Compel', 'বাধ্য করা', 'force, oblige', 'dissuade'],
            ['Compile', 'সংকলন করা', 'gather, assemble', 'scatter'],
            ['Complement', 'পরিপূরক', 'supplement, enhance', 'clash, contrast'],
            ['Complexity', 'জটিলতা', 'intricacy, complication', 'simplicity'],
            ['Compliance', 'সম্মতি, আনুগত্য', 'obedience, conformity', 'defiance, resistance'],
            ['Component', 'উপাদান', 'part, element', 'whole'],
            ['Compromise', 'আপস', 'settlement, concession', 'conflict, dispute'],
            ['Conceal', 'গোপন করা', 'hide, disguise', 'reveal, expose'],
            ['Concede', 'স্বীকার করা', 'admit, yield', 'deny, refuse'],
            ['Conception', 'ধারণা', 'idea, notion', 'none'],
            ['Concrete', 'দৃঢ়, বাস্তব', 'solid, tangible', 'abstract, vague'],
            ['Condemn', 'নিন্দা করা', 'denounce, criticize', 'praise, endorse'],
            ['Confidential', 'গোপনীয়', 'private, secret', 'public, open'],
            ['Conflict', 'দ্বন্দ্ব', 'clash, dispute', 'harmony, agreement'],
            ['Congestion', 'যানজট, ভিড়', 'overcrowding, blockage', 'clearance'],
            ['Conjecture', 'অনুমান', 'guess, speculation', 'fact'],
            ['Connotation', 'অন্তর্নিহিত অর্থ', 'implication, undertone', 'denotation'],
            ['Conscientious', 'বিবেকবান, নিষ্ঠাবান', 'diligent, meticulous', 'careless, negligent'],
            ['Consequence', 'পরিণতি', 'result, outcome', 'cause'],
            ['Considerate', 'বিবেচক', 'thoughtful, caring', 'inconsiderate, selfish'],
            ['Console', 'সান্ত্বনা দেওয়া', 'comfort, soothe', 'upset, distress'],
            ['Conspicuous', 'দৃষ্টি আকর্ষণকারী', 'noticeable, prominent', 'inconspicuous, hidden'],
            ['Constituent', 'উপাদান, নির্বাচক', 'component, element', 'whole'],
            ['Contaminate', 'দূষিত করা', 'pollute, taint', 'purify, cleanse'],
            ['Contemplate', 'গভীরভাবে চিন্তা করা', 'ponder, consider', 'ignore, disregard'],
            ['Contend', 'প্রতিযোগিতা করা, দাবি করা', 'compete, argue', 'concede'],
            ['Contentious', 'বিতর্কিত', 'controversial, disputed', 'agreed, settled'],
            ['Context', 'প্রসঙ্গ', 'background, setting', 'none'],
            ['Continuity', 'ধারাবাহিকতা', 'continuation, persistence', 'discontinuity'],
            ['Contract', 'চুক্তি, সংকুচিত হওয়া', 'agreement, shrink', 'expand'],
            ['Contrary', 'বিপরীত', 'opposite, conflicting', 'same, similar'],
            ['Contrast', 'বৈসাদৃশ্য', 'difference, disparity', 'similarity'],
            ['Contrive', 'উদ্ভাবন করা', 'devise, engineer', 'fail'],
            ['Conventional', 'প্রথাগত', 'traditional, standard', 'unconventional, unusual'],
            ['Convince', 'বিশ্বাস করানো', 'persuade, assure', 'dissuade, deter'],
            ['Cordial', 'সৌহার্দ্যপূর্ণ', 'friendly, warm', 'hostile, cold'],
            ['Corporate', 'কর্পোরেট', 'business, commercial', 'none'],
            ['Correspond', 'সঙ্গতিপূর্ণ হওয়া', 'match, communicate', 'differ'],
            ['Corrupt', 'দুর্নীতিগ্রস্ত', 'dishonest, fraudulent', 'honest, incorruptible'],
            ['Counterpart', 'প্রতিরূপ', 'equivalent, match', 'opposite'],
            ['Countless', 'অসংখ্য', 'innumerable, numerous', 'few, limited'],
            ['Craft', 'দক্ষতার সাথে তৈরি করা', 'make, construct', 'destroy'],
            ['Cripple', 'পঙ্গু করা, দুর্বল করা', 'disable, incapacitate', 'strengthen'],
            ['Crisis', 'সংকট', 'emergency, predicament', 'stability'],
            ['Criticism', 'সমালোচনা', 'disapproval, censure', 'praise, approval'],
            ['Cultivate', 'চাষ করা, গড়ে তোলা', 'grow, foster', 'neglect'],
            ['Culminate', 'পরিণতি লাভ করা', 'climax, conclude', 'begin'],
            ['Custody', 'হেফাজত', 'care, guardianship', 'neglect'],
            ['Debate', 'বিতর্ক', 'discussion, argument', 'agreement'],
            ['Decade', 'দশক', 'ten years', 'none'],
            ['Deceive', 'প্রতারণা করা', 'mislead, trick', 'be honest with'],
            ['Decisive', 'সিদ্ধান্তমূলক', 'definitive, resolute', 'indecisive, hesitant'],
            ['Dedicate', 'উৎসর্গ করা', 'devote, commit', 'neglect, abandon'],
            ['Deem', 'বিবেচনা করা', 'consider, judge', 'ignore'],
            ['Default', 'খেলাপ, পূর্বনির্ধারিত', 'failure, standard', 'none'],
            ['Defect', 'ত্রুটি', 'flaw, fault', 'perfection'],
            ['Defiant', 'অবাধ্য', 'rebellious, resistant', 'obedient, compliant'],
            ['Deficit', 'ঘাটতি', 'shortfall, deficiency', 'surplus'],
            ['Definite', 'সুনির্দিষ্ট', 'certain, fixed', 'uncertain, vague'],
            ['Delegate', 'প্রতিনিধি, অর্পণ করা', 'representative, assign', 'withhold'],
            ['Deliberately', 'ইচ্ছাকৃতভাবে', 'intentionally, purposely', 'accidentally'],
            ['Delicate', 'সূক্ষ্ম, নাজুক', 'fragile, subtle', 'sturdy, robust'],
            ['Delusion', 'বিভ্রম', 'illusion, misconception', 'reality'],
            ['Demanding', 'দাবিদার, কষ্টসাধ্য', 'challenging, exacting', 'easy, undemanding'],
            ['Denounce', 'নিন্দা করা', 'condemn, criticize', 'praise, commend'],
            ['Dense', 'ঘন', 'thick, compact', 'sparse, thin'],
            ['Deplete', 'নিঃশেষ করা', 'exhaust, use up', 'replenish, restore'],
            ['Depression', 'হতাশা, মন্দা', 'sadness, recession', 'happiness, boom'],
            ['Deprive', 'বঞ্চিত করা', 'deny, withhold', 'provide, grant'],
            ['Descend', 'অবতরণ করা', 'go down, decline', 'ascend, rise'],
            ['Designate', 'মনোনীত করা', 'appoint, name', 'dismiss'],
            ['Desirable', 'কাম্য', 'attractive, appealing', 'undesirable, unattractive'],
            ['Despair', 'হতাশা', 'hopelessness, despondency', 'hope, optimism'],
            ['Despite', 'সত্ত্বেও', 'notwithstanding, regardless of', 'because of'],
            ['Destination', 'গন্তব্য', 'endpoint, target', 'origin'],
            ['Detrimental', 'ক্ষতিকর', 'harmful, damaging', 'beneficial, helpful'],
            ['Devastate', 'বিধ্বস্ত করা', 'destroy, ruin', 'build, restore'],
        ];

        $now = now();
        $rows = array_map(function ($w) use ($now) {
            return [
                'word' => $w[0],
                'meaning' => $w[1],
                'synonyms' => $w[2],
                'antonyms' => $w[3],
                'lesson_id' => 4,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $words);

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('words')->insert($chunk);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $words = array_column([
            ['Abandon'],['Abolish'],['Absorb'],['Abstract'],['Accessible'],['Accommodate'],['Accompany'],['Accomplish'],['Accordingly'],['Account'],
            ['Accustomed'],['Achieve'],['Acute'],['Adjust'],['Advent'],['Adversity'],['Affect'],['Affluent'],['Aggravate'],['Agenda'],
            ['Aggression'],['Aid'],['Alarming'],['Alienate'],['Align'],['Allege'],['Alleviate'],['Alliance'],['Altruistic'],['Amend'],
            ['Amenity'],['Analyze'],['Ancestor'],['Annual'],['Anonymous'],['Antagonize'],['Apparatus'],['Appealing'],['Applicable'],['Appoint'],
            ['Appraisal'],['Appropriate'],['Approve'],['Aptitude'],['Arise'],['Array'],['Ascertain'],['Aspect'],['Assemble'],['Assessment'],
            ['Asset'],['Assign'],['Assimilate'],['Assortment'],['Astonish'],['Attentive'],['Augment'],['Authority'],['Automate'],['Avert'],
            ['Awareness'],['Awesome'],['Backdrop'],['Backfire'],['Barrier'],['Basis'],['Behalf'],['Benchmark'],['Bestow'],['Bilateral'],
            ['Bind'],['Blatant'],['Bleak'],['Blend'],['Blur'],['Boast'],['Bolster'],['Bond'],['Boundary'],['Breach'],
            ['Breakthrough'],['Breed'],['Brief'],['Broaden'],['Budget'],['Burden'],['Bypass'],['Campaign'],['Candid'],['Capable'],
            ['Capitalize'],['Captivate'],['Cater'],['Ceaseless'],['Certainty'],['Chronic'],['Circulate'],['Clarify'],['Clash'],['Classify'],
            ['Clientele'],['Clinical'],['Clutter'],['Coincide'],['Collapse'],['Collide'],['Colossal'],['Combat'],['Commodity'],['Commonplace'],
            ['Compel'],['Compile'],['Complement'],['Complexity'],['Compliance'],['Component'],['Compromise'],['Conceal'],['Concede'],['Conception'],
            ['Concrete'],['Condemn'],['Confidential'],['Conflict'],['Congestion'],['Conjecture'],['Connotation'],['Conscientious'],['Consequence'],['Considerate'],
            ['Console'],['Conspicuous'],['Constituent'],['Contaminate'],['Contemplate'],['Contend'],['Contentious'],['Context'],['Continuity'],['Contract'],
            ['Contrary'],['Contrast'],['Contrive'],['Conventional'],['Convince'],['Cordial'],['Corporate'],['Correspond'],['Corrupt'],['Counterpart'],
            ['Countless'],['Craft'],['Cripple'],['Crisis'],['Criticism'],['Cultivate'],['Culminate'],['Custody'],['Debate'],['Decade'],
            ['Deceive'],['Decisive'],['Dedicate'],['Deem'],['Default'],['Defect'],['Defiant'],['Deficit'],['Definite'],['Delegate'],
            ['Deliberately'],['Delicate'],['Delusion'],['Demanding'],['Denounce'],['Dense'],['Deplete'],['Depression'],['Deprive'],['Descend'],
            ['Designate'],['Desirable'],['Despair'],['Despite'],['Destination'],['Detrimental'],['Devastate'],
        ], 0);
        DB::table('words')->where('lesson_id', 4)->whereIn('word', $words)->delete();
    }
};
