<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Batch 1 of Medical vocabulary for lesson_id=6 ("Essential
     * Vocabulary List for Medical Students"). Adds 150 new words;
     * lesson had 89 before this, more batches will follow toward 500.
     */
    public function up(): void
    {
        $words = [
            ['Ailment', 'অসুস্থতা', 'illness, sickness', 'health, wellness'],
            ['Allergy', 'অ্যালার্জি', 'hypersensitivity, intolerance', 'tolerance'],
            ['Ambulance', 'অ্যাম্বুলেন্স', 'emergency vehicle', 'none'],
            ['Antibiotic', 'অ্যান্টিবায়োটিক', 'antimicrobial', 'none'],
            ['Antibody', 'অ্যান্টিবডি', 'immunoglobulin', 'antigen'],
            ['Antiseptic', 'জীবাণুনাশক', 'disinfectant, sterilizing', 'contaminant'],
            ['Anxiety', 'উদ্বেগ', 'worry, nervousness', 'calmness, ease'],
            ['Autopsy', 'ময়নাতদন্ত', 'postmortem', 'none'],
            ['Bacteria', 'ব্যাকটেরিয়া', 'microorganism, germ', 'none'],
            ['Bandage', 'ব্যান্ডেজ', 'dressing, wrap', 'none'],
            ['Biopsy', 'বায়োপসি', 'tissue sample', 'none'],
            ['Blister', 'ফোসকা', 'swelling, bubble', 'none'],
            ['Bloodstream', 'রক্তপ্রবাহ', 'circulation', 'none'],
            ['Cardiac', 'হৃদযন্ত্রীয়', 'heart-related', 'none'],
            ['Cardiovascular', 'হৃদরক্তনালীজনিত', 'heart and vessel related', 'none'],
            ['Cavity', 'গহ্বর, দাঁতের ক্ষয়', 'hole, decay', 'none'],
            ['Cell', 'কোষ', 'unit, corpuscle', 'none'],
            ['Chronic', 'দীর্ঘস্থায়ী', 'persistent, long-term', 'acute, temporary'],
            ['Clot', 'রক্ত জমাট বাঁধা', 'coagulate, thrombus', 'dissolve'],
            ['Congenital', 'জন্মগত', 'inborn, hereditary', 'acquired'],
            ['Contagious', 'সংক্রামক', 'infectious, transmissible', 'non-contagious'],
            ['Contusion', 'ক্ষত, থেঁতলানো', 'bruise', 'none'],
            ['Convalesce', 'সুস্থ হয়ে ওঠা', 'recover, recuperate', 'relapse'],
            ['Cure', 'নিরাময় করা', 'heal, remedy', 'worsen'],
            ['Deficiency', 'ঘাটতি', 'shortage, lack', 'sufficiency'],
            ['Diabetes', 'ডায়াবেটিস', 'blood sugar disorder', 'none'],
            ['Diagnose', 'রোগ নির্ণয় করা', 'identify, detect', 'misdiagnose'],
            ['Diarrhea', 'ডায়রিয়া', 'loose motion', 'constipation'],
            ['Digestive', 'পাচক', 'gastric', 'none'],
            ['Discharge', 'স্রাব, ছাড়পত্র দেওয়া', 'release, secretion', 'admit'],
            ['Disease', 'রোগ', 'illness, ailment', 'health'],
            ['Dizziness', 'মাথা ঘোরা', 'vertigo, lightheadedness', 'steadiness'],
            ['Dosage', 'মাত্রা', 'amount, quantity', 'none'],
            ['Drowsy', 'তন্দ্রাচ্ছন্ন', 'sleepy, lethargic', 'alert, awake'],
            ['Elderly', 'বয়স্ক', 'aged, senior', 'young, youthful'],
            ['Embryo', 'ভ্রূণ', 'unborn baby (early stage)', 'none'],
            ['Endocrine', 'অন্তঃক্ষরা', 'hormonal', 'none'],
            ['Enzyme', 'উৎসেচক', 'catalyst', 'none'],
            ['Epidemic', 'মহামারী', 'outbreak, plague', 'none'],
            ['Exhale', 'শ্বাস ছাড়া', 'breathe out', 'inhale'],
            ['Fatigue', 'ক্লান্তি', 'tiredness, exhaustion', 'energy, vigor'],
            ['Fever', 'জ্বর', 'high temperature, pyrexia', 'none'],
            ['Fetus', 'ভ্রূণ', 'unborn baby', 'none'],
            ['Gastric', 'পাকস্থলীসংক্রান্ত', 'stomach-related', 'none'],
            ['Gland', 'গ্রন্থি', 'secretory organ', 'none'],
            ['Hallucination', 'বিভ্রম', 'illusion, delusion', 'reality'],
            ['Heal', 'সেরে ওঠা', 'recover, mend', 'worsen'],
            ['Hemorrhage', 'রক্তক্ষরণ', 'bleeding', 'none'],
            ['Hereditary', 'বংশগত', 'genetic, inherited', 'acquired'],
            ['Hormone', 'হরমোন', 'chemical messenger', 'none'],
            ['Hygiene', 'স্বাস্থ্যবিধি', 'cleanliness, sanitation', 'filth'],
            ['Immunity', 'প্রতিরোধ ক্ষমতা', 'resistance, defense', 'susceptibility'],
            ['Immunize', 'টিকা দেওয়া', 'vaccinate, inoculate', 'none'],
            ['Impair', 'দুর্বল করা', 'damage, weaken', 'enhance, strengthen'],
            ['Implant', 'প্রতিস্থাপন করা', 'insert, embed', 'remove'],
            ['Inflammation', 'প্রদাহ', 'swelling, irritation', 'soothing'],
            ['Ingest', 'গ্রহণ করা', 'consume, swallow', 'expel'],
            ['Inject', 'ইনজেকশন দেওয়া', 'inoculate, administer', 'extract'],
            ['Insomnia', 'অনিদ্রা', 'sleeplessness', 'sound sleep'],
            ['Intestine', 'অন্ত্র', 'bowel, gut', 'none'],
            ['Irregular', 'অনিয়মিত', 'erratic, inconsistent', 'regular, consistent'],
            ['Isolation', 'বিচ্ছিন্নতা, কোয়ারেন্টাইন', 'quarantine, seclusion', 'integration'],
            ['Jaundice', 'জন্ডিস', 'yellowing of skin', 'none'],
            ['Joint', 'অস্থিসন্ধি', 'articulation', 'none'],
            ['Kidney', 'বৃক্ক, কিডনি', 'renal organ', 'none'],
            ['Lesion', 'ক্ষত', 'wound, injury', 'none'],
            ['Lethal', 'প্রাণঘাতী', 'deadly, fatal', 'harmless'],
            ['Liver', 'যকৃত', 'hepatic organ', 'none'],
            ['Lung', 'ফুসফুস', 'pulmonary organ', 'none'],
            ['Malignant', 'মারাত্মক, ক্যান্সারযুক্ত', 'cancerous, harmful', 'benign'],
            ['Medication', 'ঔষধ', 'medicine, drug', 'none'],
            ['Membrane', 'ঝিল্লি', 'layer, tissue', 'none'],
            ['Metabolism', 'বিপাক', 'digestion process', 'none'],
            ['Migraine', 'মাইগ্রেন', 'severe headache', 'none'],
            ['Nerve', 'স্নায়ু', 'neural fiber', 'none'],
            ['Nutrient', 'পুষ্টি উপাদান', 'nourishment', 'none'],
            ['Obese', 'স্থূলকায়', 'overweight, fat', 'thin, slim'],
            ['Onset', 'সূচনা', 'beginning, start', 'end'],
            ['Outbreak', 'প্রাদুর্ভাব', 'epidemic, eruption', 'containment'],
            ['Ovary', 'ডিম্বাশয়', 'reproductive organ', 'none'],
            ['Overdose', 'অতিরিক্ত মাত্রা', 'excess dose', 'underdose'],
            ['Pandemic', 'অতিমারী', 'global outbreak', 'none'],
            ['Paralysis', 'পক্ষাঘাত', 'immobility', 'mobility'],
            ['Pathogen', 'রোগজীবাণু', 'germ, microbe', 'none'],
            ['Pediatric', 'শিশুরোগবিদ্যাসংক্রান্ত', 'child-related medical', 'none'],
            ['Pelvis', 'শ্রোণী', 'hip bone area', 'none'],
            ['Physiology', 'শারীরবিদ্যা', 'bodily function study', 'none'],
            ['Placenta', 'অমরা', 'afterbirth organ', 'none'],
            ['Pneumonia', 'নিউমোনিয়া', 'lung infection', 'none'],
            ['Postpartum', 'প্রসবোত্তর', 'after childbirth', 'prenatal'],
            ['Pulse', 'নাড়ির স্পন্দন', 'heartbeat', 'none'],
            ['Pupil', 'চোখের মণি', 'eye opening', 'none'],
            ['Quarantine', 'কোয়ারেন্টাইন', 'isolation', 'none'],
            ['Radiology', 'রেডিওলজি', 'imaging medicine', 'none'],
            ['Recovery', 'আরোগ্য', 'healing, restoration', 'relapse'],
            ['Rehabilitation', 'পুনর্বাসন', 'recovery therapy', 'none'],
            ['Relapse', 'পুনরায় অসুস্থ হওয়া', 'recurrence, setback', 'recovery'],
            ['Remedy', 'প্রতিকার', 'cure, treatment', 'none'],
            ['Remission', 'উপশম', 'relief, abatement', 'relapse'],
            ['Renal', 'বৃক্কীয়', 'kidney-related', 'none'],
            ['Resistant', 'প্রতিরোধী', 'immune, unaffected', 'susceptible'],
            ['Respire', 'শ্বাস নেওয়া', 'breathe', 'none'],
            ['Sanitary', 'স্বাস্থ্যকর', 'hygienic, clean', 'unsanitary'],
            ['Sedative', 'প্রশমক ঔষধ', 'tranquilizer', 'stimulant'],
            ['Sepsis', 'রক্তে বিষক্রিয়া', 'blood infection', 'none'],
            ['Severe', 'গুরুতর', 'serious, intense', 'mild, minor'],
            ['Sibling', 'ভাইবোন', 'brother, sister', 'none'],
            ['Skeletal', 'কঙ্কালতন্ত্রীয়', 'bone-related', 'none'],
            ['Sore', 'ব্যথাযুক্ত, ক্ষত', 'painful, tender', 'painless'],
            ['Sterile', 'জীবাণুমুক্ত, বন্ধ্যা', 'germ-free, infertile', 'contaminated, fertile'],
            ['Stitch', 'সেলাই', 'suture', 'none'],
            ['Stroke', 'স্ট্রোক (মস্তিষ্কে রক্তক্ষরণ)', 'cerebral attack', 'none'],
            ['Symptom', 'লক্ষণ', 'sign, indication', 'none'],
            ['Syndrome', 'সিন্ড্রোম, লক্ষণসমষ্টি', 'condition, disorder', 'none'],
            ['Syringe', 'সিরিঞ্জ', 'needle, injector', 'none'],
            ['Tablet', 'বড়ি, ট্যাবলেট', 'pill', 'none'],
            ['Terminal', 'শেষ পর্যায়ের, মরণাপন্ন', 'final, fatal', 'curable'],
            ['Therapy', 'চিকিৎসা', 'treatment', 'none'],
            ['Thrombosis', 'রক্ত জমাট বাঁধার রোগ', 'blood clot condition', 'none'],
            ['Tissue', 'কলা, টিস্যু', 'cell structure', 'none'],
            ['Tonsil', 'টনসিল', 'throat gland', 'none'],
            ['Toxic', 'বিষাক্ত', 'poisonous, harmful', 'harmless, safe'],
            ['Trauma', 'মানসিক বা শারীরিক আঘাত', 'injury, shock', 'comfort'],
            ['Treatment', 'চিকিৎসা', 'therapy, remedy', 'neglect'],
            ['Tumor', 'টিউমার', 'growth, mass', 'none'],
            ['Ulcer', 'আলসার, ক্ষত', 'sore, lesion', 'none'],
            ['Umbilical', 'নাভিসংক্রান্ত', 'navel-related', 'none'],
            ['Urgent', 'জরুরি', 'pressing, critical', 'non-urgent'],
            ['Urine', 'মূত্র', 'clinical term for pee', 'none'],
            ['Vaccine', 'টিকা', 'immunization, inoculation', 'none'],
            ['Vertebra', 'কশেরুকা', 'spinal bone', 'none'],
            ['Viral', 'ভাইরাসঘটিত', 'virus-related', 'bacterial'],
            ['Vision', 'দৃষ্টিশক্তি', 'eyesight, sight', 'blindness'],
            ['Vomit', 'বমি করা', 'throw up, regurgitate', 'none'],
            ['Wound', 'ক্ষত', 'injury, cut', 'healing'],
            ['X-ray', 'এক্স-রে', 'radiograph', 'none'],
            ['Airway', 'শ্বাসনালী', 'respiratory passage', 'none'],
            ['Alveoli', 'ফুসফুসের বায়ুথলি', 'air sacs', 'none'],
            ['Anatomy', 'দেহতত্ত্ব', 'body structure study', 'none'],
            ['Antenatal', 'প্রসবপূর্ব', 'prenatal', 'postnatal'],
            ['Bladder', 'মূত্রাশয়', 'urinary sac', 'none'],
            ['Cartilage', 'তরুণাস্থি', 'cushioning tissue', 'none'],
            ['Cerebral', 'মস্তিষ্কসংক্রান্ত', 'brain-related', 'none'],
            ['Circulation', 'সংবহন', 'blood flow', 'none'],
            ['Clinic', 'চিকিৎসালয়', 'medical center', 'none'],
            ['Cornea', 'কর্নিয়া', 'eye covering', 'none'],
            ['Cranium', 'করোটি', 'skull', 'none'],
            ['Diaphragm', 'মধ্যচ্ছদা', 'breathing muscle', 'none'],
            ['Esophagus', 'অন্ননালী', 'food pipe', 'none'],
        ];

        $now = now();
        $rows = array_map(function ($w) use ($now) {
            return [
                'word' => $w[0],
                'meaning' => $w[1],
                'synonyms' => $w[2],
                'antonyms' => $w[3],
                'lesson_id' => 6,
                'status' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $words);

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('words')->insert($chunk);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $words = [
            'Ailment','Allergy','Ambulance','Antibiotic','Antibody','Antiseptic','Anxiety','Autopsy','Bacteria','Bandage',
            'Biopsy','Blister','Bloodstream','Cardiac','Cardiovascular','Cavity','Cell','Chronic','Clot','Congenital',
            'Contagious','Contusion','Convalesce','Cure','Deficiency','Diabetes','Diagnose','Diarrhea','Digestive','Discharge',
            'Disease','Dizziness','Dosage','Drowsy','Elderly','Embryo','Endocrine','Enzyme','Epidemic','Exhale',
            'Fatigue','Fever','Fetus','Gastric','Gland','Hallucination','Heal','Hemorrhage','Hereditary','Hormone',
            'Hygiene','Immunity','Immunize','Impair','Implant','Inflammation','Ingest','Inject','Insomnia','Intestine',
            'Irregular','Isolation','Jaundice','Joint','Kidney','Lesion','Lethal','Liver','Lung','Malignant',
            'Medication','Membrane','Metabolism','Migraine','Nerve','Nutrient','Obese','Onset','Outbreak','Ovary',
            'Overdose','Pandemic','Paralysis','Pathogen','Pediatric','Pelvis','Physiology','Placenta','Pneumonia','Postpartum',
            'Pulse','Pupil','Quarantine','Radiology','Recovery','Rehabilitation','Relapse','Remedy','Remission','Renal',
            'Resistant','Respire','Sanitary','Sedative','Sepsis','Severe','Sibling','Skeletal','Sore','Sterile',
            'Stitch','Stroke','Symptom','Syndrome','Syringe','Tablet','Terminal','Therapy','Thrombosis','Tissue',
            'Tonsil','Toxic','Trauma','Treatment','Tumor','Ulcer','Umbilical','Urgent','Urine','Vaccine',
            'Vertebra','Viral','Vision','Vomit','Wound','X-ray','Airway','Alveoli','Anatomy','Antenatal',
            'Bladder','Cartilage','Cerebral','Circulation','Clinic','Cornea','Cranium','Diaphragm','Esophagus',
        ];
        DB::table('words')->where('lesson_id', 6)->whereIn('word', $words)->delete();
    }
};
