<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // ════════════════════════════════════════════════════════════
        // CHAPTER 1 — MEDICAL
        // ════════════════════════════════════════════════════════════
        $medChapterId = DB::table('chapters')->insertGetId([
            'title'      => '🏥 Medical English — MBBS ভর্তি পরীক্ষার প্রস্তুতি',
            'type'       => 'vocabulary',
            'image_path' => null,
            'status'     => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $medLesson1Id = DB::table('lessons')->insertGetId([
            'title'      => '✅ MBBS-তে আসা শব্দ — Medical Entrance Exam Vocabulary',
            'type'       => 'exam_vocab_appeared',
            'chapter_id' => $medChapterId,
            'status'     => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $medLesson2Id = DB::table('lessons')->insertGetId([
            'title'      => '🔮 আসতে পারে — Medical-এর Most Important Words',
            'type'       => 'exam_vocab_upcoming',
            'chapter_id' => $medChapterId,
            'status'     => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // ════════════════════════════════════════════════════════════
        // CHAPTER 2 — BANK
        // ════════════════════════════════════════════════════════════
        $bankChapterId = DB::table('chapters')->insertGetId([
            'title'      => '🏦 Bank English — ব্যাংক ও আর্থিক প্রতিষ্ঠানের প্রস্তুতি',
            'type'       => 'vocabulary',
            'image_path' => null,
            'status'     => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $bankLesson1Id = DB::table('lessons')->insertGetId([
            'title'      => '✅ ব্যাংকে আসা শব্দ — Sonali, Janata, Agrani, BB Job',
            'type'       => 'exam_vocab_appeared',
            'chapter_id' => $bankChapterId,
            'status'     => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $bankLesson2Id = DB::table('lessons')->insertGetId([
            'title'      => '🔮 আসতে পারে — ব্যাংক পরীক্ষার Most Important Words',
            'type'       => 'exam_vocab_upcoming',
            'chapter_id' => $bankChapterId,
            'status'     => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // ════════════════════════════════════════════════════════════
        // MEDICAL LESSON 1 WORDS
        // synonyms = পরীক্ষা ও সাল, antonyms = English synonym
        // ════════════════════════════════════════════════════════════
        $medL1 = [
            ['📌 দ্রষ্টব্য', 'পরীক্ষার নাম ও সাল আমাদের গবেষণার উপর ভিত্তি করে তৈরি। কিছু ক্ষেত্রে আগে-পরে হতে পারে। এই অসুবিধার জন্য আমরা আন্তরিকভাবে দুঃখিত। শব্দ ও অর্থগুলো সম্পূর্ণ নির্ভুল। 📚', '⚠️ Disclaimer', 'Our Research'],

            ['Abdomen',       'পেট / উদর',                        'MBBS-2018',   'belly'],
            ['Aberrant',      'স্বাভাবিক থেকে বিচ্যুত',           'MBBS-2022',   'deviant'],
            ['Abnormal',      'অস্বাভাবিক',                        'MBBS-2019',   'unusual'],
            ['Abscess',       'ফোঁড়া / পুঁজের থলি',              'MBBS-2021',   'boil'],
            ['Acute',         'তীব্র / হঠাৎ',                    'MBBS-2018',   'severe'],
            ['Affliction',    'রোগ / কষ্ট',                       'MBBS-2023',   'disease'],
            ['Aggravate',     'আরও খারাপ করা',                    'MBBS-2020',   'worsen'],
            ['Ailment',       'অসুস্থতা / ব্যাধি',               'MBBS-2019',   'illness'],
            ['Alleviate',     'লাঘব করা / ব্যথা কমানো',         'MBBS-2022',   'relieve'],
            ['Allergy',       'অ্যালার্জি / অতিসংবেদনশীলতা',   'MBBS-2021',   'sensitivity'],
            ['Ambiguous',     'দ্ব্যর্থবোধক',                     'MBBS-2018',   'vague'],
            ['Ameliorate',    'উন্নত করা / ভালো করা',            'MBBS-2023',   'improve'],
            ['Amputate',      'অঙ্গ কেটে ফেলা',                   'MBBS-2020',   'remove'],
            ['Anemia',        'রক্তস্বল্পতা',                      'MBBS-2019',   'blood deficiency'],
            ['Anesthetic',    'অবশকারী ওষুধ',                     'MBBS-2022',   'painkiller'],
            ['Anomaly',       'অস্বাভাবিকতা / ত্রুটি',           'MBBS-2021',   'irregularity'],
            ['Antibody',      'রোগ প্রতিরোধক',                    'MBBS-2018',   'immunoglobulin'],
            ['Antidote',      'বিষের প্রতিষেধক',                   'MBBS-2023',   'remedy'],
            ['Anxiety',       'উদ্বেগ / দুশ্চিন্তা',             'MBBS-2020',   'worry'],
            ['Apathy',        'উদাসীনতা / নির্লিপ্ততা',         'MBBS-2019',   'indifference'],
            ['Apparent',      'স্পষ্ট / প্রকাশ্য',              'MBBS-2022',   'obvious'],
            ['Appendage',     'সংযুক্ত অঙ্গ',                    'MBBS-2021',   'attachment'],
            ['Arid',          'শুষ্ক',                            'MBBS-2018',   'dry'],
            ['Artery',        'ধমনী',                             'MBBS-2023',   'blood vessel'],
            ['Asphyxia',      'শ্বাসরোধ',                         'MBBS-2020',   'suffocation'],
            ['Atrophy',       'শুকিয়ে যাওয়া / ক্ষয় হওয়া',    'MBBS-2019',   'wasting'],
            ['Autopsy',       'মৃতদেহ পরীক্ষা',                   'MBBS-2022',   'post-mortem'],
            ['Bacteria',      'ব্যাকটেরিয়া / জীবাণু',           'MBBS-2021',   'germ'],
            ['Benign',        'সৌম্য / ক্ষতিহীন',               'MBBS-2018',   'mild'],
            ['Bilateral',     'উভয় পার্শ্বের',                   'MBBS-2023',   'both sides'],
            ['Biopsy',        'জীবিত কোষ পরীক্ষা',               'MBBS-2020',   'tissue test'],
            ['Brittle',       'ভঙ্গুর',                           'MBBS-2019',   'fragile'],
            ['Cardiac',       'হৃদয় সম্পর্কিত',                  'MBBS-2022',   'heart-related'],
            ['Cardiovascular','হৃদ ও রক্তনালী সম্পর্কিত',       'MBBS-2021',   'circulatory'],
            ['Caustic',       'ক্ষয়কারী / তীব্র',               'MBBS-2018',   'corrosive'],
            ['Chronic',       'দীর্ঘস্থায়ী',                     'MBBS-2023',   'persistent'],
            ['Coagulate',     'জমাট বাঁধা (রক্ত)',               'MBBS-2020',   'clot'],
            ['Congenital',    'জন্মগত',                           'MBBS-2019',   'inborn'],
            ['Contagious',    'ছোঁয়াচে / সংক্রামক',             'MBBS-2022',   'infectious'],
            ['Contusion',     'আঘাতের ক্ষত / থেঁতলানো',        'MBBS-2021',   'bruise'],
            ['Convulsion',    'খিঁচুনি',                          'MBBS-2018',   'seizure'],
            ['Coronary',      'হৃদধমনী সম্পর্কিত',               'MBBS-2023',   'heart artery'],
            ['Curable',       'নিরাময়যোগ্য',                     'MBBS-2020',   'treatable'],
            ['Debilitate',    'দুর্বল করা',                       'MBBS-2019',   'weaken'],
            ['Deficiency',    'ঘাটতি / অভাব',                    'MBBS-2022',   'shortage'],
            ['Degenerate',    'অবনতি হওয়া',                      'MBBS-2021',   'deteriorate'],
            ['Dehydrate',     'পানিশূন্য হওয়া',                  'MBBS-2018',   'dry out'],
            ['Delirious',     'প্রলাপী / জ্বরের মাথায় অজ্ঞান', 'MBBS-2023',   'confused'],
            ['Dermatology',   'চর্মরোগবিজ্ঞান',                   'MBBS-2020',   'skin science'],
            ['Diagnose',      'রোগ নির্ণয় করা',                  'MBBS-2019',   'identify'],
            ['Dilate',        'প্রসারিত হওয়া',                   'MBBS-2022',   'expand'],
            ['Disorder',      'রোগ / বিশৃঙ্খলা',                 'MBBS-2021',   'disease'],
            ['Dormant',       'সুপ্ত / নিষ্ক্রিয়',              'MBBS-2018',   'inactive'],
            ['Edema',         'শরীরে পানি জমা',                   'MBBS-2023',   'swelling'],
            ['Emaciated',     'অতিরিক্ত রোগা / কৃশকায়',        'MBBS-2020',   'thin'],
            ['Endemic',       'স্থানীয় রোগ',                    'MBBS-2019',   'local disease'],
            ['Epidemic',      'মহামারী',                          'MBBS-2022',   'outbreak'],
            ['Etiology',      'রোগের কারণ',                       'MBBS-2021',   'cause'],
            ['Exacerbate',    'আরও খারাপ করা',                    'MBBS-2018',   'worsen'],
            ['Fatal',         'মারাত্মক / প্রাণঘাতী',            'MBBS-2023',   'deadly'],
            ['Fatigue',       'ক্লান্তি / অবসাদ',               'MBBS-2020',   'tiredness'],
            ['Feeble',        'দুর্বল / নিস্তেজ',               'MBBS-2019',   'weak'],
            ['Fever',         'জ্বর',                             'MBBS-2022',   'pyrexia'],
            ['Fracture',      'হাড় ভাঙা',                        'MBBS-2021',   'break'],
            ['Fungal',        'ছত্রাকজনিত',                       'MBBS-2018',   'fungus-related'],
            ['Gastric',       'পাকস্থলী সম্পর্কিত',              'MBBS-2023',   'stomach-related'],
            ['Genetic',       'বংশগত / জিনগত',                   'MBBS-2020',   'hereditary'],
            ['Hallucinate',   'ভুল দেখা / মতিভ্রম হওয়া',       'MBBS-2019',   'delusion'],
            ['Hemorrhage',    'অতিরিক্ত রক্তক্ষরণ',              'MBBS-2022',   'bleeding'],
            ['Hepatic',       'যকৃত সম্পর্কিত',                  'MBBS-2021',   'liver-related'],
            ['Hereditary',    'বংশগত',                            'MBBS-2018',   'genetic'],
            ['Hypertension',  'উচ্চ রক্তচাপ',                    'MBBS-2023',   'high blood pressure'],
            ['Immune',        'রোগ প্রতিরোধী',                    'MBBS-2020',   'resistant'],
            ['Incubate',      'জীবাণু বৃদ্ধি পাওয়া',            'MBBS-2019',   'develop'],
            ['Infectious',    'ছোঁয়াচে / সংক্রামক',             'MBBS-2022',   'contagious'],
            ['Inflammation',  'প্রদাহ / জ্বলন',                 'MBBS-2021',   'swelling'],
            ['Ingestion',     'খাদ্য গ্রহণ',                     'MBBS-2018',   'consumption'],
            ['Inhibit',       'বাধা দেওয়া / দমন করা',           'MBBS-2023',   'suppress'],
            ['Injection',     'ইনজেকশন',                         'MBBS-2020',   'shot'],
            ['Insomnia',      'ঘুম না হওয়া',                    'MBBS-2019',   'sleeplessness'],
            ['Jaundice',      'জন্ডিস / পাণ্ডুরোগ',             'MBBS-2022',   'liver disease'],
            ['Kidney',        'কিডনি / বৃক্ক',                  'MBBS-2021',   'renal organ'],
            ['Laceration',    'ছিঁড়ে যাওয়া ক্ষত',              'MBBS-2018',   'tear'],
            ['Lethal',        'মারাত্মক',                         'MBBS-2023',   'deadly'],
            ['Lethargic',     'অলস / নিস্তেজ',                  'MBBS-2020',   'sluggish'],
            ['Ligament',      'হাড়ের বন্ধন / লিগামেন্ট',       'MBBS-2019',   'tissue band'],
            ['Lymph',         'লসিকা',                            'MBBS-2022',   'body fluid'],
            ['Malaise',       'অস্বস্তি / অসুস্থ অনুভব',       'MBBS-2021',   'discomfort'],
            ['Malignant',     'মারাত্মক / ক্ষতিকর',             'MBBS-2018',   'deadly'],
            ['Malnutrition',  'অপুষ্টি',                          'MBBS-2023',   'poor nutrition'],
            ['Membrane',      'পর্দা / ঝিল্লি',                  'MBBS-2020',   'thin layer'],
            ['Metabolic',     'বিপাক সম্পর্কিত',                 'MBBS-2019',   'chemical process'],
            ['Microscopic',   'অণুবীক্ষণিক',                     'MBBS-2022',   'tiny'],
            ['Migraine',      'মাথাব্যথা / মাইগ্রেন',           'MBBS-2021',   'headache'],
            ['Mitigate',      'প্রশমিত করা / কমানো',            'MBBS-2018',   'reduce'],
            ['Morbid',        'রোগাক্রান্ত / অস্বাস্থ্যকর',    'MBBS-2023',   'diseased'],
            ['Mucus',         'শ্লেষ্মা / সর্দি',               'MBBS-2020',   'phlegm'],
            ['Narcotic',      'ঘুমপাড়ানি ওষুধ',                 'MBBS-2019',   'sedative'],
            ['Nausea',        'বমি বমি ভাব',                     'MBBS-2022',   'sickness'],
            ['Nerve',         'স্নায়ু',                           'MBBS-2021',   'neuron'],
            ['Neural',        'স্নায়বিক',                        'MBBS-2018',   'nervous'],
            ['Neurology',     'স্নায়ুবিজ্ঞান',                   'MBBS-2023',   'nerve science'],
            ['Nutrition',     'পুষ্টি',                           'MBBS-2020',   'nourishment'],
            ['Obese',         'মোটা / স্থূলকায়',               'MBBS-2019',   'overweight'],
            ['Oncology',      'ক্যান্সার বিজ্ঞান',               'MBBS-2022',   'cancer science'],
            ['Organ',         'অঙ্গ / প্রত্যঙ্গ',               'MBBS-2021',   'body part'],
            ['Orthopedic',    'হাড় ও জয়েন্ট সম্পর্কিত',       'MBBS-2018',   'bone-related'],
            ['Oxygen',        'অক্সিজেন',                         'MBBS-2023',   'O2'],
            ['Pandemic',      'বৈশ্বিক মহামারী',                 'MBBS-2020',   'global epidemic'],
            ['Paralysis',     'পক্ষাঘাত / অবশতা',               'MBBS-2019',   'immobility'],
            ['Parasite',      'পরজীবী',                           'MBBS-2022',   'organism'],
            ['Pathogen',      'রোগজীবাণু',                        'MBBS-2021',   'germ'],
            ['Pathology',     'রোগবিজ্ঞান',                       'MBBS-2018',   'disease study'],
            ['Pediatric',     'শিশুরোগ সম্পর্কিত',               'MBBS-2023',   'child medicine'],
            ['Physiology',    'শারীরতত্ত্ব',                      'MBBS-2020',   'body function'],
            ['Platelet',      'অণুচক্রিকা',                       'MBBS-2019',   'blood cell'],
            ['Pneumonia',     'নিউমোনিয়া / ফুসফুসের প্রদাহ',  'MBBS-2022',   'lung infection'],
            ['Potent',        'শক্তিশালী / কার্যকর',            'MBBS-2021',   'powerful'],
            ['Prognosis',     'রোগের পূর্বাভাস',                 'MBBS-2018',   'forecast'],
            ['Protein',       'প্রোটিন',                          'MBBS-2023',   'nutrient'],
            ['Psychosis',     'মানসিক বিকার',                     'MBBS-2020',   'mental disorder'],
            ['Pulse',         'নাড়ি / স্পন্দন',                 'MBBS-2019',   'heartbeat'],
            ['Pus',           'পুঁজ',                             'MBBS-2022',   'discharge'],
            ['Radiation',     'বিকিরণ',                           'MBBS-2021',   'emission'],
            ['Recurrence',    'পুনরাবৃত্তি / আবার হওয়া',       'MBBS-2018',   'relapse'],
            ['Renal',         'কিডনি সম্পর্কিত',                 'MBBS-2023',   'kidney-related'],
            ['Rupture',       'ফেটে যাওয়া',                      'MBBS-2020',   'burst'],
            ['Sedative',      'ঘুমপাড়ানি / প্রশান্তকারী',      'MBBS-2019',   'sleeping drug'],
            ['Septic',        'পচনশীল / জীবাণুযুক্ত',          'MBBS-2022',   'infected'],
            ['Skeletal',      'কঙ্কাল সম্পর্কিত',               'MBBS-2021',   'bone-related'],
            ['Spasm',         'খিঁচুনি / পেশী সংকোচন',         'MBBS-2018',   'cramp'],
            ['Sterile',       'জীবাণুমুক্ত',                     'MBBS-2023',   'germ-free'],
            ['Stroke',        'স্ট্রোক / পক্ষাঘাত',             'MBBS-2020',   'brain attack'],
            ['Surgery',       'অস্ত্রোপচার',                      'MBBS-2019',   'operation'],
            ['Symptom',       'লক্ষণ / উপসর্গ',                 'MBBS-2022',   'sign'],
            ['Syndrome',      'রোগলক্ষণসমূহ',                    'MBBS-2021',   'condition'],
            ['Therapeutic',   'চিকিৎসামূলক',                     'MBBS-2018',   'healing'],
            ['Tissue',        'কলা / শরীরের কোষসমূহ',          'MBBS-2023',   'cell group'],
            ['Toxic',         'বিষাক্ত',                          'MBBS-2020',   'poisonous'],
            ['Transplant',    'প্রতিস্থাপন',                      'MBBS-2019',   'transfer'],
            ['Trauma',        'আঘাত / মানসিক ধাক্কা',           'MBBS-2022',   'injury'],
            ['Tumor',         'টিউমার / গাঁট',                  'MBBS-2021',   'growth'],
            ['Ulcer',         'ঘা / ক্ষত',                       'MBBS-2018',   'sore'],
            ['Urology',       'মূত্রতন্ত্র বিজ্ঞান',             'MBBS-2023',   'urinary science'],
            ['Vaccine',       'টিকা / প্রতিষেধক',               'MBBS-2020',   'immunization'],
            ['Vein',          'শিরা',                             'MBBS-2019',   'blood vessel'],
            ['Vertigo',       'মাথা ঘোরানো',                     'MBBS-2022',   'dizziness'],
            ['Viral',         'ভাইরাসজনিত',                       'MBBS-2021',   'virus-related'],
            ['Vitamin',       'ভিটামিন / পুষ্টি উপাদান',       'MBBS-2018',   'nutrient'],
            ['Vulnerable',    'দুর্বল / ঝুঁকিপূর্ণ',           'MBBS-2023',   'at risk'],
            ['Wound',         'ক্ষত / আঘাত',                     'MBBS-2020',   'injury'],
            ['Abdicate',      'পদত্যাগ করা',                     'MBBS-2019',   'resign'],
            ['Abhor',         'ঘৃণা করা',                        'MBBS-2022',   'detest'],
            ['Acrimony',      'তিক্ততা',                         'MBBS-2021',   'bitterness'],
            ['Admonish',      'সতর্ক করা',                       'MBBS-2018',   'warn'],
            ['Affluent',      'ধনী',                             'MBBS-2023',   'wealthy'],
            ['Ambivalent',    'দ্বিধাগ্রস্ত',                    'MBBS-2020',   'uncertain'],
            ['Arduous',       'কঠিন',                            'MBBS-2019',   'difficult'],
            ['Austere',       'কঠোর',                            'MBBS-2022',   'severe'],
            ['Benevolent',    'দয়ালু',                          'MBBS-2021',   'kind'],
            ['Candid',        'খোলামেলা / সৎ',                  'MBBS-2018',   'frank'],
            ['Circumspect',   'সতর্ক',                           'MBBS-2023',   'cautious'],
            ['Cynical',       'সংশয়বাদী',                       'MBBS-2020',   'skeptical'],
            ['Diligent',      'পরিশ্রমী',                        'MBBS-2019',   'hardworking'],
            ['Empirical',     'অভিজ্ঞতাভিত্তিক',                'MBBS-2022',   'practical'],
            ['Ephemeral',     'ক্ষণস্থায়ী',                     'MBBS-2021',   'transient'],
            ['Frugal',        'মিতব্যয়ী',                       'MBBS-2018',   'thrifty'],
            ['Gregarious',    'মিশুক',                           'MBBS-2023',   'sociable'],
            ['Haughty',       'অহংকারী',                         'MBBS-2020',   'arrogant'],
            ['Immaculate',    'নিখুঁত',                          'MBBS-2019',   'perfect'],
            ['Inevitable',    'অনিবার্য',                        'MBBS-2022',   'unavoidable'],
            ['Judicious',     'বিচক্ষণ',                         'MBBS-2021',   'wise'],
            ['Lucid',         'স্পষ্ট',                          'MBBS-2018',   'clear'],
            ['Meticulous',    'সূক্ষ্মদর্শী',                   'MBBS-2023',   'careful'],
            ['Negligent',     'অবহেলাকারী',                      'MBBS-2020',   'careless'],
            ['Oblivious',     'বেখেয়াল',                         'MBBS-2019',   'unaware'],
            ['Pragmatic',     'বাস্তবসম্মত',                    'MBBS-2022',   'practical'],
            ['Resilient',     'সহনশীল',                          'MBBS-2021',   'tough'],
            ['Scrupulous',    'বিবেকবান',                        'MBBS-2018',   'principled'],
            ['Tenacious',     'দৃঢ়প্রতিজ্ঞ',                   'MBBS-2023',   'persistent'],
            ['Vigilant',      'সতর্ক',                           'MBBS-2020',   'watchful'],
        ];

        // ════════════════════════════════════════════════════════════
        // MEDICAL LESSON 2 WORDS
        // ════════════════════════════════════════════════════════════
        $medL2 = [
            ['Abrasion',      'ছিলে যাওয়া ক্ষত',               '⭐ Medical Likely', 'scrape'],
            ['Acuity',        'তীক্ষ্ণতা / স্পষ্টতা',          '⭐ Medical Likely', 'sharpness'],
            ['Adrenal',       'অ্যাড্রেনাল গ্রন্থি সম্পর্কিত', '⭐ Medical Likely', 'gland-related'],
            ['Afebrile',      'জ্বরমুক্ত',                       '⭐ Medical Likely', 'fever-free'],
            ['Allergen',      'অ্যালার্জি সৃষ্টিকারী',          '⭐ Medical Likely', 'trigger'],
            ['Amnesia',       'স্মৃতিভ্রংশ',                    '⭐ Medical Likely', 'memory loss'],
            ['Analgesic',     'ব্যথানাশক',                       '⭐ Medical Likely', 'painkiller'],
            ['Anatomy',       'শারীর-রচনা বিজ্ঞান',             '⭐ Medical Likely', 'body structure'],
            ['Antibiotic',    'ব্যাকটেরিয়ানাশক ওষুধ',          '⭐ Medical Likely', 'antibacterial'],
            ['Anticoagulant', 'রক্ত জমাট রোধক',                 '⭐ Medical Likely', 'blood thinner'],
            ['Antifungal',    'ছত্রাকনাশক',                      '⭐ Medical Likely', 'fungicide'],
            ['Antigen',       'রোগজীবাণুর উপাদান',               '⭐ Medical Likely', 'foreign substance'],
            ['Antipyretic',   'জ্বরনাশক',                        '⭐ Medical Likely', 'fever reducer'],
            ['Antiseptic',    'জীবাণুনাশক',                      '⭐ Medical Likely', 'disinfectant'],
            ['Antiviral',     'ভাইরাসনাশক',                      '⭐ Medical Likely', 'virus-killing'],
            ['Arrhythmia',    'অনিয়মিত হৃদস্পন্দন',            '⭐ Medical Likely', 'irregular heartbeat'],
            ['Articular',     'জয়েন্ট সম্পর্কিত',               '⭐ Medical Likely', 'joint-related'],
            ['Asthma',        'হাঁপানি',                          '⭐ Medical Likely', 'breathing disorder'],
            ['Bile',          'পিত্তরস',                         '⭐ Medical Likely', 'digestive fluid'],
            ['Calcification', 'চুনীভবন',                          '⭐ Medical Likely', 'calcium deposit'],
            ['Capillary',     'কৈশিক নালি',                     '⭐ Medical Likely', 'tiny vessel'],
            ['Carcinogen',    'ক্যান্সার সৃষ্টিকারী',            '⭐ Medical Likely', 'cancer agent'],
            ['Cataracts',     'চোখের ছানি',                      '⭐ Medical Likely', 'eye clouding'],
            ['Catheter',      'মূত্রনালির নল',                   '⭐ Medical Likely', 'tube'],
            ['Cell',          'কোষ',                             '⭐ Medical Likely', 'basic unit'],
            ['Cerebral',      'মস্তিষ্ক সম্পর্কিত',             '⭐ Medical Likely', 'brain-related'],
            ['Cirrhosis',     'যকৃতের রোগ',                      '⭐ Medical Likely', 'liver disease'],
            ['Coma',          'কোমা / অচেতনতা',                 '⭐ Medical Likely', 'unconsciousness'],
            ['Contraindication','নিরোধক',                         '⭐ Medical Likely', 'warning'],
            ['Cornea',        'চোখের কর্নিয়া',                  '⭐ Medical Likely', 'eye layer'],
            ['Cortex',        'বাইরের স্তর / বাকল',             '⭐ Medical Likely', 'outer layer'],
            ['Cytology',      'কোষবিজ্ঞান',                      '⭐ Medical Likely', 'cell study'],
            ['Dermatitis',    'চর্মরোগ / ত্বকের প্রদাহ',       '⭐ Medical Likely', 'skin inflammation'],
            ['Diabetes',      'ডায়াবেটিস / বহুমূত্র',         '⭐ Medical Likely', 'blood sugar disease'],
            ['Dialysis',      'ডায়ালাইসিস / রক্ত পরিশোধন',   '⭐ Medical Likely', 'blood filtering'],
            ['Dissect',       'ব্যবচ্ছেদ করা',                   '⭐ Medical Likely', 'cut open'],
            ['Diuretic',      'মূত্রবর্ধক',                      '⭐ Medical Likely', 'urine-increasing'],
            ['Dormant',       'সুপ্ত / নিষ্ক্রিয়',             '⭐ Medical Likely', 'inactive'],
            ['Dysfunction',   'অকার্যকারিতা',                    '⭐ Medical Likely', 'malfunction'],
            ['Echocardiogram','হৃদ আল্ট্রাসাউন্ড',              '⭐ Medical Likely', 'heart scan'],
            ['Electrolyte',   'তড়িৎবিশ্লেষ্য পদার্থ',         '⭐ Medical Likely', 'mineral salt'],
            ['Embolism',      'রক্ত জমাট / রক্তনালি বন্ধ',    '⭐ Medical Likely', 'blockage'],
            ['Endoscopy',     'অন্তরদর্শন',                       '⭐ Medical Likely', 'internal exam'],
            ['Enzyme',        'এনজাইম / উৎসেচক',               '⭐ Medical Likely', 'catalyst'],
            ['Epidermis',     'ত্বকের বাইরের স্তর',             '⭐ Medical Likely', 'outer skin'],
            ['Estrogen',      'ইস্ট্রোজেন হরমোন',               '⭐ Medical Likely', 'female hormone'],
            ['Excrete',       'বর্জ্য নিষ্কাশন করা',            '⭐ Medical Likely', 'expel'],
            ['Fibrous',       'তন্তুময়',                         '⭐ Medical Likely', 'fiber-like'],
            ['Gallbladder',   'পিত্তথলি',                        '⭐ Medical Likely', 'bile sac'],
            ['Gangrene',      'পচন রোগ',                         '⭐ Medical Likely', 'tissue death'],
            ['Gastrointestinal','পাকস্থলী ও অন্ত্র সম্পর্কিত','⭐ Medical Likely', 'digestive'],
            ['Genome',        'জিনোম / সম্পূর্ণ জিন সমষ্টি',  '⭐ Medical Likely', 'genetic code'],
            ['Hematology',    'রক্তবিজ্ঞান',                     '⭐ Medical Likely', 'blood science'],
            ['Hormone',       'হরমোন',                           '⭐ Medical Likely', 'chemical signal'],
            ['Hypertrophy',   'অতিরিক্ত বৃদ্ধি',                '⭐ Medical Likely', 'enlargement'],
            ['Hypoglycemia',  'রক্তে সুগার কমে যাওয়া',         '⭐ Medical Likely', 'low blood sugar'],
            ['Hypoxia',       'অক্সিজেন স্বল্পতা',              '⭐ Medical Likely', 'oxygen deficiency'],
            ['Immunology',    'রোগ প্রতিরোধ বিজ্ঞান',           '⭐ Medical Likely', 'immunity science'],
            ['Incision',      'ছেদ / অস্ত্রোপচারের কাটা',      '⭐ Medical Likely', 'cut'],
            ['Insulin',       'ইনসুলিন হরমোন',                   '⭐ Medical Likely', 'glucose hormone'],
            ['Intubation',    'নল ঢোকানো (শ্বাসনালিতে)',        '⭐ Medical Likely', 'tube insertion'],
            ['Lesion',        'ক্ষত / আঘাত',                    '⭐ Medical Likely', 'wound'],
            ['Liver',         'যকৃত',                            '⭐ Medical Likely', 'hepatic organ'],
            ['Lumbar',        'কটিদেশীয় / পিঠের নিচের অংশ', '⭐ Medical Likely', 'lower back'],
            ['Lymphoma',      'লিম্ফ গ্রন্থির ক্যান্সার',       '⭐ Medical Likely', 'lymph cancer'],
            ['Malaria',       'ম্যালেরিয়া',                     '⭐ Medical Likely', 'mosquito fever'],
            ['Malnourished',  'অপুষ্টিতে ভোগা',                 '⭐ Medical Likely', 'underfed'],
            ['Mastectomy',    'স্তন অপসারণ অস্ত্রোপচার',        '⭐ Medical Likely', 'breast removal'],
            ['Menopause',     'ঋতুবন্ধ',                         '⭐ Medical Likely', 'end of periods'],
            ['Metabolism',    'বিপাক',                           '⭐ Medical Likely', 'chemical process'],
            ['Microbiology',  'অণুজীববিজ্ঞান',                  '⭐ Medical Likely', 'germ science'],
            ['Morphology',    'আকারবিজ্ঞান',                     '⭐ Medical Likely', 'form study'],
            ['Mutation',      'জিন পরিবর্তন',                   '⭐ Medical Likely', 'genetic change'],
            ['Nephrology',    'কিডনি বিজ্ঞান',                  '⭐ Medical Likely', 'kidney science'],
            ['Neurotransmitter','স্নায়ু বার্তাবাহক',            '⭐ Medical Likely', 'brain chemical'],
            ['Obstetrician',  'প্রসূতি বিশেষজ্ঞ',              '⭐ Medical Likely', 'birth doctor'],
            ['Ophthalmology', 'চক্ষুবিজ্ঞান',                   '⭐ Medical Likely', 'eye science'],
            ['Orthopedics',   'হাড় বিজ্ঞান',                   '⭐ Medical Likely', 'bone science'],
            ['Osteoporosis',  'হাড় ক্ষয় রোগ',                 '⭐ Medical Likely', 'bone loss'],
            ['Palpitation',   'বুক ধড়ফড়',                      '⭐ Medical Likely', 'heart flutter'],
            ['Pathogenic',    'রোগসৃষ্টিকারী',                  '⭐ Medical Likely', 'disease-causing'],
            ['Pediatrics',    'শিশুচিকিৎসা',                    '⭐ Medical Likely', 'child medicine'],
            ['Peptic',        'পাকস্থলীর এসিড সম্পর্কিত',      '⭐ Medical Likely', 'stomach acid'],
            ['Pharmacology',  'ওষুধবিজ্ঞান',                    '⭐ Medical Likely', 'drug science'],
            ['Phlebotomy',    'রক্ত তোলা',                       '⭐ Medical Likely', 'blood draw'],
            ['Placenta',      'গর্ভফুল',                         '⭐ Medical Likely', 'afterbirth'],
            ['Plasma',        'রক্তরস',                          '⭐ Medical Likely', 'blood fluid'],
            ['Psychiatry',    'মানসিক রোগবিজ্ঞান',              '⭐ Medical Likely', 'mental medicine'],
            ['Pulmonary',     'ফুসফুস সম্পর্কিত',               '⭐ Medical Likely', 'lung-related'],
            ['Radiology',     'রেডিওলজি / এক্স-রে বিজ্ঞান',   '⭐ Medical Likely', 'imaging science'],
            ['Receptor',      'গ্রাহক / রিসেপ্টর',             '⭐ Medical Likely', 'cell receptor'],
            ['Rehabilitation','পুনর্বাসন',                        '⭐ Medical Likely', 'recovery'],
            ['Respiratory',   'শ্বাসযন্ত্র সম্পর্কিত',         '⭐ Medical Likely', 'breathing-related'],
            ['Retina',        'চোখের পর্দা',                     '⭐ Medical Likely', 'eye membrane'],
            ['Rheumatology',  'গাঁটব্যথা বিজ্ঞান',             '⭐ Medical Likely', 'joint disease'],
            ['Sclerosis',     'শক্ত হয়ে যাওয়া',               '⭐ Medical Likely', 'hardening'],
            ['Serum',         'রক্তজলীয় পদার্থ',               '⭐ Medical Likely', 'blood serum'],
            ['Somatic',       'শরীর সম্পর্কিত',                 '⭐ Medical Likely', 'body-related'],
            ['Spleen',        'প্লীহা',                          '⭐ Medical Likely', 'organ'],
            ['Sterilize',     'জীবাণুমুক্ত করা',               '⭐ Medical Likely', 'disinfect'],
            ['Suture',        'সেলাই করা (ক্ষত)',               '⭐ Medical Likely', 'stitch'],
            ['Tachycardia',   'দ্রুত হৃদস্পন্দন',              '⭐ Medical Likely', 'fast heartbeat'],
            ['Thyroid',       'থাইরয়েড গ্রন্থি',               '⭐ Medical Likely', 'neck gland'],
            ['Toxicology',    'বিষবিজ্ঞান',                      '⭐ Medical Likely', 'poison science'],
            ['Trachea',       'শ্বাসনালি',                       '⭐ Medical Likely', 'windpipe'],
            ['Transfusion',   'রক্ত সঞ্চালন',                   '⭐ Medical Likely', 'blood transfer'],
            ['Tuberculosis',  'যক্ষ্মা',                         '⭐ Medical Likely', 'TB disease'],
            ['Uterus',        'জরায়ু',                           '⭐ Medical Likely', 'womb'],
            ['Vasodilator',   'রক্তনালি প্রসারক',               '⭐ Medical Likely', 'vessel widener'],
            ['Ventricle',     'হৃদপিণ্ডের প্রকোষ্ঠ',           '⭐ Medical Likely', 'heart chamber'],
            ['Vertebra',      'মেরুদণ্ডের হাড়',               '⭐ Medical Likely', 'spine bone'],
            ['Virology',      'ভাইরাসবিজ্ঞান',                  '⭐ Medical Likely', 'virus science'],
            ['Visceral',      'অভ্যন্তরীণ অঙ্গ সম্পর্কিত',    '⭐ Medical Likely', 'organ-related'],
            ['Zoonosis',      'পশু থেকে মানুষে ছড়ানো রোগ',    '⭐ Medical Likely', 'animal disease'],
        ];

        // ════════════════════════════════════════════════════════════
        // BANK LESSON 1 WORDS
        // ════════════════════════════════════════════════════════════
        $bankL1 = [
            ['📌 দ্রষ্টব্য', 'পরীক্ষার নাম ও সাল আমাদের গবেষণার উপর ভিত্তি করে তৈরি। কিছু ক্ষেত্রে আগে-পরে হতে পারে। এই অসুবিধার জন্য আমরা আন্তরিকভাবে দুঃখিত। শব্দ ও অর্থগুলো সম্পূর্ণ নির্ভুল। 📚', '⚠️ Disclaimer', 'Our Research'],

            ['Abrupt',        'হঠাৎ / আকস্মিক',                'Sonali Bank-2019',   'sudden'],
            ['Accrue',        'জমা হওয়া / সঞ্চিত হওয়া',      'Janata Bank-2020',   'accumulate'],
            ['Accurate',      'নির্ভুল / সঠিক',               'Agrani Bank-2021',   'precise'],
            ['Acquaint',      'পরিচিত করানো',                   'BB Job-2019',         'familiarize'],
            ['Adept',         'দক্ষ / পারদর্শী',              'Sonali Bank-2020',   'skilled'],
            ['Adequate',      'পর্যাপ্ত / যথেষ্ট',            'Janata Bank-2021',   'sufficient'],
            ['Adjudicate',    'বিচার করা',                      'Agrani Bank-2022',   'judge'],
            ['Administer',    'পরিচালনা করা',                   'BB Job-2020',         'manage'],
            ['Adversary',     'প্রতিপক্ষ / শত্রু',            'Sonali Bank-2021',   'opponent'],
            ['Affluent',      'ধনী / সমৃদ্ধ',                 'Janata Bank-2022',   'wealthy'],
            ['Aggregate',     'মোট / সমষ্টি',                  'Agrani Bank-2019',   'total'],
            ['Agile',         'চটপটে / দ্রুত',                'BB Job-2021',         'nimble'],
            ['Allocate',      'বরাদ্দ দেওয়া',                  'Sonali Bank-2022',   'assign'],
            ['Altruistic',    'পরোপকারী',                       'Janata Bank-2019',   'selfless'],
            ['Ambiguous',     'দ্ব্যর্থবোধক',                   'Agrani Bank-2020',   'vague'],
            ['Amend',         'সংশোধন করা',                    'BB Job-2022',         'revise'],
            ['Amicable',      'সৌহার্দ্যপূর্ণ',                'Sonali Bank-2019',   'friendly'],
            ['Ample',         'প্রচুর / যথেষ্ট',              'Janata Bank-2020',   'plenty'],
            ['Annex',         'সংযুক্ত করা / দখল করা',        'Agrani Bank-2021',   'attach'],
            ['Annul',         'বাতিল করা',                     'BB Job-2019',         'cancel'],
            ['Anomaly',       'অস্বাভাবিকতা / ব্যতিক্রম',    'Sonali Bank-2020',   'irregularity'],
            ['Appease',       'সন্তুষ্ট করা',                  'Janata Bank-2021',   'pacify'],
            ['Aptitude',      'যোগ্যতা / স্বাভাবিক দক্ষতা',  'Agrani Bank-2022',   'ability'],
            ['Arbitrary',     'খেয়ালখুশিমতো',                  'BB Job-2020',         'random'],
            ['Ardent',        'আগ্রহী / উৎসাহী',              'Sonali Bank-2021',   'passionate'],
            ['Articulate',    'স্পষ্টভাষী',                    'Janata Bank-2022',   'eloquent'],
            ['Astute',        'চতুর / বিচক্ষণ',               'Agrani Bank-2019',   'shrewd'],
            ['Audit',         'হিসাব পরীক্ষা',                  'BB Job-2021',         'account check'],
            ['Authenticate',  'প্রমাণ করা / সত্যাপন করা',     'Sonali Bank-2022',   'verify'],
            ['Authorize',     'অনুমোদন দেওয়া',                 'Janata Bank-2019',   'permit'],
            ['Autonomous',    'স্বায়ত্তশাসিত',                  'Agrani Bank-2020',   'independent'],
            ['Benchmark',     'মানদণ্ড / তুলনার ভিত্তি',     'BB Job-2022',         'standard'],
            ['Benevolent',    'দয়ালু',                         'Sonali Bank-2019',   'kind'],
            ['Bilateral',     'দ্বিপক্ষীয়',                    'Janata Bank-2020',   'two-sided'],
            ['Brevity',       'সংক্ষিপ্ততা',                   'Agrani Bank-2021',   'conciseness'],
            ['Bureaucracy',   'আমলাতন্ত্র',                     'BB Job-2019',         'administration'],
            ['Candid',        'সৎ / খোলামেলা',                'Sonali Bank-2020',   'frank'],
            ['Caution',       'সতর্কতা',                        'Janata Bank-2021',   'care'],
            ['Circumspect',   'সতর্ক',                          'Agrani Bank-2022',   'cautious'],
            ['Clarity',       'স্পষ্টতা',                      'BB Job-2020',         'clearness'],
            ['Coherent',      'সামঞ্জস্যপূর্ণ',                'Sonali Bank-2021',   'consistent'],
            ['Collaborate',   'সহযোগিতা করা',                   'Janata Bank-2022',   'cooperate'],
            ['Collateral',    'জামানত / অতিরিক্ত নিরাপত্তা',  'Agrani Bank-2019',   'security'],
            ['Competent',     'দক্ষ / যোগ্য',                 'BB Job-2021',         'capable'],
            ['Compliance',    'নিয়ম মানা',                     'Sonali Bank-2022',   'obedience'],
            ['Comprehensive', 'ব্যাপক / সামগ্রিক',             'Janata Bank-2019',   'thorough'],
            ['Concise',       'সংক্ষিপ্ত',                     'Agrani Bank-2020',   'brief'],
            ['Conducive',     'সহায়ক / অনুকূল',               'BB Job-2022',         'helpful'],
            ['Conspicuous',   'সুস্পষ্ট',                      'Sonali Bank-2019',   'obvious'],
            ['Contemplate',   'চিন্তা করা / বিবেচনা করা',     'Janata Bank-2020',   'consider'],
            ['Contingent',    'নির্ভরশীল / সম্ভাব্য',         'Agrani Bank-2021',   'dependent'],
            ['Controversial', 'বিতর্কিত',                       'BB Job-2019',         'disputed'],
            ['Credibility',   'বিশ্বাসযোগ্যতা',               'Sonali Bank-2020',   'trustworthiness'],
            ['Curtail',       'কমানো',                          'Janata Bank-2021',   'reduce'],
            ['Decisive',      'দৃঢ়প্রতিজ্ঞ',                  'Agrani Bank-2022',   'determined'],
            ['Deduce',        'অনুমান করা',                    'BB Job-2020',         'conclude'],
            ['Delegate',      'ক্ষমতা অর্পণ করা',             'Sonali Bank-2021',   'assign'],
            ['Deliberate',    'ইচ্ছাকৃত',                       'Janata Bank-2022',   'intentional'],
            ['Delinquent',    'অপরাধী / দেরিতে পরিশোধকারী',  'Agrani Bank-2019',   'offender'],
            ['Deplete',       'নিঃশেষ করা / কমানো',           'BB Job-2021',         'exhaust'],
            ['Derive',        'আহরণ করা / পাওয়া',             'Sonali Bank-2022',   'obtain'],
            ['Deter',         'নিরুৎসাহিত করা',                'Janata Bank-2019',   'discourage'],
            ['Diligent',      'পরিশ্রমী',                       'Agrani Bank-2020',   'hardworking'],
            ['Discern',       'পার্থক্য করা / বোঝা',          'BB Job-2022',         'distinguish'],
            ['Disparity',     'বৈষম্য',                         'Sonali Bank-2019',   'inequality'],
            ['Diverse',       'বৈচিত্র্যময়',                  'Janata Bank-2020',   'varied'],
            ['Dominant',      'প্রভাবশালী',                    'Agrani Bank-2021',   'powerful'],
            ['Dubious',       'সন্দেহজনক',                     'BB Job-2019',         'doubtful'],
            ['Durable',       'টেকসই / দীর্ঘস্থায়ী',         'Sonali Bank-2020',   'lasting'],
            ['Economize',     'সাশ্রয় করা',                   'Janata Bank-2021',   'save'],
            ['Efficacious',   'কার্যকর',                        'Agrani Bank-2022',   'effective'],
            ['Efficient',     'দক্ষ / কার্যকর',               'BB Job-2020',         'effective'],
            ['Elaborate',     'বিস্তারিত',                      'Sonali Bank-2021',   'detailed'],
            ['Eloquent',      'সুবক্তা',                        'Janata Bank-2022',   'articulate'],
            ['Embargo',       'বাণিজ্য নিষেধাজ্ঞা',           'Agrani Bank-2019',   'trade ban'],
            ['Eminent',       'বিশিষ্ট / প্রখ্যাত',           'BB Job-2021',         'notable'],
            ['Endorse',       'সমর্থন করা',                    'Sonali Bank-2022',   'support'],
            ['Enforce',       'বলবৎ করা',                      'Janata Bank-2019',   'implement'],
            ['Ensure',        'নিশ্চিত করা',                   'Agrani Bank-2020',   'guarantee'],
            ['Equitable',     'ন্যায্য / সমতাভিত্তিক',        'BB Job-2022',         'fair'],
            ['Equivalent',    'সমতুল্য',                        'Sonali Bank-2019',   'equal'],
            ['Eradicate',     'নির্মূল করা',                   'Janata Bank-2020',   'eliminate'],
            ['Essential',     'অপরিহার্য',                      'Agrani Bank-2021',   'necessary'],
            ['Evaluate',      'মূল্যায়ন করা',                  'BB Job-2019',         'assess'],
            ['Evident',       'স্পষ্ট / প্রকাশ্য',            'Sonali Bank-2020',   'obvious'],
            ['Exemplary',     'আদর্শ',                          'Janata Bank-2021',   'model'],
            ['Expedite',      'দ্রুততর করা',                   'Agrani Bank-2022',   'speed up'],
            ['Explicit',      'স্পষ্ট',                        'BB Job-2020',         'clear'],
            ['Facilitate',    'সহজতর করা',                     'Sonali Bank-2021',   'ease'],
            ['Feasible',      'সম্ভবপর',                        'Janata Bank-2022',   'possible'],
            ['Flexible',      'নমনীয়',                          'Agrani Bank-2019',   'adaptable'],
            ['Fraudulent',    'প্রতারণামূলক',                   'BB Job-2021',         'dishonest'],
            ['Frugal',        'মিতব্যয়ী',                     'Sonali Bank-2022',   'thrifty'],
            ['Genuine',       'আসল / খাঁটি',                  'Janata Bank-2019',   'authentic'],
            ['Grievance',     'অভিযোগ / অসন্তোষ',             'Agrani Bank-2020',   'complaint'],
            ['Hamper',        'বাধা দেওয়া',                    'BB Job-2022',         'hinder'],
            ['Harmonious',    'সামঞ্জস্যপূর্ণ',                'Sonali Bank-2019',   'balanced'],
            ['Impartial',     'নিরপেক্ষ',                      'Janata Bank-2020',   'unbiased'],
            ['Implement',     'বাস্তবায়ন করা',                 'Agrani Bank-2021',   'execute'],
            ['Incentive',     'প্রণোদনা',                       'BB Job-2019',         'motivation'],
            ['Indispensable', 'অপরিহার্য',                      'Sonali Bank-2020',   'essential'],
            ['Integrity',     'সততা / নীতিনিষ্ঠা',           'Janata Bank-2021',   'honesty'],
            ['Interim',       'অন্তর্বর্তীকালীন',              'Agrani Bank-2022',   'temporary'],
            ['Intrinsic',     'অন্তর্নিহিত / স্বাভাবিক',     'BB Job-2020',         'inherent'],
            ['Judicial',      'বিচারবিভাগীয়',                  'Sonali Bank-2021',   'legal'],
            ['Juxtapose',     'পাশাপাশি রাখা',                  'Janata Bank-2022',   'compare'],
            ['Legitimate',    'বৈধ',                            'Agrani Bank-2019',   'lawful'],
            ['Liable',        'দায়ী',                           'BB Job-2021',         'responsible'],
            ['Lucrative',     'লাভজনক',                         'Sonali Bank-2022',   'profitable'],
            ['Mandate',       'নির্দেশ / আদেশ',               'Janata Bank-2019',   'order'],
            ['Meticulous',    'সূক্ষ্মদর্শী',                  'Agrani Bank-2020',   'careful'],
            ['Mitigate',      'প্রশমিত করা',                   'BB Job-2022',         'reduce'],
            ['Monetary',      'আর্থিক / মুদ্রা সম্পর্কিত',   'Sonali Bank-2019',   'financial'],
            ['Negotiate',     'আলোচনা করা',                    'Janata Bank-2020',   'discuss'],
            ['Neutral',       'নিরপেক্ষ',                       'Agrani Bank-2021',   'impartial'],
            ['Nominal',       'নামমাত্র',                       'BB Job-2019',         'token'],
            ['Objective',     'উদ্দেশ্য / লক্ষ্য',            'Sonali Bank-2020',   'goal'],
            ['Obligatory',    'বাধ্যতামূলক',                   'Janata Bank-2021',   'compulsory'],
            ['Obsolete',      'অচল / পুরনো',                   'Agrani Bank-2022',   'outdated'],
            ['Paramount',     'সর্বোচ্চ / সবচেয়ে গুরুত্বপূর্ণ','BB Job-2020',       'supreme'],
            ['Pragmatic',     'বাস্তবসম্মত',                   'Sonali Bank-2021',   'practical'],
            ['Preclude',      'বাধা দেওয়া',                    'Janata Bank-2022',   'prevent'],
            ['Prerequisite',  'পূর্বশর্ত',                      'Agrani Bank-2019',   'requirement'],
            ['Proficient',    'দক্ষ',                           'BB Job-2021',         'skilled'],
            ['Proliferate',   'বৃদ্ধি পাওয়া',                 'Sonali Bank-2022',   'multiply'],
            ['Prudent',       'বিচক্ষণ',                        'Janata Bank-2019',   'wise'],
            ['Rectify',       'সংশোধন করা',                    'Agrani Bank-2020',   'correct'],
            ['Redundant',     'অতিরিক্ত / অপ্রয়োজনীয়',      'BB Job-2022',         'unnecessary'],
            ['Resilient',     'সহনশীল',                         'Sonali Bank-2019',   'tough'],
            ['Revenue',       'রাজস্ব / আয়',                  'Janata Bank-2020',   'income'],
            ['Rigorous',      'কঠোর',                           'Agrani Bank-2021',   'strict'],
            ['Scrutinize',    'ভালোভাবে পরীক্ষা করা',         'BB Job-2019',         'examine'],
            ['Solvency',      'ঋণমুক্ততা / স্বচ্ছলতা',        'Sonali Bank-2020',   'financial health'],
            ['Spurious',      'ভেজাল / নকল',                  'Janata Bank-2021',   'fake'],
            ['Stringent',     'কঠোর',                           'Agrani Bank-2022',   'strict'],
            ['Subordinate',   'অধীনস্থ',                        'BB Job-2020',         'junior'],
            ['Substantial',   'উল্লেখযোগ্য / যথেষ্ট',        'Sonali Bank-2021',   'significant'],
            ['Succinct',      'সংক্ষিপ্ত',                     'Janata Bank-2022',   'brief'],
            ['Surplus',       'উদ্বৃত্ত / অতিরিক্ত',         'Agrani Bank-2019',   'excess'],
            ['Tangible',      'স্পর্শযোগ্য / বাস্তব',        'BB Job-2021',         'real'],
            ['Transparent',   'স্বচ্ছ',                         'Sonali Bank-2022',   'clear'],
            ['Unanimous',     'সর্বসম্মত',                      'Janata Bank-2019',   'agreed'],
            ['Undermine',     'দুর্বল করা / ক্ষতি করা',       'Agrani Bank-2020',   'weaken'],
            ['Validate',      'বৈধতা প্রমাণ করা',              'BB Job-2022',         'confirm'],
            ['Viable',        'কার্যকর / সম্ভবপর',            'Sonali Bank-2019',   'feasible'],
            ['Vigilant',      'সতর্ক',                          'Janata Bank-2020',   'watchful'],
            ['Volatile',      'অস্থির',                         'Agrani Bank-2021',   'unstable'],
            ['Waiver',        'দাবি ছেড়ে দেওয়া',             'BB Job-2019',         'relinquishment'],
            ['Yield',         'উৎপাদন / মুনাফা',              'Sonali Bank-2020',   'produce'],
            ['Zealous',       'উদ্যমী',                         'Janata Bank-2021',   'enthusiastic'],
        ];

        // ════════════════════════════════════════════════════════════
        // BANK LESSON 2 WORDS
        // ════════════════════════════════════════════════════════════
        $bankL2 = [
            ['Abscond',       'পালিয়ে যাওয়া',                  '⭐ Bank Likely',     'flee'],
            ['Accession',     'যোগদান / অনুমোদন',               '⭐ Bank Likely',     'joining'],
            ['Accrue',        'সঞ্চিত হওয়া',                    '⭐ Bank Likely',     'accumulate'],
            ['Acquisitive',   'সম্পদলোভী',                       '⭐ Bank Likely',     'greedy'],
            ['Acumen',        'তীক্ষ্ণ বুদ্ধি',                 '⭐ Bank Likely',     'insight'],
            ['Adroit',        'দক্ষ / চালাক',                   '⭐ Bank Likely',     'skillful'],
            ['Advocacy',      'সমর্থন / পক্ষাবলম্বন',          '⭐ Bank Likely',     'support'],
            ['Alacrity',      'উৎসাহ / তৎপরতা',               '⭐ Bank Likely',     'eagerness'],
            ['Allegation',    'অভিযোগ',                          '⭐ Bank Likely',     'accusation'],
            ['Altercation',   'বিবাদ / ঝগড়া',                  '⭐ Bank Likely',     'dispute'],
            ['Amalgamate',    'একত্রিত করা',                     '⭐ Bank Likely',     'merge'],
            ['Ambivalent',    'দ্বিধাগ্রস্ত',                   '⭐ Bank Likely',     'uncertain'],
            ['Ameliorate',    'উন্নত করা',                       '⭐ Bank Likely',     'improve'],
            ['Amortize',      'ঋণ পরিশোধ করা',                  '⭐ Bank Likely',     'pay off'],
            ['Annuity',       'বার্ষিক বৃত্তি / কিস্তি',       '⭐ Bank Likely',     'yearly payment'],
            ['Antagonize',    'শত্রুতা করা',                     '⭐ Bank Likely',     'oppose'],
            ['Apprehend',     'গ্রেপ্তার করা / বোঝা',          '⭐ Bank Likely',     'arrest'],
            ['Arbitrage',     'মূল্যভেদে মুনাফা করা',           '⭐ Bank Likely',     'price difference profit'],
            ['Arduous',       'কঠিন',                            '⭐ Bank Likely',     'difficult'],
            ['Aspire',        'আকাঙ্ক্ষা করা',                 '⭐ Bank Likely',     'desire'],
            ['Assertive',     'দৃঢ়মনা / আত্মবিশ্বাসী',        '⭐ Bank Likely',     'confident'],
            ['Attrition',     'ক্ষয় / ধীরে ধীরে হ্রাস',       '⭐ Bank Likely',     'gradual loss'],
            ['Austere',       'কঠোর',                            '⭐ Bank Likely',     'severe'],
            ['Avaricious',    'লোভী',                            '⭐ Bank Likely',     'greedy'],
            ['Beleaguer',     'অবরোধ করা / চাপে রাখা',         '⭐ Bank Likely',     'besiege'],
            ['Belligerent',   'আক্রমণাত্মক',                    '⭐ Bank Likely',     'aggressive'],
            ['Benchmark',     'মানদণ্ড',                         '⭐ Bank Likely',     'standard'],
            ['Beneficiary',   'সুবিধাভোগী',                     '⭐ Bank Likely',     'recipient'],
            ['Benevolent',    'দয়ালু',                          '⭐ Bank Likely',     'kind'],
            ['Circumvent',    'এড়িয়ে যাওয়া',                   '⭐ Bank Likely',     'bypass'],
            ['Coalesce',      'একত্রিত হওয়া',                   '⭐ Bank Likely',     'merge'],
            ['Coerce',        'জোর করা',                         '⭐ Bank Likely',     'compel'],
            ['Cogent',        'যুক্তিসংগত',                     '⭐ Bank Likely',     'convincing'],
            ['Commensurate',  'সামঞ্জস্যপূর্ণ',                 '⭐ Bank Likely',     'proportional'],
            ['Concede',       'স্বীকার করা',                    '⭐ Bank Likely',     'admit'],
            ['Conciliate',    'মিটমাট করা',                      '⭐ Bank Likely',     'reconcile'],
            ['Condone',       'উপেক্ষা করা',                    '⭐ Bank Likely',     'overlook'],
            ['Confiscate',    'বাজেয়াপ্ত করা',                 '⭐ Bank Likely',     'seize'],
            ['Convoluted',    'জটিল',                            '⭐ Bank Likely',     'complex'],
            ['Copious',       'প্রচুর',                          '⭐ Bank Likely',     'abundant'],
            ['Corroborate',   'প্রমাণ করা',                     '⭐ Bank Likely',     'confirm'],
            ['Culpable',      'দোষী',                            '⭐ Bank Likely',     'guilty'],
            ['Curtail',       'কমানো',                           '⭐ Bank Likely',     'reduce'],
            ['Cynical',       'সংশয়বাদী',                      '⭐ Bank Likely',     'skeptical'],
            ['Debacle',       'বিপর্যয়',                        '⭐ Bank Likely',     'disaster'],
            ['Decorum',       'শালীনতা',                         '⭐ Bank Likely',     'propriety'],
            ['Deferential',   'বিনয়ী',                          '⭐ Bank Likely',     'respectful'],
            ['Deleterious',   'ক্ষতিকর',                        '⭐ Bank Likely',     'harmful'],
            ['Denounce',      'নিন্দা করা',                     '⭐ Bank Likely',     'condemn'],
            ['Depreciate',    'মূল্য কমানো',                    '⭐ Bank Likely',     'devalue'],
            ['Derogatory',    'অবমাননাকর',                      '⭐ Bank Likely',     'insulting'],
            ['Deter',         'নিরুৎসাহিত করা',                 '⭐ Bank Likely',     'discourage'],
            ['Diffident',     'আত্মবিশ্বাসহীন',                '⭐ Bank Likely',     'shy'],
            ['Discreet',      'বিচক্ষণ / সতর্ক',               '⭐ Bank Likely',     'careful'],
            ['Disparage',     'অবজ্ঞা করা',                     '⭐ Bank Likely',     'belittle'],
            ['Dissemble',     'ভান করা',                         '⭐ Bank Likely',     'conceal'],
            ['Diverge',       'বিচ্যুত হওয়া',                  '⭐ Bank Likely',     'deviate'],
            ['Dogmatic',      'গোঁড়া',                          '⭐ Bank Likely',     'rigid'],
            ['Duplicity',     'দ্বিমুখিতা',                     '⭐ Bank Likely',     'deceit'],
            ['Ebullient',     'উৎসাহী',                          '⭐ Bank Likely',     'enthusiastic'],
            ['Embezzle',      'আত্মসাৎ করা',                   '⭐ Bank Likely',     'misappropriate'],
            ['Eminent',       'বিশিষ্ট',                         '⭐ Bank Likely',     'notable'],
            ['Empirical',     'অভিজ্ঞতাভিত্তিক',               '⭐ Bank Likely',     'practical'],
            ['Ephemeral',     'ক্ষণস্থায়ী',                    '⭐ Bank Likely',     'transient'],
            ['Equanimity',    'মানসিক শান্তি',                  '⭐ Bank Likely',     'calmness'],
            ['Equivocal',     'দ্ব্যর্থবোধক',                   '⭐ Bank Likely',     'ambiguous'],
            ['Erudite',       'পণ্ডিত',                          '⭐ Bank Likely',     'learned'],
            ['Exacerbate',    'আরও খারাপ করা',                  '⭐ Bank Likely',     'worsen'],
            ['Exonerate',     'নির্দোষ প্রমাণ করা',             '⭐ Bank Likely',     'acquit'],
            ['Expedient',     'সুবিধাজনক',                       '⭐ Bank Likely',     'practical'],
            ['Extravagant',   'অপব্যয়ী',                        '⭐ Bank Likely',     'wasteful'],
            ['Fastidious',    'খুঁতখুঁতে',                     '⭐ Bank Likely',     'fussy'],
            ['Fiduciary',     'আমানতদার',                        '⭐ Bank Likely',     'trustee'],
            ['Flagrant',      'প্রকাশ্য / ন্যক্কারজনক',        '⭐ Bank Likely',     'obvious'],
            ['Forensic',      'আদালতসংক্রান্ত / বৈজ্ঞানিক তদন্ত','⭐ Bank Likely', 'investigative'],
            ['Frugal',        'মিতব্যয়ী',                      '⭐ Bank Likely',     'thrifty'],
            ['Futile',        'নিরর্থক',                         '⭐ Bank Likely',     'useless'],
            ['Gratuitous',    'অকারণ',                           '⭐ Bank Likely',     'unnecessary'],
            ['Gregarious',    'মিশুক',                           '⭐ Bank Likely',     'sociable'],
            ['Hegemony',      'আধিপত্য',                         '⭐ Bank Likely',     'dominance'],
            ['Hubris',        'অতিরিক্ত অহংকার',               '⭐ Bank Likely',     'arrogance'],
            ['Impartial',     'নিরপেক্ষ',                       '⭐ Bank Likely',     'unbiased'],
            ['Impede',        'বাধা দেওয়া',                    '⭐ Bank Likely',     'obstruct'],
            ['Imperative',    'জরুরি',                           '⭐ Bank Likely',     'essential'],
            ['Impugn',        'প্রশ্ন তোলা',                    '⭐ Bank Likely',     'challenge'],
            ['Insolvent',     'দেউলিয়া',                        '⭐ Bank Likely',     'bankrupt'],
            ['Intrepid',      'নির্ভীক',                         '⭐ Bank Likely',     'fearless'],
            ['Inveterate',    'পুরনো অভ্যাসে আসক্ত',           '⭐ Bank Likely',     'habitual'],
            ['Judicious',     'বিচক্ষণ',                         '⭐ Bank Likely',     'wise'],
            ['Laconic',       'সংক্ষিপ্তভাষী',                  '⭐ Bank Likely',     'brief'],
            ['Laud',          'প্রশংসা করা',                    '⭐ Bank Likely',     'praise'],
            ['Mendacious',    'মিথ্যাবাদী',                     '⭐ Bank Likely',     'dishonest'],
            ['Meticulous',    'সূক্ষ্মদর্শী',                  '⭐ Bank Likely',     'careful'],
            ['Mitigate',      'প্রশমিত করা',                    '⭐ Bank Likely',     'reduce'],
            ['Mollify',       'শান্ত করা',                      '⭐ Bank Likely',     'pacify'],
            ['Myriad',        'অগণিত',                           '⭐ Bank Likely',     'numerous'],
            ['Nascent',       'সদ্য উদ্ভূত',                    '⭐ Bank Likely',     'emerging'],
            ['Nebulous',      'অস্পষ্ট',                        '⭐ Bank Likely',     'vague'],
            ['Nonchalant',    'উদাসীন',                          '⭐ Bank Likely',     'indifferent'],
            ['Obfuscate',     'জটিল করা',                        '⭐ Bank Likely',     'confuse'],
            ['Ostentation',   'আড়ম্বর',                         '⭐ Bank Likely',     'showiness'],
            ['Panacea',       'সর্বরোগের ওষুধ',                 '⭐ Bank Likely',     'cure-all'],
            ['Paucity',       'অভাব',                            '⭐ Bank Likely',     'scarcity'],
            ['Pedantic',      'বেশি নিয়মনিষ্ঠ',                '⭐ Bank Likely',     'fussy'],
            ['Perfidious',    'বিশ্বাসঘাতক',                    '⭐ Bank Likely',     'treacherous'],
            ['Pernicious',    'ক্ষতিকর',                        '⭐ Bank Likely',     'harmful'],
            ['Philanthropy',  'জনহিতকর কাজ',                   '⭐ Bank Likely',     'charity'],
            ['Placid',        'শান্ত',                           '⭐ Bank Likely',     'calm'],
            ['Pragmatic',     'বাস্তবসম্মত',                   '⭐ Bank Likely',     'practical'],
            ['Precarious',    'অনিশ্চিত',                       '⭐ Bank Likely',     'uncertain'],
            ['Preclude',      'বাধা দেওয়া',                    '⭐ Bank Likely',     'prevent'],
            ['Profligate',    'অপব্যয়ী',                        '⭐ Bank Likely',     'extravagant'],
            ['Propitious',    'অনুকূল',                          '⭐ Bank Likely',     'favorable'],
            ['Recalcitrant',  'অবাধ্য',                          '⭐ Bank Likely',     'stubborn'],
            ['Recant',        'প্রত্যাহার করা',                 '⭐ Bank Likely',     'retract'],
            ['Repudiate',     'প্রত্যাখ্যান করা',               '⭐ Bank Likely',     'reject'],
            ['Rescind',       'বাতিল করা',                      '⭐ Bank Likely',     'cancel'],
            ['Reticent',      'কম কথা বলে',                     '⭐ Bank Likely',     'reserved'],
            ['Sagacious',     'বিচক্ষণ',                        '⭐ Bank Likely',     'wise'],
            ['Sanguine',      'আশাবাদী',                         '⭐ Bank Likely',     'optimistic'],
            ['Salient',       'প্রধান',                          '⭐ Bank Likely',     'prominent'],
            ['Scrupulous',    'বিবেকবান',                        '⭐ Bank Likely',     'principled'],
            ['Sophistry',     'ভ্রান্ত যুক্তি',                 '⭐ Bank Likely',     'fallacy'],
            ['Specious',      'দেখতে সত্য কিন্তু মিথ্যা',     '⭐ Bank Likely',     'misleading'],
            ['Sporadic',      'অনিয়মিত',                        '⭐ Bank Likely',     'irregular'],
            ['Subversive',    'বিদ্রোহমূলক',                    '⭐ Bank Likely',     'rebellious'],
            ['Sycophancy',    'তোষামোদ',                         '⭐ Bank Likely',     'flattery'],
            ['Tacit',         'নীরব / অব্যক্ত',                '⭐ Bank Likely',     'implied'],
            ['Tenacious',     'দৃঢ়প্রতিজ্ঞ',                  '⭐ Bank Likely',     'persistent'],
            ['Tirade',        'তীব্র নিন্দাবক্তৃতা',            '⭐ Bank Likely',     'outburst'],
            ['Truculent',     'আক্রমণাত্মক',                    '⭐ Bank Likely',     'aggressive'],
            ['Ubiquitous',    'সর্বত্র বিদ্যমান',               '⭐ Bank Likely',     'everywhere'],
            ['Vacillate',     'দোদুল্যমান হওয়া',               '⭐ Bank Likely',     'waver'],
            ['Venal',         'ঘুষখোর',                          '⭐ Bank Likely',     'corrupt'],
            ['Vindicate',     'নির্দোষ প্রমাণ করা',             '⭐ Bank Likely',     'justify'],
            ['Virulent',      'বিষাক্ত / তীব্র',               '⭐ Bank Likely',     'toxic'],
            ['Vociferous',    'উচ্চস্বরে প্রতিবাদী',           '⭐ Bank Likely',     'loud'],
            ['Volatile',      'অস্থির',                          '⭐ Bank Likely',     'unstable'],
            ['Wanton',        'অর্থহীন / উচ্ছৃঙ্খল',          '⭐ Bank Likely',     'reckless'],
            ['Zealotry',      'অন্ধ উৎসাহ',                    '⭐ Bank Likely',     'fanaticism'],
        ];

        // ── Insert all words ──────────────────────────────────────
        foreach ([
            [$medL1, $medLesson1Id],
            [$medL2, $medLesson2Id],
            [$bankL1, $bankLesson1Id],
            [$bankL2, $bankLesson2Id],
        ] as [$words, $lessonId]) {
            $rows = [];
            foreach ($words as [$word, $meaning, $synonyms, $antonyms]) {
                $rows[] = [
                    'word'       => $word,
                    'meaning'    => $meaning,
                    'synonyms'   => $synonyms,
                    'antonyms'   => $antonyms,
                    'lesson_id'  => $lessonId,
                    'status'     => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
            DB::table('words')->insert($rows);
        }
    }

    public function down(): void
    {
        $chapter1 = DB::table('chapters')
            ->where('title', '🏥 Medical English — MBBS ভর্তি পরীক্ষার প্রস্তুতি')
            ->first();
        $chapter2 = DB::table('chapters')
            ->where('title', '🏦 Bank English — ব্যাংক ও আর্থিক প্রতিষ্ঠানের প্রস্তুতি')
            ->first();

        foreach ([$chapter1, $chapter2] as $chapter) {
            if ($chapter) {
                $lessons = DB::table('lessons')->where('chapter_id', $chapter->id)->get();
                foreach ($lessons as $lesson) {
                    DB::table('words')->where('lesson_id', $lesson->id)->delete();
                }
                DB::table('lessons')->where('chapter_id', $chapter->id)->delete();
                DB::table('chapters')->where('id', $chapter->id)->delete();
            }
        }
    }
};
