<?php
// Variables
return [
  "creatorName" => "",
  "creatorUrl" => "",
  "templateName" => "",
  "templateSuffix" => "",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "Designed & Developed by MD NAYEEM SARKER",
  "templateKeyword" => "",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "moreThemes" => "",
  "documentation" => "",
  "generator" => "",
  "changelog" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => "",
  "customKey" => "Abmn@!0171#Asha@Bizli#FL1234",
  "random_text" => "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ",
];
